// This is its own module, not a normal subpackage of examples/, so that
// order_typed.go's import of it is one `cleat build` can resolve locally.
//
// cleat build stages a WASM workflow with a flat, non-recursive copy of its
// own source directory (wasm/build.go, PrepareBuildDir) and nothing else --
// a subpackage of the workflow's own module can never be staged, and
// resolving it from the module proxy instead means either a loud failure
// (examples/ is not independently published) or, worse, a silent one
// against whatever commit happens to be reachable at @latest, which is not
// necessarily the one being built. See cleat#2658, and
// scripts/check-generated-plugin-clients.sh's identical reasoning for why
// cleat/pluginclients/{webhookingest,email} live inside the cleat/ module
// rather than under examples/order-lifecycle/ -- that fix does not apply
// here, because these clients are fooddash-specific fixtures, not reusable
// plugin clients, so cleat/ is not the right home for them. A nested module
// with an explicit replace is the general mechanism instead, and this file
// is the minimal shape of it: content in clients/*/client.go is unchanged
// (still "Code generated by cleat-gen. DO NOT EDIT."), and only a build
// boundary was added around it.
module github.com/cleat-team/cleat/examples/fooddash/clients

go 1.27.0

require github.com/cleat-team/cleat/cleat v0.0.0

replace github.com/cleat-team/cleat/cleat => ../../../cleat
