-- cleat mssql schema (generated)
-- Generated by scripts/gen-mssql-baseline from a database built by the real runner
-- over the chain this file replaces. Do not hand-edit: the next run of the
-- generator reverts it silently. See docs/contributor/migrations.md.
--
-- Seed data is 002_defaults.sql. Routines and security policies are
-- 003_procedures.sql, deliberately last so seed rows load before any
-- predicate exists -- SQL Server does not exempt sa from a BLOCK predicate.

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'admin')
    EXEC('CREATE SCHEMA [admin]');
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'cleat_admin' AND type = 'R')
    CREATE ROLE [cleat_admin];
GO

-- admin.orgs
CREATE TABLE admin.orgs (
    org_id uniqueidentifier NOT NULL CONSTRAINT DF__orgs__org_id__2BC97F7C DEFAULT (newid()),
    name nvarchar(255) NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__orgs__created_at__2CBDA3B5 DEFAULT (sysutcdatetime())
);
GO

-- admin.plugin_tables
CREATE TABLE admin.plugin_tables (
    plugin_name nvarchar(200) NOT NULL,
    table_name nvarchar(200) NOT NULL
);
GO

-- admin.rls_predicate_form
CREATE TABLE admin.rls_predicate_form (
    only_row bit NOT NULL CONSTRAINT DF__rls_predi__only___0F2D40CE DEFAULT ((1)),
    form nvarchar(16) NOT NULL,
    applied_at datetimeoffset(7) NOT NULL CONSTRAINT DF__rls_predi__appli__10216507 DEFAULT (sysutcdatetime())
);
GO

-- admin.tenant_api_keys
CREATE TABLE admin.tenant_api_keys (
    key_id uniqueidentifier NOT NULL CONSTRAINT DF__tenant_ap__key_i__4222D4EF DEFAULT (newid()),
    tenant_id uniqueidentifier NOT NULL,
    key_hash varbinary(32) NOT NULL,
    description nvarchar(max) NOT NULL CONSTRAINT DF__tenant_ap__descr__4316F928 DEFAULT (''),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenant_ap__creat__440B1D61 DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    expires_at datetimeoffset(7),
    oauth_identity nvarchar(512),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_api_keys_updated_at DEFAULT (sysutcdatetime())
);
GO

-- admin.tenant_egress_allow
CREATE TABLE admin.tenant_egress_allow (
    tenant_id uniqueidentifier NOT NULL,
    host nvarchar(255) NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenant_eg__creat__7C1A6C5A DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_egress_allow_updated_at DEFAULT (sysutcdatetime())
);
GO

-- admin.tenant_roles
CREATE TABLE admin.tenant_roles (
    tenant_id uniqueidentifier NOT NULL,
    role_name nvarchar(max) NOT NULL,
    password nvarchar(max) NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenant_ro__creat__49C3F6B7 DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_roles_updated_at DEFAULT (sysutcdatetime())
);
GO

-- admin.tenants
CREATE TABLE admin.tenants (
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__tenants__tenant___3C69FB99 DEFAULT (newid()),
    name nvarchar(255) NOT NULL,
    display_name nvarchar(max) NOT NULL CONSTRAINT DF__tenants__display__3D5E1FD2 DEFAULT (''),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenants__created__3E52440B DEFAULT (sysutcdatetime()),
    suspended bit NOT NULL CONSTRAINT DF__tenants__suspend__3F466844 DEFAULT ((0)),
    org_id uniqueidentifier NOT NULL CONSTRAINT df_tenants_org_id DEFAULT ('00000000-0000-0000-0000-000000000000')
);
GO

-- admin.workers
CREATE TABLE admin.workers (
    worker_id nvarchar(64) NOT NULL,
    hostname nvarchar(255) NOT NULL CONSTRAINT DF__workers__hostnam__72910220 DEFAULT (''),
    pid int NOT NULL CONSTRAINT DF__workers__pid__73852659 DEFAULT ((0)),
    concurrency int NOT NULL CONSTRAINT DF__workers__concurr__74794A92 DEFAULT ((0)),
    connection_budget int NOT NULL CONSTRAINT DF__workers__connect__756D6ECB DEFAULT ((0)),
    started_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workers__started__76619304 DEFAULT (sysutcdatetime()),
    last_heartbeat_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workers__last_he__7755B73D DEFAULT (sysutcdatetime()),
    secret_key_versions nvarchar(255)
);
GO

-- dbo.concurrency_keys
CREATE TABLE dbo.concurrency_keys (
    key_hash varbinary(32) NOT NULL,
    key_text nvarchar(max) NOT NULL,
    workflow_id nvarchar(255) NOT NULL,
    acquired_at datetimeoffset(7) NOT NULL CONSTRAINT DF__concurren__acqui__0E6E26BF DEFAULT (sysutcdatetime()),
    expires_at datetimeoffset(7) NOT NULL,
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__concurren__tenan__0F624AF8 DEFAULT ('00000000-0000-0000-0000-000000000000')
);
GO

-- dbo.deployment_secrets
CREATE TABLE dbo.deployment_secrets (
    name nvarchar(128) NOT NULL,
    ciphertext nvarchar(max) NOT NULL,
    key_version int NOT NULL CONSTRAINT df_deployment_secrets_keyver DEFAULT ((1)),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_deployment_secrets_updated DEFAULT (sysutcdatetime()),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT df_deployment_secrets_created DEFAULT (sysutcdatetime())
);
GO

-- dbo.event_history
CREATE TABLE dbo.event_history (
    workflow_id nvarchar(255) NOT NULL,
    step int NOT NULL,
    service nvarchar(255),
    operation nvarchar(255),
    request nvarchar(max),
    response nvarchar(max),
    error nvarchar(max),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__event_his__creat__6FE99F9F DEFAULT (sysutcdatetime()),
    event_type nvarchar(255) NOT NULL CONSTRAINT DF__event_his__event__70DDC3D8 DEFAULT ('call'),
    duration_ms bigint,
    signal_names nvarchar(512),
    timeout_ms bigint,
    signal_name nvarchar(255),
    signal_payload nvarchar(max),
    defer_description nvarchar(512),
    defer_id nvarchar(255),
    child_name nvarchar(255),
    child_input nvarchar(max),
    run_id nvarchar(255),
    new_input nvarchar(max),
    plugin_name nvarchar(255),
    plugin_func nvarchar(255),
    plugin_input nvarchar(max),
    plugin_output nvarchar(max),
    plugin_error nvarchar(max),
    promise_name nvarchar(255),
    promise_id nvarchar(255),
    promise_result nvarchar(max),
    promise_error nvarchar(max),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__event_his__tenan__71D1E811 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    payload nvarchar(max),
    checksum nvarchar(max),
    thread_id nvarchar(255) NOT NULL CONSTRAINT DF__event_his__threa__72C60C4A DEFAULT ('main'),
    local_step int NOT NULL CONSTRAINT DF__event_his__local__73BA3083 DEFAULT ((0)),
    global_seq bigint NOT NULL CONSTRAINT DF__event_his__globa__74AE54BC DEFAULT ((0)),
    intent_at datetimeoffset(7),
    payload_encoding smallint
);
GO

-- dbo.idempotency_keys
CREATE TABLE dbo.idempotency_keys (
    key_hash varbinary(32) NOT NULL,
    workflow_id nvarchar(255) NOT NULL,
    error_msg nvarchar(max),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__idempoten__creat__1332DBDC DEFAULT (sysutcdatetime()),
    expires_at datetimeoffset(7) NOT NULL CONSTRAINT DF__idempoten__expir__14270015 DEFAULT (dateadd(day,(7),sysutcdatetime())),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT df_idempotency_keys_tenant_id DEFAULT ('00000000-0000-0000-0000-000000000000'),
    def_name nvarchar(255),
    input_digest nvarchar(64)
);
GO

-- dbo.plugin_defs
CREATE TABLE dbo.plugin_defs (
    name nvarchar(255) NOT NULL,
    version nvarchar(64) NOT NULL,
    wasm_bytes varbinary(max),
    config nvarchar(max) NOT NULL CONSTRAINT DF__plugin_de__confi__5812160E DEFAULT ('{}'),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__plugin_de__creat__59063A47 DEFAULT (sysutcdatetime()),
    deprecated bit NOT NULL CONSTRAINT DF__plugin_de__depre__59FA5E80 DEFAULT ((0))
);
GO

-- dbo.queue_holders
CREATE TABLE dbo.queue_holders (
    tenant_id uniqueidentifier NOT NULL,
    queue_name nvarchar(128) NOT NULL,
    workflow_id nvarchar(255) NOT NULL,
    expires_at datetimeoffset(7) NOT NULL,
    worker_id nvarchar(255)
);
GO

-- dbo.queue_rate_tokens
CREATE TABLE dbo.queue_rate_tokens (
    tenant_id uniqueidentifier NOT NULL,
    queue_name nvarchar(128) NOT NULL,
    workflow_id nvarchar(255) NOT NULL,
    expires_at datetimeoffset(7) NOT NULL
);
GO

-- dbo.queues
CREATE TABLE dbo.queues (
    tenant_id uniqueidentifier NOT NULL,
    name nvarchar(128) NOT NULL,
    concurrency_limit int NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT df_queues_created DEFAULT (sysutcdatetime()),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_queues_updated DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    rate_limit int,
    rate_period_seconds int,
    worker_concurrency int
);
GO

-- dbo.slack_workspace
CREATE TABLE dbo.slack_workspace (
    team_id nvarchar(32) NOT NULL,
    tenant_id uniqueidentifier NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT df_slack_workspace_created DEFAULT (sysutcdatetime())
);
GO

-- dbo.tenant_domains
CREATE TABLE dbo.tenant_domains (
    hostname nvarchar(255) NOT NULL,
    tenant_id uniqueidentifier NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenant_do__creat__7FEAFD3E DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_domains_updated_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.tenant_secrets
CREATE TABLE dbo.tenant_secrets (
    tenant_id uniqueidentifier NOT NULL,
    name nvarchar(128) NOT NULL,
    ciphertext nvarchar(max) NOT NULL,
    key_version int NOT NULL CONSTRAINT df_tenant_secrets_keyver DEFAULT ((1)),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_secrets_updated DEFAULT (sysutcdatetime()),
    disabled_at datetimeoffset(7),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_secrets_created_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.tenant_settings
CREATE TABLE dbo.tenant_settings (
    tenant_id uniqueidentifier NOT NULL,
    wasm_instance_timeout_ms bigint,
    wasm_wall_clock_ceiling_ms bigint,
    host_retry_budget_ms bigint,
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT DF__tenant_se__updat__5BAD9CC8 DEFAULT (sysutcdatetime()),
    max_workflow_duration_ms bigint,
    disabled_at datetimeoffset(7),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT df_tenant_settings_created_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.workflow_defs
CREATE TABLE dbo.workflow_defs (
    name nvarchar(255) NOT NULL,
    version int NOT NULL,
    wasm_bytes varbinary(max) NOT NULL,
    entry_points nvarchar(max) NOT NULL CONSTRAINT DF__workflow___entry__4D94879B DEFAULT ('[]'),
    min_version int NOT NULL CONSTRAINT DF__workflow___min_v__4E88ABD4 DEFAULT ((0)),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__4F7CD00D DEFAULT (sysutcdatetime()),
    dag_spec nvarchar(max),
    max_history_length int NOT NULL CONSTRAINT DF__workflow___max_h__5070F446 DEFAULT ((0)),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__5165187F DEFAULT ('00000000-0000-0000-0000-000000000000'),
    task_queue nvarchar(255) NOT NULL CONSTRAINT DF__workflow___task___52593CB8 DEFAULT ('default'),
    abi_version int NOT NULL CONSTRAINT DF__workflow___abi_v__534D60F1 DEFAULT ((1)),
    plugin_deps nvarchar(max) NOT NULL CONSTRAINT DF__workflow___plugi__5441852A DEFAULT ('{}'),
    disabled_at datetimeoffset(7),
    gc_eligible bit NOT NULL CONSTRAINT DF__workflow___gc_el__5535A963 DEFAULT ((0)),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_workflow_defs_updated_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.workflow_instances
CREATE TABLE dbo.workflow_instances (
    id nvarchar(255) NOT NULL,
    def_name nvarchar(255) NOT NULL,
    def_version int NOT NULL,
    status nvarchar(32) NOT NULL CONSTRAINT DF__workflow___statu__5DCAEF64 DEFAULT ('ready'),
    input nvarchar(max) NOT NULL CONSTRAINT DF__workflow___input__5EBF139D DEFAULT ('{}'),
    assigned_to nvarchar(255),
    heartbeat_at datetimeoffset(7),
    next_wake_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___next___5FB337D6 DEFAULT (sysutcdatetime()),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__60A75C0F DEFAULT (sysutcdatetime()),
    completed_at datetimeoffset(7),
    cancellation_requested bit NOT NULL CONSTRAINT DF__workflow___cance__619B8048 DEFAULT ((0)),
    cancellation_reason nvarchar(max),
    result nvarchar(max),
    error_msg nvarchar(max),
    error_code nvarchar(255),
    error_op nvarchar(255),
    parent_workflow_id nvarchar(255),
    parent_close_policy nvarchar(32) CONSTRAINT DF__workflow___paren__628FA481 DEFAULT ('ABANDON'),
    query_state nvarchar(max) CONSTRAINT DF__workflow___query__6383C8BA DEFAULT ('{}'),
    trace_id nvarchar(255),
    sticky_worker_id nvarchar(255),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__6477ECF3 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    task_queue nvarchar(255) NOT NULL CONSTRAINT DF__workflow___task___656C112C DEFAULT ('default'),
    compaction_state nvarchar(max),
    compacted_at datetimeoffset(7),
    compaction_step int,
    plugin_vers nvarchar(max) NOT NULL CONSTRAINT DF__workflow___plugi__66603565 DEFAULT ('{}'),
    event_count bigint NOT NULL CONSTRAINT DF__workflow___event__6754599E DEFAULT ((0)),
    allowed_signals nvarchar(max),
    generation bigint NOT NULL CONSTRAINT DF__workflow___gener__68487DD7 DEFAULT ((0)),
    priority int NOT NULL CONSTRAINT DF__workflow___prior__693CA210 DEFAULT ((0)),
    pending_terminal_status nvarchar(32),
    defer_phase_deadline datetime2(7),
    continued_from nvarchar(255),
    signal_seq bigint NOT NULL CONSTRAINT DF__workflow___signa__625A9A57 DEFAULT ((0)),
    signal_seq_at_claim bigint NOT NULL CONSTRAINT DF__workflow___signa__634EBE90 DEFAULT ((0)),
    signal_consumed_seq bigint NOT NULL CONSTRAINT DF__workflow___signa__6442E2C9 DEFAULT ((0)),
    signal_consumed_at_claim bigint NOT NULL CONSTRAINT DF__workflow___signa__65370702 DEFAULT ((0)),
    reclaim_count bigint NOT NULL CONSTRAINT DF__workflow___recla__662B2B3B DEFAULT ((0)),
    started_at datetime2(7),
    concurrency_key nvarchar(255),
    concurrency_key_hash varbinary(32),
    run_wasm_instance_timeout_ms bigint,
    run_wasm_wall_clock_ceiling_ms bigint,
    run_host_retry_budget_ms bigint,
    completed_by nvarchar(255),
    run_max_workflow_duration_ms bigint,
    history_swept_at datetimeoffset(7)
);
GO

-- dbo.workflow_memory_samples
CREATE TABLE dbo.workflow_memory_samples (
    id bigint IDENTITY(1,1) NOT NULL,
    def_name nvarchar(255) NOT NULL,
    sample_bytes bigint NOT NULL,
    recorded_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___recor__208CD6FA DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT df_memory_samples_tenant DEFAULT ('00000000-0000-0000-0000-000000000000')
);
GO

-- dbo.workflow_memory_stats
CREATE TABLE dbo.workflow_memory_stats (
    def_name nvarchar(255) NOT NULL,
    mean_bytes float(53) NOT NULL CONSTRAINT DF__workflow___mean___236943A5 DEFAULT ((0)),
    sample_count int NOT NULL CONSTRAINT DF__workflow___sampl__245D67DE DEFAULT ((0)),
    alpha float(53) NOT NULL CONSTRAINT DF__workflow___alpha__25518C17 DEFAULT ((0.3)),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___updat__2645B050 DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT df_memory_stats_tenant DEFAULT ('00000000-0000-0000-0000-000000000000')
);
GO

-- dbo.workflow_promises
CREATE TABLE dbo.workflow_promises (
    workflow_id nvarchar(255) NOT NULL,
    promise_id nvarchar(64) NOT NULL,
    promise_name nvarchar(255) NOT NULL,
    tenant_id nvarchar(255) NOT NULL,
    priority int NOT NULL CONSTRAINT DF__workflow___prior__7F2BE32F DEFAULT ((0)),
    status nvarchar(50) NOT NULL CONSTRAINT DF__workflow___statu__00200768 DEFAULT ('pending'),
    result nvarchar(max),
    error_msg nvarchar(max),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__01142BA1 DEFAULT (sysutcdatetime()),
    resolved_at datetimeoffset(7)
);
GO

-- dbo.workflow_routing
CREATE TABLE dbo.workflow_routing (
    id uniqueidentifier NOT NULL CONSTRAINT DF__workflow_rou__id__2DE6D218 DEFAULT (newid()),
    workflow_name nvarchar(255) NOT NULL,
    target_version int NOT NULL,
    weight float(53) NOT NULL CONSTRAINT DF__workflow___weigh__2EDAF651 DEFAULT ((1.0)),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__2FCF1A8A DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__30C33EC3 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_workflow_routing_updated_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.workflow_schedules
CREATE TABLE dbo.workflow_schedules (
    name nvarchar(255) NOT NULL,
    def_name nvarchar(255) NOT NULL,
    entry_point nvarchar(255) NOT NULL CONSTRAINT DF__workflow___entry__05D8E0BE DEFAULT (''),
    cron_expression nvarchar(255) NOT NULL,
    input nvarchar(max) NOT NULL CONSTRAINT DF__workflow___input__06CD04F7 DEFAULT ('{}'),
    disabled_at datetimeoffset(7),
    next_run_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___next___08B54D69 DEFAULT (sysutcdatetime()),
    last_run_at datetimeoffset(7),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__09A971A2 DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__0A9D95DB DEFAULT ('00000000-0000-0000-0000-000000000000'),
    timezone nvarchar(64) NOT NULL CONSTRAINT df_workflow_schedules_timezone DEFAULT ('UTC'),
    misfire_policy nvarchar(16) NOT NULL CONSTRAINT df_workflow_schedules_misfire_policy DEFAULT ('catch_up'),
    catch_up_limit int NOT NULL CONSTRAINT df_workflow_schedules_catch_up_limit DEFAULT ((60)),
    overlap_policy nvarchar(16) NOT NULL CONSTRAINT df_workflow_schedules_overlap_policy DEFAULT ('allow'),
    last_run_id nvarchar(255),
    idempotency_key nvarchar(255),
    request_digest nvarchar(64),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_workflow_schedules_updated_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.workflow_signals
CREATE TABLE dbo.workflow_signals (
    workflow_id nvarchar(255) NOT NULL,
    signal_name nvarchar(255) NOT NULL,
    payload nvarchar(max) NOT NULL CONSTRAINT DF__workflow___paylo__787EE5A0 DEFAULT ('{}'),
    delivered_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___deliv__797309D9 DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__7A672E12 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    id bigint IDENTITY(1,1) NOT NULL
);
GO

-- dbo.workflow_tags
CREATE TABLE dbo.workflow_tags (
    workflow_name nvarchar(255) NOT NULL,
    version int NOT NULL,
    tag nvarchar(255) NOT NULL,
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__29221CFB DEFAULT (sysutcdatetime()),
    tenant_id uniqueidentifier NOT NULL CONSTRAINT DF__workflow___tenan__2A164134 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    disabled_at datetimeoffset(7),
    updated_at datetimeoffset(7) NOT NULL CONSTRAINT df_workflow_tags_updated_at DEFAULT (sysutcdatetime())
);
GO

-- dbo.workflow_update_requests
CREATE TABLE dbo.workflow_update_requests (
    workflow_id nvarchar(255) NOT NULL,
    update_name nvarchar(255) NOT NULL,
    tenant_id nvarchar(36) NOT NULL CONSTRAINT DF__workflow___tenan__17F790F9 DEFAULT ('00000000-0000-0000-0000-000000000000'),
    priority int NOT NULL CONSTRAINT DF__workflow___prior__18EBB532 DEFAULT ((0)),
    payload nvarchar(max) NOT NULL CONSTRAINT DF__workflow___paylo__19DFD96B DEFAULT ('{}'),
    promise_id nvarchar(max),
    status nvarchar(50) NOT NULL CONSTRAINT DF__workflow___statu__1AD3FDA4 DEFAULT ('pending'),
    result nvarchar(max),
    error_msg nvarchar(max),
    created_at datetimeoffset(7) NOT NULL CONSTRAINT DF__workflow___creat__1BC821DD DEFAULT (sysutcdatetime()),
    completed_at datetimeoffset(7),
    request_id nvarchar(255) NOT NULL
);
GO

ALTER TABLE admin.orgs ADD CONSTRAINT pk_admin_orgs PRIMARY KEY CLUSTERED (org_id);
GO

ALTER TABLE admin.orgs ADD CONSTRAINT uq_admin_orgs_name UNIQUE NONCLUSTERED (name);
GO

ALTER TABLE admin.plugin_tables ADD CONSTRAINT pk_admin_plugin_tables PRIMARY KEY CLUSTERED (plugin_name, table_name);
GO

ALTER TABLE admin.rls_predicate_form ADD CONSTRAINT pk_admin_rls_predicate_form PRIMARY KEY CLUSTERED (only_row);
GO

ALTER TABLE admin.tenant_api_keys ADD CONSTRAINT pk_admin_tenant_api_keys PRIMARY KEY CLUSTERED (key_id);
GO

ALTER TABLE admin.tenant_egress_allow ADD CONSTRAINT pk_tenant_egress_allow PRIMARY KEY CLUSTERED (tenant_id, host);
GO

ALTER TABLE admin.tenant_roles ADD CONSTRAINT pk_admin_tenant_roles PRIMARY KEY CLUSTERED (tenant_id);
GO

ALTER TABLE admin.tenants ADD CONSTRAINT pk_admin_tenants PRIMARY KEY CLUSTERED (tenant_id);
GO

ALTER TABLE admin.tenants ADD CONSTRAINT uq_admin_tenants_name UNIQUE NONCLUSTERED (name);
GO

ALTER TABLE admin.workers ADD CONSTRAINT pk_admin_workers PRIMARY KEY CLUSTERED (worker_id);
GO

ALTER TABLE dbo.concurrency_keys ADD CONSTRAINT pk_concurrency_keys PRIMARY KEY CLUSTERED (key_hash, tenant_id);
GO

ALTER TABLE dbo.deployment_secrets ADD CONSTRAINT pk_deployment_secrets PRIMARY KEY CLUSTERED (name);
GO

ALTER TABLE dbo.event_history ADD CONSTRAINT pk_event_history PRIMARY KEY CLUSTERED (workflow_id, step);
GO

ALTER TABLE dbo.idempotency_keys ADD CONSTRAINT pk_idempotency_keys PRIMARY KEY CLUSTERED (key_hash, tenant_id);
GO

ALTER TABLE dbo.plugin_defs ADD CONSTRAINT pk_plugin_defs PRIMARY KEY CLUSTERED (name, version);
GO

ALTER TABLE dbo.queue_holders ADD CONSTRAINT pk_queue_holders PRIMARY KEY CLUSTERED (tenant_id, queue_name, workflow_id);
GO

ALTER TABLE dbo.queues ADD CONSTRAINT pk_queues PRIMARY KEY CLUSTERED (tenant_id, name);
GO

ALTER TABLE dbo.slack_workspace ADD CONSTRAINT pk_slack_workspace PRIMARY KEY CLUSTERED (team_id);
GO

ALTER TABLE dbo.tenant_domains ADD CONSTRAINT pk_tenant_domains PRIMARY KEY CLUSTERED (hostname);
GO

ALTER TABLE dbo.tenant_secrets ADD CONSTRAINT pk_tenant_secrets PRIMARY KEY CLUSTERED (tenant_id, name);
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT pk_tenant_settings PRIMARY KEY CLUSTERED (tenant_id);
GO

ALTER TABLE dbo.workflow_defs ADD CONSTRAINT pk_workflow_defs PRIMARY KEY CLUSTERED (tenant_id, name, version);
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT pk_workflow_instances PRIMARY KEY CLUSTERED (id);
GO

ALTER TABLE dbo.workflow_memory_samples ADD CONSTRAINT pk_workflow_memory_samples PRIMARY KEY CLUSTERED (id);
GO

ALTER TABLE dbo.workflow_memory_stats ADD CONSTRAINT pk_workflow_memory_stats PRIMARY KEY CLUSTERED (tenant_id, def_name);
GO

ALTER TABLE dbo.workflow_promises ADD CONSTRAINT pk_workflow_promises PRIMARY KEY CLUSTERED (workflow_id, promise_id);
GO

ALTER TABLE dbo.workflow_routing ADD CONSTRAINT pk_workflow_routing PRIMARY KEY CLUSTERED (id);
GO

ALTER TABLE dbo.workflow_schedules ADD CONSTRAINT pk_workflow_schedules PRIMARY KEY CLUSTERED (tenant_id, name);
GO

ALTER TABLE dbo.workflow_signals ADD CONSTRAINT pk_workflow_signals PRIMARY KEY CLUSTERED (id);
GO

ALTER TABLE dbo.workflow_tags ADD CONSTRAINT pk_workflow_tags PRIMARY KEY CLUSTERED (tenant_id, workflow_name, tag);
GO

ALTER TABLE dbo.workflow_update_requests ADD CONSTRAINT pk_workflow_update_requests PRIMARY KEY CLUSTERED (workflow_id, request_id);
GO

ALTER TABLE admin.rls_predicate_form ADD CONSTRAINT ck_admin_rls_predicate_form_single CHECK ([only_row]=(1));
GO

ALTER TABLE admin.rls_predicate_form ADD CONSTRAINT ck_admin_rls_predicate_form_value CHECK ([form]=N'admin' OR [form]=N'plain');
GO

ALTER TABLE dbo.deployment_secrets ADD CONSTRAINT ck_deployment_secrets_ciphertext_nonempty CHECK (len([ciphertext])>(0));
GO

ALTER TABLE dbo.event_history ADD CONSTRAINT ck_event_history_payload CHECK ([payload] IS NULL OR isjson([payload])=(1));
GO

ALTER TABLE dbo.plugin_defs ADD CONSTRAINT ck_plugin_defs_config CHECK (isjson([config])=(1));
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_concurrency_limit_positive CHECK ([concurrency_limit]>=(1));
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_rate_limit_paired CHECK ([rate_limit] IS NULL AND [rate_period_seconds] IS NULL OR [rate_limit] IS NOT NULL AND [rate_period_seconds] IS NOT NULL);
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_rate_limit_positive CHECK ([rate_limit] IS NULL OR [rate_limit]>=(1));
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_rate_period_positive CHECK ([rate_period_seconds] IS NULL OR [rate_period_seconds]>=(1));
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_worker_concurrency_le_concurrency CHECK ([worker_concurrency] IS NULL OR [worker_concurrency]<=[concurrency_limit]);
GO

ALTER TABLE dbo.queues ADD CONSTRAINT ck_queues_worker_concurrency_positive CHECK ([worker_concurrency] IS NULL OR [worker_concurrency]>=(1));
GO

ALTER TABLE dbo.slack_workspace ADD CONSTRAINT ck_slack_workspace_team_id_shape CHECK (([team_id]) collate Latin1_General_BIN2 like N'[TE][A-Z0-9]%' AND NOT ([team_id]) collate Latin1_General_BIN2 like N'%[^A-Z0-9]%');
GO

ALTER TABLE dbo.tenant_domains ADD CONSTRAINT ck_tenant_domains_hostname_lowercase CHECK ([hostname]=lower([hostname]));
GO

ALTER TABLE dbo.tenant_domains ADD CONSTRAINT ck_tenant_domains_hostname_no_port CHECK (charindex(':',[hostname])=(0));
GO

ALTER TABLE dbo.tenant_domains ADD CONSTRAINT ck_tenant_domains_hostname_nonempty CHECK (len([hostname])>(0));
GO

ALTER TABLE dbo.tenant_secrets ADD CONSTRAINT ck_tenant_secrets_ciphertext_nonempty CHECK (len([ciphertext])>(0));
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT ck_tenant_settings_instance_timeout_positive CHECK ([wasm_instance_timeout_ms] IS NULL OR [wasm_instance_timeout_ms]>(0));
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT ck_tenant_settings_retry_budget_positive CHECK ([host_retry_budget_ms] IS NULL OR [host_retry_budget_ms]>(0));
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT ck_tenant_settings_wall_clock_positive CHECK ([wasm_wall_clock_ceiling_ms] IS NULL OR [wasm_wall_clock_ceiling_ms]>(0));
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT ck_ts_max_workflow_duration_positive CHECK ([max_workflow_duration_ms] IS NULL OR [max_workflow_duration_ms]>(0));
GO

ALTER TABLE dbo.workflow_defs ADD CONSTRAINT ck_workflow_defs_dag_spec CHECK ([dag_spec] IS NULL OR isjson([dag_spec])=(1));
GO

ALTER TABLE dbo.workflow_defs ADD CONSTRAINT ck_workflow_defs_plugin_deps CHECK (isjson([plugin_deps])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_wi_run_instance_timeout_positive CHECK ([run_wasm_instance_timeout_ms] IS NULL OR [run_wasm_instance_timeout_ms]>(0));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_wi_run_max_workflow_duration_positive CHECK ([run_max_workflow_duration_ms] IS NULL OR [run_max_workflow_duration_ms]>(0));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_wi_run_retry_budget_positive CHECK ([run_host_retry_budget_ms] IS NULL OR [run_host_retry_budget_ms]>(0));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_wi_run_wall_clock_positive CHECK ([run_wasm_wall_clock_ceiling_ms] IS NULL OR [run_wasm_wall_clock_ceiling_ms]>(0));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_allowed_signals CHECK ([allowed_signals] IS NULL OR isjson([allowed_signals])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_compaction_state CHECK ([compaction_state] IS NULL OR isjson([compaction_state])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_input CHECK (isjson([input])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_plugin_vers CHECK (isjson([plugin_vers])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_query_state CHECK ([query_state] IS NULL OR isjson([query_state])=(1));
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT ck_workflow_instances_result CHECK ([result] IS NULL OR isjson([result])=(1));
GO

ALTER TABLE dbo.workflow_promises ADD CONSTRAINT ck_workflow_promises_result CHECK ([result] IS NULL OR isjson([result])=(1));
GO

ALTER TABLE dbo.workflow_routing ADD CONSTRAINT ck_workflow_routing_weight CHECK ([weight]>=(0) AND [weight]<=(1));
GO

ALTER TABLE dbo.workflow_schedules ADD CONSTRAINT ck_schedules_catch_up_limit CHECK ([catch_up_limit]>=(0));
GO

ALTER TABLE dbo.workflow_schedules ADD CONSTRAINT ck_schedules_misfire_policy CHECK ([misfire_policy]='skip' OR [misfire_policy]='catch_up');
GO

ALTER TABLE dbo.workflow_schedules ADD CONSTRAINT ck_schedules_overlap_policy CHECK ([overlap_policy]='skip' OR [overlap_policy]='allow');
GO

ALTER TABLE dbo.workflow_schedules ADD CONSTRAINT ck_workflow_schedules_input CHECK (isjson([input])=(1));
GO

ALTER TABLE dbo.workflow_signals ADD CONSTRAINT ck_workflow_signals_payload CHECK (isjson([payload],VALUE)=(1));
GO

ALTER TABLE dbo.workflow_update_requests ADD CONSTRAINT ck_workflow_update_requests_payload CHECK (isjson([payload],VALUE)=(1));
GO

ALTER TABLE dbo.workflow_update_requests ADD CONSTRAINT ck_workflow_update_requests_result CHECK ([result] IS NULL OR isjson([result])=(1));
GO

ALTER TABLE admin.tenant_api_keys ADD CONSTRAINT fk_admin_api_keys_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id);
GO

ALTER TABLE admin.tenant_egress_allow ADD CONSTRAINT fk_tenant_egress_allow_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE admin.tenant_roles ADD CONSTRAINT fk_admin_roles_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id);
GO

ALTER TABLE admin.tenants ADD CONSTRAINT tenants_org_id_fk FOREIGN KEY (org_id) REFERENCES admin.orgs (org_id);
GO

ALTER TABLE dbo.concurrency_keys ADD CONSTRAINT fk_concurrency_keys_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.event_history ADD CONSTRAINT fk_event_history_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.queue_holders ADD CONSTRAINT fk_queue_holders_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.queue_rate_tokens ADD CONSTRAINT fk_queue_rate_tokens_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.queues ADD CONSTRAINT fk_queues_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.slack_workspace ADD CONSTRAINT fk_slack_workspace_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.tenant_domains ADD CONSTRAINT fk_tenant_domains_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.tenant_secrets ADD CONSTRAINT fk_tenant_secrets_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.tenant_settings ADD CONSTRAINT fk_tenant_settings_tenant FOREIGN KEY (tenant_id) REFERENCES admin.tenants (tenant_id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.workflow_instances ADD CONSTRAINT fk_instances_def FOREIGN KEY (tenant_id, def_name, def_version) REFERENCES dbo.workflow_defs (tenant_id, name, version);
GO

ALTER TABLE dbo.workflow_promises ADD CONSTRAINT fk_promises_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.workflow_routing ADD CONSTRAINT fk_workflow_routing_def FOREIGN KEY (tenant_id, workflow_name, target_version) REFERENCES dbo.workflow_defs (tenant_id, name, version);
GO

ALTER TABLE dbo.workflow_signals ADD CONSTRAINT fk_signals_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

ALTER TABLE dbo.workflow_tags ADD CONSTRAINT fk_workflow_tags_def FOREIGN KEY (tenant_id, workflow_name, version) REFERENCES dbo.workflow_defs (tenant_id, name, version);
GO

ALTER TABLE dbo.workflow_update_requests ADD CONSTRAINT fk_update_requests_workflow FOREIGN KEY (workflow_id) REFERENCES dbo.workflow_instances (id) ON DELETE CASCADE;
GO

CREATE NONCLUSTERED INDEX idx_api_keys_hash ON admin.tenant_api_keys (key_hash) WHERE ([disabled_at] IS NULL);
GO

CREATE NONCLUSTERED INDEX idx_workers_last_heartbeat ON admin.workers (last_heartbeat_at);
GO

CREATE NONCLUSTERED INDEX idx_concurrency_keys_expires ON dbo.concurrency_keys (expires_at);
GO

CREATE NONCLUSTERED INDEX idx_concurrency_keys_workflow ON dbo.concurrency_keys (workflow_id);
GO

CREATE NONCLUSTERED INDEX idx_event_history_pending ON dbo.event_history (workflow_id, step) WHERE ([intent_at] IS NOT NULL AND [checksum] IS NULL);
GO

CREATE NONCLUSTERED INDEX idx_event_history_tenant_wf ON dbo.event_history (tenant_id, workflow_id, step);
GO

CREATE NONCLUSTERED INDEX idx_idempotency_expires ON dbo.idempotency_keys (expires_at);
GO

CREATE NONCLUSTERED INDEX idx_idempotency_workflow_id ON dbo.idempotency_keys (workflow_id);
GO

CREATE NONCLUSTERED INDEX idx_queue_holders_expires ON dbo.queue_holders (expires_at);
GO

CREATE NONCLUSTERED INDEX idx_queue_holders_worker ON dbo.queue_holders (tenant_id, queue_name, worker_id, expires_at);
GO

CREATE NONCLUSTERED INDEX idx_queue_holders_workflow ON dbo.queue_holders (workflow_id);
GO

CREATE NONCLUSTERED INDEX idx_queue_rate_tokens_expires ON dbo.queue_rate_tokens (expires_at);
GO

CREATE NONCLUSTERED INDEX idx_queue_rate_tokens_window ON dbo.queue_rate_tokens (tenant_id, queue_name, expires_at);
GO

CREATE NONCLUSTERED INDEX idx_slack_workspace_tenant ON dbo.slack_workspace (tenant_id);
GO

CREATE NONCLUSTERED INDEX idx_tenant_domains_tenant ON dbo.tenant_domains (tenant_id);
GO

CREATE NONCLUSTERED INDEX idx_defs_active ON dbo.workflow_defs (name, version DESC);
GO

CREATE NONCLUSTERED INDEX idx_defs_tenant_name_version ON dbo.workflow_defs (tenant_id, name, version DESC);
GO

CREATE NONCLUSTERED INDEX idx_instances_claim_order ON dbo.workflow_instances (tenant_id, task_queue, priority, created_at) WHERE ([status] IN ('ready', 'terminating'));
GO

CREATE NONCLUSTERED INDEX idx_instances_claimable ON dbo.workflow_instances (status, next_wake_at) WHERE ([status] IN ('ready', 'terminating'));
GO

CREATE NONCLUSTERED INDEX idx_instances_concurrency_key ON dbo.workflow_instances (tenant_id, concurrency_key_hash) WHERE ([concurrency_key_hash] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX idx_instances_created_at ON dbo.workflow_instances (tenant_id, created_at DESC);
GO

CREATE NONCLUSTERED INDEX idx_instances_heartbeat ON dbo.workflow_instances (assigned_to, heartbeat_at) WHERE ([status]='running');
GO

CREATE NONCLUSTERED INDEX idx_instances_parent_policy ON dbo.workflow_instances (parent_workflow_id, parent_close_policy, status);
GO

CREATE NONCLUSTERED INDEX idx_instances_stale ON dbo.workflow_instances (status, heartbeat_at) WHERE ([status]='running');
GO

CREATE NONCLUSTERED INDEX idx_instances_sticky ON dbo.workflow_instances (sticky_worker_id) WHERE ([sticky_worker_id] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX idx_instances_tenant_claimable ON dbo.workflow_instances (tenant_id, status, next_wake_at) WHERE ([status] IN ('ready', 'terminating'));
GO

CREATE NONCLUSTERED INDEX idx_instances_tenant_queue_claimable ON dbo.workflow_instances (tenant_id, task_queue, status, priority, next_wake_at) WHERE ([status] IN ('ready', 'terminating'));
GO

CREATE NONCLUSTERED INDEX idx_instances_tenant_status_created ON dbo.workflow_instances (tenant_id, status, created_at DESC);
GO

CREATE NONCLUSTERED INDEX idx_instances_terminal_completed ON dbo.workflow_instances (tenant_id, status, completed_at) WHERE ([status] IN ('done', 'failed', 'terminated'));
GO

CREATE NONCLUSTERED INDEX idx_workflow_instances_continued_from ON dbo.workflow_instances (continued_from) WHERE ([continued_from] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX idx_workflow_instances_defer_phase_deadline ON dbo.workflow_instances (defer_phase_deadline) WHERE ([pending_terminal_status] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX idx_mem_samples_def ON dbo.workflow_memory_samples (def_name, recorded_at DESC);
GO

CREATE NONCLUSTERED INDEX idx_memory_samples_tenant_def ON dbo.workflow_memory_samples (tenant_id, def_name, recorded_at DESC);
GO

CREATE UNIQUE NONCLUSTERED INDEX idx_promises_id_unique ON dbo.workflow_promises (tenant_id, promise_id);
GO

CREATE NONCLUSTERED INDEX idx_promises_status ON dbo.workflow_promises (workflow_id, status);
GO

CREATE NONCLUSTERED INDEX idx_schedules_tenant_due ON dbo.workflow_schedules (tenant_id, next_run_at) WHERE ([disabled_at] IS NULL);
GO

CREATE UNIQUE NONCLUSTERED INDEX uq_workflow_schedules_idempotency_key ON dbo.workflow_schedules (tenant_id, idempotency_key) WHERE ([idempotency_key] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX idx_signals_tenant_wf ON dbo.workflow_signals (tenant_id, workflow_id, signal_name);
GO

CREATE NONCLUSTERED INDEX idx_workflow_signals_queue ON dbo.workflow_signals (workflow_id, signal_name);
GO

CREATE NONCLUSTERED INDEX idx_update_requests_pending ON dbo.workflow_update_requests (workflow_id, status);
GO

CREATE NONCLUSTERED INDEX idx_update_requests_pending_name ON dbo.workflow_update_requests (workflow_id, update_name, status);
GO

