// Code generated by cleat-gen. DO NOT EDIT.

package dispatch

import "github.com/cleat-team/cleat/cleat"

type FindDriverRequest struct {
	Address string `json:"address"`
}

type FindDriverResponse struct {
	DriverID   string `json:"driver_id"`
	DriverName string `json:"driver_name"`
	ETAMinutes int    `json:"eta_minutes"`
}

type ReleaseDriverRequest struct {
	DriverID string `json:"driver_id"`
}

type CheckPickupStatusRequest struct {
	DriverID string `json:"driver_id"`
}

type CheckPickupStatusResponse struct {
	Status string `json:"status"`
}

type Client struct {
	h cleat.HostCalls
}

func NewClient(h cleat.HostCalls) *Client {
	return &Client{h: h}
}

func (c *Client) FindDriver(req FindDriverRequest) (*FindDriverResponse, error) {
	var resp FindDriverResponse
	if err := c.h.DurableCallTyped("dispatch", "FindDriver", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *Client) ReleaseDriver(req ReleaseDriverRequest) error {
	return c.h.DurableCallTyped("dispatch", "ReleaseDriver", req, nil)
}

func (c *Client) CheckPickupStatus(req CheckPickupStatusRequest) (*CheckPickupStatusResponse, error) {
	var resp CheckPickupStatusResponse
	if err := c.h.DurableCallTyped("dispatch", "CheckPickupStatus", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
