run:
  go: "1.26"
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocyclo
    - gofmt
issues:
  exclude-files:
    - ".*_test\\.go$"
