package wasm

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"

	"github.com/rcownie/cleat/internal/analyzer"
)

// GenerateExports produces the content of gen_wasm_exports.go.
func GenerateExports(pkgName string, result *analyzer.AnalysisResult) []byte {
	var buf bytes.Buffer

	buf.WriteString("//go:build wasip1\n\n")
	buf.WriteString("// Code generated by cleat build. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"unsafe\"\n")
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/rcownie/cleat/cleat\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(`// writeJSONOut marshals v to JSON and copies it into the output buffer.
func writeJSONOut(outPtr unsafe.Pointer, maxLen uint32, v interface{}) int64 {
	data, err := json.Marshal(v)
	if err != nil {
		return writeErrorOut(outPtr, maxLen, err)
	}
	outLen := uint32(len(data))
	if outLen > maxLen {
		return writeErrorOut(outPtr, maxLen,
			fmt.Errorf("response size %d exceeds buffer capacity %d", outLen, maxLen))
	}
	if outLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(outLen))
		copy(dst, data)
	}
	return int64(outLen) << 32 // errCode = 0
}

// writeErrorOut writes an error message to the output buffer.
func writeErrorOut(outPtr unsafe.Pointer, maxLen uint32, err error) int64 {
	msg := err.Error()
	msgLen := uint32(len(msg))
	if msgLen > maxLen {
		msgLen = maxLen
	}
	if msgLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(msgLen))
		copy(dst, msg)
	}
	return (int64(msgLen) << 32) | 1
}

// writeSuspendOut returns a sentinel indicating the workflow suspended.
func writeSuspendOut() int64 {
	return 1 << 62
}

`)

	qual := types.RelativeTo(result.TargetPkg.Types)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		generateExport(&buf, fd, qual)
	}

	return buf.Bytes()
}

func generateExport(buf *bytes.Buffer, fd *analyzer.FuncDecl, qual types.Qualifier) {
	exportName := ToSnakeCase(fd.Name)
	sig := fd.Type

	params := sig.Params()
	type argField struct {
		GoName  string
		GoType  string
		JSONTag string
	}
	var fields []argField

	startIdx := 0
	if params != nil && params.Len() > 0 {
		if analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			p := params.At(i)
			fields = append(fields, argField{
				GoName:  capitalize(p.Name()),
				GoType:  types.TypeString(p.Type(), qual),
				JSONTag: p.Name(),
			})
		}
	}

	results := sig.Results()
	var hasResultValue, hasErrorReturn bool
	if results != nil {
		for i := 0; i < results.Len(); i++ {
			typeName := types.TypeString(results.At(i).Type(), qual)
			if typeName == "error" {
				hasErrorReturn = true
			} else {
				hasResultValue = true
			}
		}
	}

	fmt.Fprintf(buf, "//go:wasmexport %s\n", exportName)
	fmt.Fprintf(buf, "func %s(argsPtr unsafe.Pointer, argsLen uint32, outPtr unsafe.Pointer, maxOutLen uint32) int64 {\n", exportName)

	if len(fields) > 0 {
		buf.WriteString("\targsJSON := readString(argsPtr, argsLen)\n")
		buf.WriteString("\tvar args struct {\n")
		for _, f := range fields {
			fmt.Fprintf(buf, "\t\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONTag)
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tif err := json.Unmarshal([]byte(argsJSON), &args); err != nil {\n")
		buf.WriteString("\t\terrJSON, _ := json.Marshal(err.Error())\n")
		buf.WriteString("\t\terrPtr, errLen := stringPtr(string(errJSON))\n")
		buf.WriteString("\t\tcleatCompleteImport(1, errPtr, errLen)\n")
		buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, err)\n")
		buf.WriteString("\t}\n")
	} else {
		buf.WriteString("\t_ = argsPtr\n")
		buf.WriteString("\t_ = argsLen\n")
	}

	buf.WriteString("\n\th := makeHostCalls()\n\n")

	// Declare captured result/suspend variables.
	buf.WriteString("\tvar __susResultJSON []byte\n")
	buf.WriteString("\tvar __susResultErr error\n")
	buf.WriteString("\t__susSuspended := false\n\n")

	// Wrap entry point call in recover for suspend handling.
	buf.WriteString("\tfunc() {\n")
	buf.WriteString("\t\tdefer func() {\n")
	buf.WriteString("\t\t\tif r := recover(); r != nil {\n")
	buf.WriteString("\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {\n")
	buf.WriteString("\t\t\t\t\t__susSuspended = true\n")
	buf.WriteString("\t\t\t\t\treturn\n")
	buf.WriteString("\t\t\t\t}\n")
	buf.WriteString("\t\t\t\tpanic(r)\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}()\n\n")

	// Build call arguments.
	var callArgs []string
	callArgs = append(callArgs, "h")
	for _, f := range fields {
		callArgs = append(callArgs, "args."+f.GoName)
	}

	if hasResultValue && hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__r, __e := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\tif __e != nil {\n")
		buf.WriteString("\t\t\t__susResultErr = __e\n")
		buf.WriteString("\t\t\treturn\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\t__susResultJSON, __susResultErr = json.Marshal(__r)\n")
	} else if hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__susResultErr = %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	} else if hasResultValue {
		fmt.Fprintf(buf, "\t\t__r := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\t__susResultJSON, __susResultErr = json.Marshal(__r)\n")
	} else {
		fmt.Fprintf(buf, "\t\t%s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	}

	buf.WriteString("\t}()\n\n")

	buf.WriteString("\tif __susSuspended {\n")
	buf.WriteString("\t\treturn writeSuspendOut()\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif __susResultErr != nil {\n")
		buf.WriteString("\t\terrJSON, _ := json.Marshal(__susResultErr.Error())\n")
		buf.WriteString("\t\terrPtr, errLen := stringPtr(string(errJSON))\n")
		buf.WriteString("\t\tcleatCompleteImport(1, errPtr, errLen)\n")
	buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, __susResultErr)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tresultJSON, _ := json.Marshal(string(__susResultJSON))\n")
	buf.WriteString("\tresultPtr, resultLen := stringPtr(string(resultJSON))\n")
	buf.WriteString("\tcleatCompleteImport(0, resultPtr, resultLen)\n")
	buf.WriteString("\treturn writeJSONOut(outPtr, maxOutLen, json.RawMessage(__susResultJSON))\n")

	buf.WriteString("}\n\n")
}

func ToSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(r + 32))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
