package wasm

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"

	"github.com/rcownie/durable/internal/analyzer"
)

// GenerateExports produces the content of gen_wasm_exports.go.
// Each entry point gets a //go:wasmexport wrapper with signature:
//
//	func <snake_name>(argsPtr unsafe.Pointer, argsLen uint32,
//	    outPtr unsafe.Pointer, maxOutLen uint32) int64
//
// The int64 return packs (actualOutLen << 32) | errCode.
func GenerateExports(pkgName string, result *analyzer.AnalysisResult) []byte {
	var buf bytes.Buffer

	buf.WriteString("//go:build wasip1\n\n")
	buf.WriteString("// Code generated by durable build. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	buf.WriteString(`import (
		"encoding/json"
		"unsafe"
	)

// writeJSONOut marshals v to JSON and copies it into the output buffer.
// Returns int64 = (actualLen << 32) | errCode (0 = success).
func writeJSONOut(outPtr unsafe.Pointer, maxLen uint32, v interface{}) int64 {
	data, err := json.Marshal(v)
	if err != nil {
		return writeErrorOut(outPtr, maxLen, err)
	}
	outLen := uint32(len(data))
	if outLen > maxLen {
		outLen = maxLen
	}
	if outLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(outLen))
		copy(dst, data)
	}
	return int64(outLen) << 32 // errCode = 0
}

// writeErrorOut writes an error message to the output buffer.
// Returns int64 = (msgLen << 32) | 1 (non-zero errCode).
func writeErrorOut(outPtr unsafe.Pointer, maxLen uint32, err error) int64 {
	msg := err.Error()
	msgLen := uint32(len(msg))
	if msgLen > maxLen {
		msgLen = maxLen
	}
	if msgLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(msgLen))
		copy(dst, msg)
	}
	return (int64(msgLen) << 32) | 1
}

`)

	qual := types.RelativeTo(result.TargetPkg.Types)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		generateExport(&buf, fd, qual)
	}

	return buf.Bytes()
}

// generateExport writes a single //go:wasmexport function.
func generateExport(buf *bytes.Buffer, fd *analyzer.FuncDecl, qual types.Qualifier) {
	exportName := ToSnakeCase(fd.Name)
	sig := fd.Type

	// Collect parameters after durable.HostCalls.
	params := sig.Params()
	type argField struct {
		GoName  string
		GoType  string
		JSONTag string
	}
	var fields []argField

	startIdx := 0
	if params != nil && params.Len() > 0 {
		if analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			p := params.At(i)
			fields = append(fields, argField{
				GoName:  capitalize(p.Name()),
				GoType:  types.TypeString(p.Type(), qual),
				JSONTag: p.Name(),
			})
		}
	}

	// Determine result handling.
	results := sig.Results()
	var hasResultValue, hasErrorReturn bool
	if results != nil {
		for i := 0; i < results.Len(); i++ {
			typeName := types.TypeString(results.At(i).Type(), qual)
			if typeName == "error" {
				hasErrorReturn = true
			} else {
				hasResultValue = true
			}
		}
	}

	// Export signature: (argsPtr, argsLen, outPtr, maxOutLen) int64
	fmt.Fprintf(buf, "//go:wasmexport %s\n", exportName)
	fmt.Fprintf(buf, "func %s(argsPtr unsafe.Pointer, argsLen uint32, outPtr unsafe.Pointer, maxOutLen uint32) int64 {\n", exportName)

	// Read and unmarshal args.
	if len(fields) > 0 {
		buf.WriteString("\targsJSON := readString(argsPtr, argsLen)\n")
		buf.WriteString("\tvar args struct {\n")
		for _, f := range fields {
			fmt.Fprintf(buf, "\t\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, f.JSONTag)
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tif err := json.Unmarshal([]byte(argsJSON), &args); err != nil {\n")
		buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, err)\n")
		buf.WriteString("\t}\n")
	} else {
		buf.WriteString("\t_ = argsPtr\n")
		buf.WriteString("\t_ = argsLen\n")
	}

	buf.WriteString("\n\th := makeHostCalls()\n")

	// Build call arguments.
	var callArgs []string
	callArgs = append(callArgs, "h")
	for _, f := range fields {
		callArgs = append(callArgs, "args."+f.GoName)
	}

	if hasResultValue && hasErrorReturn {
		fmt.Fprintf(buf, "\tresult, err := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn writeJSONOut(outPtr, maxOutLen, result)\n")
	} else if hasErrorReturn {
		fmt.Fprintf(buf, "\tif err := %s(%s); err != nil {\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn 0\n")
	} else if hasResultValue {
		fmt.Fprintf(buf, "\tresult := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\treturn writeJSONOut(outPtr, maxOutLen, result)\n")
	} else {
		fmt.Fprintf(buf, "\t%s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\treturn 0\n")
	}

	buf.WriteString("}\n\n")
}

// ToSnakeCase converts a CamelCase string to snake_case.
func ToSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(r + 32))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// capitalize returns the string with the first character uppercased.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
