-- cleat MySQL consolidated schema (001)
-- GENERATED by scripts/gen-mysql-baseline.py from a mysqldump of a
-- database built from the numbered chain. Do not hand-edit: the next
-- regeneration silently reverts it. Add a new numbered migration.
--
-- Tables carry their indexes inline, which is how a dump resolves 39
-- CREATE INDEX and 111 ALTER TABLE statements in the chain.
--
-- CREATE TABLE IF NOT EXISTS guards idempotency, matching the chain's
-- shape. A re-run is a no-op.
--
-- FOREIGN_KEY_CHECKS is off for the body and restored after it: a dump
-- orders tables alphabetically, the chain orders them by dependency,
-- and this makes the baseline correct in either order.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `concurrency_keys` (
  `key_hash` varbinary(32) NOT NULL,
  `key_text` text NOT NULL,
  `workflow_id` varchar(255) NOT NULL,
  `acquired_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `expires_at` timestamp(6) NOT NULL,
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  PRIMARY KEY (`key_hash`,`tenant_id`),
  KEY `idx_concurrency_keys_workflow` (`workflow_id`),
  KEY `idx_concurrency_keys_expires` (`expires_at`),
  CONSTRAINT `concurrency_keys_ibfk_1` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `deployment_secrets` (
  `name` varchar(128) NOT NULL,
  `ciphertext` text NOT NULL,
  `key_version` int NOT NULL DEFAULT '1',
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`name`),
  CONSTRAINT `ck_deployment_secrets_ciphertext_nonempty` CHECK ((char_length(`ciphertext`) > 0)),
  CONSTRAINT `ck_deployment_secrets_name_charset` CHECK (regexp_like(`name`,_utf8mb4'^[A-Za-z0-9_.-]{1,128}$'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `event_history` (
  `workflow_id` varchar(255) NOT NULL,
  `step` int NOT NULL,
  `service` varchar(255) DEFAULT NULL,
  `operation` varchar(255) DEFAULT NULL,
  `request` longtext,
  `response` longtext,
  `error` text,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `event_type` varchar(255) NOT NULL DEFAULT 'call',
  `duration_ms` bigint DEFAULT NULL,
  `signal_names` text,
  `timeout_ms` bigint DEFAULT NULL,
  `signal_name` varchar(255) DEFAULT NULL,
  `signal_payload` longtext,
  `defer_description` text,
  `defer_id` varchar(255) DEFAULT NULL,
  `child_name` varchar(255) DEFAULT NULL,
  `child_input` longtext,
  `run_id` varchar(255) DEFAULT NULL,
  `new_input` longtext,
  `plugin_name` varchar(255) DEFAULT NULL,
  `plugin_func` varchar(255) DEFAULT NULL,
  `plugin_input` longtext,
  `plugin_output` longtext,
  `plugin_error` text,
  `promise_name` varchar(255) DEFAULT NULL,
  `promise_id` varchar(255) DEFAULT NULL,
  `promise_result` text,
  `promise_error` text,
  `tenant_id` char(36) DEFAULT NULL,
  `payload` longtext,
  `checksum` text,
  `thread_id` varchar(255) NOT NULL DEFAULT 'main',
  `local_step` int NOT NULL DEFAULT '0',
  `global_seq` bigint NOT NULL DEFAULT '0',
  `intent_at` timestamp(6) NULL DEFAULT NULL,
  `payload_encoding` tinyint DEFAULT NULL COMMENT 'NULL = unknown (pre-cleat#1319 row), 1 = base64, 0 = plaintext',
  PRIMARY KEY (`workflow_id`,`step`),
  KEY `idx_event_history_tenant_wf` (`tenant_id`,`workflow_id`,`step`),
  KEY `idx_event_history_pending` (`intent_at`,`workflow_id`,`step`),
  CONSTRAINT `event_history_ibfk_1` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_event_history_payload` CHECK (((`payload` is null) or json_valid(`payload`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `idempotency_keys` (
  `key_hash` varbinary(32) NOT NULL,
  `workflow_id` varchar(255) NOT NULL,
  `error_msg` text,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `expires_at` timestamp(6) NOT NULL DEFAULT ((now(6) + interval 7 day)),
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `def_name` varchar(255) DEFAULT NULL,
  `input_digest` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`key_hash`,`tenant_id`),
  KEY `idx_idempotency_workflow_id` (`workflow_id`),
  KEY `idx_idempotency_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `orgs` (
  `org_id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`org_id`),
  UNIQUE KEY `uq_orgs_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `plugin_defs` (
  `name` varchar(255) NOT NULL,
  `version` varchar(255) NOT NULL,
  `wasm_bytes` longblob,
  `config` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deprecated` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `plugin_tables` (
  `plugin_name` varchar(255) NOT NULL,
  `table_name` varchar(255) NOT NULL,
  PRIMARY KEY (`plugin_name`,`table_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `queue_holders` (
  `tenant_id` char(36) NOT NULL,
  `queue_name` varchar(128) NOT NULL,
  `workflow_id` varchar(255) NOT NULL,
  `expires_at` timestamp(6) NOT NULL,
  `worker_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`tenant_id`,`queue_name`,`workflow_id`),
  KEY `idx_queue_holders_workflow` (`workflow_id`),
  KEY `idx_queue_holders_expires` (`expires_at`),
  KEY `idx_queue_holders_worker` (`tenant_id`,`queue_name`,`worker_id`,`expires_at`),
  CONSTRAINT `fk_queue_holders_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `queue_rate_tokens` (
  `tenant_id` char(36) NOT NULL,
  `queue_name` varchar(128) NOT NULL,
  `workflow_id` varchar(255) NOT NULL,
  `expires_at` timestamp(6) NOT NULL,
  KEY `idx_queue_rate_tokens_window` (`tenant_id`,`queue_name`,`expires_at`),
  KEY `idx_queue_rate_tokens_expires` (`expires_at`),
  CONSTRAINT `fk_queue_rate_tokens_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `queues` (
  `tenant_id` char(36) NOT NULL,
  `name` varchar(128) NOT NULL,
  `concurrency_limit` int NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `rate_limit` int DEFAULT NULL,
  `rate_period_seconds` int DEFAULT NULL,
  `worker_concurrency` int DEFAULT NULL,
  PRIMARY KEY (`tenant_id`,`name`),
  CONSTRAINT `fk_queues_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_queues_concurrency_limit_positive` CHECK ((`concurrency_limit` >= 1)),
  CONSTRAINT `ck_queues_name_charset` CHECK (regexp_like(`name`,_utf8mb4'^[A-Za-z0-9_.-]{1,128}$')),
  CONSTRAINT `ck_queues_rate_limit_paired` CHECK (((`rate_limit` is null) = (`rate_period_seconds` is null))),
  CONSTRAINT `ck_queues_rate_limit_positive` CHECK (((`rate_limit` is null) or (`rate_limit` >= 1))),
  CONSTRAINT `ck_queues_rate_period_positive` CHECK (((`rate_period_seconds` is null) or (`rate_period_seconds` >= 1))),
  CONSTRAINT `ck_queues_worker_concurrency_le_concurrency` CHECK (((`worker_concurrency` is null) or (`worker_concurrency` <= `concurrency_limit`))),
  CONSTRAINT `ck_queues_worker_concurrency_positive` CHECK (((`worker_concurrency` is null) or (`worker_concurrency` >= 1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `schema_migrations` (
  `version` varchar(255) NOT NULL,
  `applied_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `slack_workspace` (
  `team_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`team_id`),
  KEY `idx_slack_workspace_tenant` (`tenant_id`),
  CONSTRAINT `fk_slack_workspace_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_slack_workspace_team_id_shape` CHECK (regexp_like(`team_id`,_utf8mb4'^[TE][A-Z0-9]+$'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_api_keys` (
  `key_id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `key_hash` varbinary(32) NOT NULL,
  `description` varchar(1024) NOT NULL DEFAULT '',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `expires_at` timestamp(6) NULL DEFAULT NULL,
  `oauth_identity` varchar(512) DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`key_id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `idx_api_keys_hash` (`key_hash`),
  CONSTRAINT `tenant_api_keys_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_domains` (
  `hostname` varchar(255) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`hostname`),
  KEY `idx_tenant_domains_tenant` (`tenant_id`),
  CONSTRAINT `fk_tenant_domains_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_tenant_domains_hostname_lowercase` CHECK ((`hostname` = lower(`hostname`))),
  CONSTRAINT `ck_tenant_domains_hostname_no_port` CHECK ((locate(_utf8mb4':',`hostname`) = 0)),
  CONSTRAINT `ck_tenant_domains_hostname_nonempty` CHECK ((char_length(`hostname`) > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_egress_allow` (
  `tenant_id` char(36) NOT NULL,
  `host` varchar(255) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`,`host`),
  CONSTRAINT `tenant_egress_allow_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_roles` (
  `tenant_id` char(36) NOT NULL,
  `role_name` varchar(255) NOT NULL,
  `password` text NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`),
  UNIQUE KEY `uq_tenant_roles_role_name` (`role_name`),
  CONSTRAINT `tenant_roles_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_secrets` (
  `tenant_id` char(36) NOT NULL,
  `name` varchar(128) NOT NULL,
  `ciphertext` text NOT NULL,
  `key_version` int NOT NULL DEFAULT '1',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`,`name`),
  CONSTRAINT `fk_tenant_secrets_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_tenant_secrets_ciphertext_nonempty` CHECK ((char_length(`ciphertext`) > 0)),
  CONSTRAINT `ck_tenant_secrets_name_charset` CHECK (regexp_like(`name`,_utf8mb4'^[A-Za-z0-9_.-]{1,128}$'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenant_settings` (
  `tenant_id` char(36) NOT NULL,
  `wasm_instance_timeout_ms` bigint DEFAULT NULL,
  `wasm_wall_clock_ceiling_ms` bigint DEFAULT NULL,
  `host_retry_budget_ms` bigint DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `max_workflow_duration_ms` bigint DEFAULT NULL,
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`),
  CONSTRAINT `fk_tenant_settings_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_tenant_settings_instance_timeout_positive` CHECK (((`wasm_instance_timeout_ms` is null) or (`wasm_instance_timeout_ms` > 0))),
  CONSTRAINT `ck_tenant_settings_retry_budget_positive` CHECK (((`host_retry_budget_ms` is null) or (`host_retry_budget_ms` > 0))),
  CONSTRAINT `ck_tenant_settings_wall_clock_positive` CHECK (((`wasm_wall_clock_ceiling_ms` is null) or (`wasm_wall_clock_ceiling_ms` > 0))),
  CONSTRAINT `ck_ts_max_workflow_duration_positive` CHECK (((`max_workflow_duration_ms` is null) or (`max_workflow_duration_ms` > 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tenants` (
  `tenant_id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `display_name` varchar(255) NOT NULL DEFAULT '',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `suspended` tinyint(1) NOT NULL DEFAULT '0',
  `singleton` tinyint NOT NULL DEFAULT '1',
  `org_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  PRIMARY KEY (`tenant_id`),
  UNIQUE KEY `uq_tenants_name` (`name`),
  UNIQUE KEY `uq_tenants_mysql_is_single_tenant_only_see_tiers_yaml_d1` (`singleton`),
  KEY `tenants_org_id_fk` (`org_id`),
  CONSTRAINT `tenants_org_id_fk` FOREIGN KEY (`org_id`) REFERENCES `orgs` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workers` (
  `worker_id` varchar(64) NOT NULL,
  `hostname` varchar(255) NOT NULL DEFAULT '',
  `pid` int NOT NULL DEFAULT '0',
  `concurrency` int NOT NULL DEFAULT '0',
  `connection_budget` int NOT NULL DEFAULT '0',
  `started_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_heartbeat_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `secret_key_versions` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`worker_id`),
  KEY `idx_workers_last_heartbeat` (`last_heartbeat_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_defs` (
  `name` varchar(255) NOT NULL,
  `version` int NOT NULL,
  `wasm_bytes` longblob NOT NULL,
  `entry_points` json NOT NULL DEFAULT (_utf8mb4'[]'),
  `min_version` int NOT NULL DEFAULT '0',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `max_history_length` int NOT NULL DEFAULT '0',
  `dag_spec` json DEFAULT NULL,
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `task_queue` varchar(255) NOT NULL DEFAULT 'default',
  `abi_version` int NOT NULL DEFAULT '1',
  `plugin_deps` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `gc_eligible` tinyint(1) NOT NULL DEFAULT '0',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`,`name`,`version`),
  KEY `idx_defs_active` (`name`,`version`),
  KEY `idx_defs_tenant_name_version` (`tenant_id`,`name`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_instances` (
  `id` varchar(255) NOT NULL,
  `def_name` varchar(255) NOT NULL,
  `def_version` int NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'ready',
  `input` longtext NOT NULL DEFAULT (_utf8mb4'{}'),
  `assigned_to` varchar(255) DEFAULT NULL,
  `heartbeat_at` timestamp(6) NULL DEFAULT NULL,
  `next_wake_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_at` timestamp(6) NULL DEFAULT NULL,
  `cancellation_requested` tinyint(1) NOT NULL DEFAULT '0',
  `cancellation_reason` text,
  `result` longtext,
  `error_msg` text,
  `error_code` varchar(255) DEFAULT NULL,
  `error_op` varchar(255) DEFAULT NULL,
  `parent_workflow_id` varchar(255) DEFAULT NULL,
  `parent_close_policy` varchar(50) DEFAULT 'ABANDON',
  `query_state` json DEFAULT (_utf8mb4'{}'),
  `trace_id` varchar(255) DEFAULT NULL,
  `sticky_worker_id` varchar(255) DEFAULT NULL,
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `task_queue` varchar(255) NOT NULL DEFAULT 'default',
  `compaction_state` json DEFAULT NULL,
  `compacted_at` timestamp(6) NULL DEFAULT NULL,
  `compaction_step` int DEFAULT NULL,
  `plugin_vers` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `event_count` bigint NOT NULL DEFAULT '0',
  `priority` int NOT NULL DEFAULT '0',
  `generation` bigint NOT NULL DEFAULT '0',
  `allowed_signals` json DEFAULT NULL,
  `pending_terminal_status` varchar(32) DEFAULT NULL,
  `defer_phase_deadline` timestamp(6) NULL DEFAULT NULL,
  `continued_from` varchar(255) DEFAULT NULL,
  `signal_seq` bigint NOT NULL DEFAULT '0',
  `signal_seq_at_claim` bigint NOT NULL DEFAULT '0',
  `signal_consumed_seq` bigint NOT NULL DEFAULT '0',
  `signal_consumed_at_claim` bigint NOT NULL DEFAULT '0',
  `reclaim_count` bigint NOT NULL DEFAULT '0',
  `started_at` datetime(6) DEFAULT NULL,
  `concurrency_key` varchar(255) DEFAULT NULL,
  `concurrency_key_hash` varbinary(32) DEFAULT NULL,
  `run_wasm_instance_timeout_ms` bigint DEFAULT NULL,
  `run_wasm_wall_clock_ceiling_ms` bigint DEFAULT NULL,
  `run_host_retry_budget_ms` bigint DEFAULT NULL,
  `completed_by` varchar(255) DEFAULT NULL,
  `run_max_workflow_duration_ms` bigint DEFAULT NULL,
  `history_swept_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `def_name` (`def_name`,`def_version`),
  KEY `idx_instances_ready` (`status`,`next_wake_at`),
  KEY `idx_instances_heartbeat` (`assigned_to`,`heartbeat_at`),
  KEY `idx_instances_stale` (`status`,`heartbeat_at`),
  KEY `idx_instances_sticky` (`sticky_worker_id`),
  KEY `idx_instances_tenant_ready` (`tenant_id`,`status`,`next_wake_at`),
  KEY `idx_instances_tenant_queue_ready` (`tenant_id`,`task_queue`,`status`,`priority`,`next_wake_at`),
  KEY `idx_instances_created_at` (`tenant_id`,`created_at`),
  KEY `idx_instances_terminal_completed` (`tenant_id`,`status`,`completed_at`),
  KEY `idx_instances_parent_policy` (`parent_workflow_id`,`parent_close_policy`,`status`),
  KEY `idx_workflow_instances_ready_claim` (`tenant_id`,`task_queue`,`status`,`priority`,`created_at`),
  KEY `idx_instances_tenant_status_created` (`tenant_id`,`status`,`created_at`),
  KEY `fk_instances_def` (`tenant_id`,`def_name`,`def_version`),
  KEY `idx_workflow_instances_defer_phase` (`pending_terminal_status`,`defer_phase_deadline`),
  KEY `idx_workflow_instances_continued_from` (`continued_from`),
  KEY `idx_instances_concurrency_key` (`tenant_id`,`concurrency_key_hash`),
  CONSTRAINT `fk_instances_def` FOREIGN KEY (`tenant_id`, `def_name`, `def_version`) REFERENCES `workflow_defs` (`tenant_id`, `name`, `version`),
  CONSTRAINT `ck_wi_run_instance_timeout_positive` CHECK (((`run_wasm_instance_timeout_ms` is null) or (`run_wasm_instance_timeout_ms` > 0))),
  CONSTRAINT `ck_wi_run_max_workflow_duration_positive` CHECK (((`run_max_workflow_duration_ms` is null) or (`run_max_workflow_duration_ms` > 0))),
  CONSTRAINT `ck_wi_run_retry_budget_positive` CHECK (((`run_host_retry_budget_ms` is null) or (`run_host_retry_budget_ms` > 0))),
  CONSTRAINT `ck_wi_run_wall_clock_positive` CHECK (((`run_wasm_wall_clock_ceiling_ms` is null) or (`run_wasm_wall_clock_ceiling_ms` > 0))),
  CONSTRAINT `ck_workflow_instances_input` CHECK (json_valid(`input`)),
  CONSTRAINT `ck_workflow_instances_result` CHECK (((`result` is null) or json_valid(`result`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_memory_samples` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `def_name` varchar(255) NOT NULL,
  `sample_bytes` bigint NOT NULL,
  `recorded_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  PRIMARY KEY (`id`),
  KEY `idx_mem_samples_def` (`def_name`,`recorded_at`),
  KEY `idx_memory_samples_tenant_def` (`tenant_id`,`def_name`,`recorded_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_memory_stats` (
  `def_name` varchar(255) NOT NULL,
  `mean_bytes` double NOT NULL DEFAULT '0',
  `sample_count` int NOT NULL DEFAULT '0',
  `alpha` double NOT NULL DEFAULT '0.3',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  PRIMARY KEY (`tenant_id`,`def_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_promises` (
  `workflow_id` varchar(255) NOT NULL,
  `promise_id` varchar(255) NOT NULL,
  `promise_name` varchar(255) NOT NULL,
  `tenant_id` varchar(255) NOT NULL,
  `priority` int NOT NULL DEFAULT '0',
  `status` varchar(50) NOT NULL DEFAULT 'pending',
  `result` longtext,
  `error_msg` text,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `resolved_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`workflow_id`,`promise_id`),
  UNIQUE KEY `idx_promises_id_unique` (`tenant_id`,`promise_id`),
  KEY `idx_promises_status` (`workflow_id`,`status`),
  CONSTRAINT `workflow_promises_ibfk_1` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_workflow_promises_result` CHECK (((`result` is null) or json_valid(`result`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_routing` (
  `id` char(36) NOT NULL,
  `workflow_name` varchar(255) NOT NULL,
  `target_version` int NOT NULL,
  `weight` double NOT NULL DEFAULT '1',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) DEFAULT NULL,
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `workflow_name` (`workflow_name`,`target_version`),
  KEY `fk_workflow_routing_def` (`tenant_id`,`workflow_name`,`target_version`),
  CONSTRAINT `fk_workflow_routing_def` FOREIGN KEY (`tenant_id`, `workflow_name`, `target_version`) REFERENCES `workflow_defs` (`tenant_id`, `name`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_schedules` (
  `name` varchar(255) NOT NULL,
  `def_name` varchar(255) NOT NULL,
  `entry_point` varchar(255) NOT NULL DEFAULT '',
  `cron_expression` text NOT NULL,
  `input` longtext NOT NULL DEFAULT (_utf8mb4'{}'),
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `next_run_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_run_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `timezone` varchar(64) NOT NULL DEFAULT 'UTC',
  `misfire_policy` varchar(16) NOT NULL DEFAULT 'catch_up',
  `catch_up_limit` int NOT NULL DEFAULT '60',
  `overlap_policy` varchar(16) NOT NULL DEFAULT 'allow',
  `last_run_id` varchar(255) DEFAULT NULL,
  `idempotency_key` varchar(255) DEFAULT NULL,
  `request_digest` varchar(64) DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`,`name`),
  UNIQUE KEY `uq_workflow_schedules_idempotency_key` (`tenant_id`,`idempotency_key`),
  KEY `idx_schedules_tenant_due` (`tenant_id`,`disabled_at`,`next_run_at`),
  CONSTRAINT `ck_workflow_schedules_input` CHECK (json_valid(`input`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_signals` (
  `workflow_id` varchar(255) NOT NULL,
  `signal_name` varchar(255) NOT NULL,
  `payload` longtext NOT NULL DEFAULT (_utf8mb4'{}'),
  `delivered_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  KEY `idx_signals_tenant_wf` (`tenant_id`,`workflow_id`,`signal_name`),
  KEY `idx_workflow_signals_queue` (`workflow_id`,`signal_name`),
  CONSTRAINT `workflow_signals_ibfk_1` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_workflow_signals_payload` CHECK (json_valid(`payload`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_tags` (
  `workflow_name` varchar(255) NOT NULL,
  `version` int NOT NULL,
  `tag` varchar(255) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `disabled_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tenant_id`,`workflow_name`,`tag`),
  KEY `workflow_name` (`workflow_name`,`version`),
  KEY `fk_workflow_tags_def` (`tenant_id`,`workflow_name`,`version`),
  CONSTRAINT `fk_workflow_tags_def` FOREIGN KEY (`tenant_id`, `workflow_name`, `version`) REFERENCES `workflow_defs` (`tenant_id`, `name`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `workflow_update_requests` (
  `workflow_id` varchar(255) NOT NULL,
  `update_name` varchar(255) NOT NULL,
  `tenant_id` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `priority` int NOT NULL DEFAULT '0',
  `payload` longtext NOT NULL DEFAULT (_utf8mb4'{}'),
  `promise_id` varchar(255) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'pending',
  `result` longtext,
  `error_msg` text,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_at` timestamp(6) NULL DEFAULT NULL,
  `request_id` varchar(255) NOT NULL,
  PRIMARY KEY (`workflow_id`,`request_id`),
  KEY `idx_update_requests_pending` (`workflow_id`,`status`),
  KEY `idx_update_requests_pending_name` (`workflow_id`,`update_name`,`status`),
  CONSTRAINT `workflow_update_requests_ibfk_1` FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_workflow_update_requests_payload` CHECK (json_valid(`payload`)),
  CONSTRAINT `ck_workflow_update_requests_result` CHECK (((`result` is null) or json_valid(`result`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
