buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.teavm:teavm-gradle-plugin:0.10.2")
    }
}

apply(plugin = "java")
apply(plugin = "org.teavm")
apply(plugin = "maven-publish")
apply(plugin = "signing")

group = "com.cleat"
version = "0.1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.teavm:teavm-classlib:0.10.2")
    implementation("org.teavm:teavm-jso-apis:0.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    withJavadocJar()
    withSourcesJar()
}

teavm {
    // TeaVM 0.10.2 uses a flat configuration (no nested "wasm {}" block)
    // and Gradle Property delegates for all values.
    // WorkflowEntry is the static analysis root for TeaVM.
    // It is auto-generated by CleatEntryProcessor and references
    // CleatEntryIndex to prevent tree-shaking of @CleatEntry exports.
    mainClass.set("cleat.WorkflowEntry")
    obfuscated.set(false)   // Debug-friendly; switch to ADVANCED for production (FULL optimization used separately)
    fileName.set("workflow.wasm")
    outputDir.set(layout.buildDirectory.dir("wasm"))
    targetType.set("WASM")
    optimizationLevel.set("FULL")
}

tasks.test {
    useJUnitPlatform()
}

// =========================================================================
// Maven Central publishing configuration
// =========================================================================

// Publish guard: disabled by default to prevent accidental publication
val cleatPublish: Boolean by project.ext { false }

tasks.named("publish") {
    doFirst {
        require(cleatPublish || project.hasProperty("cleatPublish")) {
            "Publishing is disabled by default. Enable with -PcleatPublish=true or define cleatPublish=true in gradle.properties."
        }
    }
}

publishing {
    publications {
        register<MavenPublication>("cleatJava") {
            from(components["java"])
            groupId = project.group.toString()
            artifactId = "cleat-sdk"
            version = project.version.toString()

            pom {
                name = "Cleat Java SDK"
                description = "Java SDK for building cleat durable workflow applications"
                url = "https://github.com/cleat/cleat"

                licenses {
                    license {
                        name = "Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }

                developers {
                    developer {
                        name = "Cleat Contributors"
                        email = "contributors@cleat.dev"
                    }
                }

                scm {
                    connection = "scm:git:git://github.com/cleat/cleat.git"
                    developerConnection = "scm:git:ssh://github.com/cleat/cleat.git"
                    url = "https://github.com/cleat/cleat"
                }
            }
        }
    }

    repositories {
        maven {
            name = "sonatype"
            url = uri("https://oss.sonatype.org/service/local/staging/deploy/maven2/")
            credentials {
                username = findProperty("ossrhUsername") as? String ?: System.getenv("OSSRH_USERNAME") ?: ""
                password = findProperty("ossrhPassword") as? String ?: System.getenv("OSSRH_PASSWORD") ?: ""
            }
        }
    }
}

signing {
    setRequired({
        gradle.taskGraph.hasTask(":publishCleatJavaPublicationToSonatypeRepository")
    })

    val signingKey = (findProperty("signingKey") as? String ?: System.getenv("SIGNING_KEY")) ?: ""
    val signingPassword = (findProperty("signingPassword") as? String ?: System.getenv("SIGNING_PASSWORD")) ?: ""

    if (signingKey.isNotEmpty()) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications["cleatJava"])
    }
}
