package engine_test

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/cleat-team/cleat/plugin"
)

// requiredColumns is the set of columns a writer MUST supply for a table:
// NOT NULL, no default, and not generated by the database.
type requiredColumns map[string]map[string]bool // table -> column -> true

// TestEveryDialectAgreesWhichColumnsAWriterMustSupply is cleat#963.
//
// # What the existing all-dialect test cannot see
//
// TestPluginMigrations_AllDialects runs every plugin's migrations on every
// dialect and then asserts `tableExists`. That passed throughout cleat#958,
// where audit_events.id is CHAR(36) with no default on MySQL and generated on
// the other two, and the plugin's INSERT omitted the column: zero audit events
// had ever been recorded on MySQL. The table was there. It was the write that
// could not succeed.
//
// **"The schema was created" and "the schema is usable" are different claims**,
// and an existence check only answers the first. It cannot see a missing
// default, a NOT NULL with no source, or a constraint nothing satisfies.
//
// # What this asserts instead, and why it is a mechanism rather than a sweep
//
// Not "does plugin X's INSERT work" -- that needs a write path per plugin and
// only covers statements someone has already written. The property underneath
// is simpler and catches the ones nobody has written yet:
//
//	the three dialects must AGREE about which columns a writer must supply.
//
// If they agree, a statement that works on one works on all, which is exactly
// the invariant #958 broke. If they disagree, either the schema is wrong or the
// code compensates -- and a compensated case has to be written down rather than
// left to be rediscovered.
//
// # The database is the oracle, not a regex over DDL
//
// A sibling session's loose scan of plugins/*/migrations.go reported 13 plugins
// with some per-dialect asymmetry, and the first one checked precisely turned
// out already compensated. That number was never a finding. This asks each real
// database what it actually did with the DDL, which is the only thing that
// knows: `information_schema` sees generated columns, identity columns and
// defaults that a pattern over SQL text cannot.
func TestEveryDialectAgreesWhichColumnsAWriterMustSupply(t *testing.T) {
	plugins, err := plugin.Discover()
	if err != nil {
		t.Fatalf("plugin.Discover: %v", err)
	}
	var migratable []*plugin.LoadedPlugin
	tablesOf := map[string][]string{}
	for _, lp := range plugins {
		if !lp.Healthy {
			continue
		}
		pm, ok := lp.Plugin.(plugin.HasMigrations)
		if !ok {
			continue
		}
		if lp.Plugin.Info().Name == "pgvector" {
			continue // PostgreSQL-only by design; excluded by the sibling test too
		}
		migratable = append(migratable, lp)
		tablesOf[lp.Plugin.Info().Name] = extractTableNames(pm.Migrations())
	}
	if len(migratable) == 0 {
		t.Fatal("no migratable plugins discovered; this test would compare nothing")
	}

	// Gather per dialect. Every configured dialect must be reachable: a skip
	// here would compare two dialects and call it agreement, which is the
	// failure mode the whole test is about.
	got := map[string]requiredColumns{}
	for _, backend := range pluginTestBackends {
		if !backend.enabled() {
			t.Logf("%s: not configured, not compared", backend.name)
			continue
		}
		// A FRESH schema, not the shared test database.
		//
		// This matters more here than anywhere else in the file. RunMigrations
		// records applied versions and skips them, and MySQL/MSSQL's backend
		// setup hands back the shared database whose plugin tables were created
		// by some earlier run. So without this the guard reads whatever DDL was
		// current when those tables were first made -- and CREATE TABLE IF NOT
		// EXISTS never adds a column, which is CLAUDE.md's "when a schema
		// migration lands, recreate your test databases".
		//
		// Measured while falsifying: removing the MySQL default from
		// audit_events.timestamp did not redden this test, because the mutated
		// DDL never ran. A guard that reports agreement from a stale schema is
		// the same defect as cleat#963 one level up.
		db, teardown := freshPluginSchema(t, backend)
		defer teardown()
		if err := plugin.RunMigrations(context.Background(), db, backend.dialect, nil, migratable); err != nil {
			t.Fatalf("%s: RunMigrations: %v", backend.name, err)
		}
		rc, err := readRequiredColumns(context.Background(), db, backend.dialect)
		if err != nil {
			t.Fatalf("%s: reading required columns: %v", backend.name, err)
		}
		got[backend.name] = rc
	}

	if len(got) < 2 {
		t.Skipf("only %d dialect(s) configured; agreement needs at least two", len(got))
	}

	// Compare, per plugin table, across every configured dialect.
	var names []string
	for n := range got {
		names = append(names, n)
	}
	sort.Strings(names)
	base := names[0]

	var disagreements []string
	for pluginName, tables := range tablesOf {
		for _, table := range tables {
			for _, other := range names[1:] {
				a := got[base][strings.ToLower(table)]
				b := got[other][strings.ToLower(table)]
				for col := range union(a, b) {
					if a[col] == b[col] {
						continue
					}
					needs, doesNot := base, other
					if b[col] {
						needs, doesNot = other, base
					}
					disagreements = append(disagreements, fmt.Sprintf(
						"  %s.%s: %s requires a value, %s supplies one (plugin %s)",
						table, col, needs, doesNot, pluginName))
				}
			}
		}
	}
	sort.Strings(disagreements)

	if extra := notIn(disagreements, knownColumnAsymmetries); len(extra) > 0 {
		t.Errorf("dialects disagree about which columns a writer must supply:\n%s\n\n"+
			"A statement that omits such a column succeeds on the dialect that defaults it and "+
			"fails on the one that does not -- silently, if the caller logs and swallows, which "+
			"is cleat#958: zero audit events had ever been recorded on MySQL while the "+
			"table-existence test passed.\n\n"+
			"Fix the schema so the dialects agree, or -- if the plugin's own code already "+
			"supplies the value on the dialect that needs it -- add the line to "+
			"knownColumnAsymmetries with that reason.",
			strings.Join(extra, "\n"))
	}
	if closed := notIn(knownColumnAsymmetries, disagreements); len(closed) > 0 {
		t.Errorf("knownColumnAsymmetries records %d asymmetr(ies) that no longer exist:\n%s\n\n"+
			"Good news, and the list must shrink to match or it stops measuring anything.",
			len(closed), strings.Join(closed, "\n"))
	}
}

// knownColumnAsymmetries are dialect disagreements that exist and are
// compensated in code. SHRINK-ONLY: removing an entry when the schema is fixed
// is the point; adding one requires the reason here.
//
// Measured 2026-09-08. Both entries were verified at source, not taken on
// report: each names the code that supplies the value MySQL will not.
//
// Note what this list does and does not assert. The check above compares
// SCHEMAS, so an entry here means "the dialects disagree and I have read the
// code that compensates". It does not re-verify the compensation on every run
// -- deleting the MySQL-specific INSERT would not redden this test. Where that
// matters, the compensation needs its own write test: audit-log has one
// (IMPROVEMENT-PLAN 3.255, which drives recordAudit against a real MySQL and
// asserts the row lands), and event-triggers does not. That is a real gap and
// is named rather than implied.
var knownColumnAsymmetries = []string{
	// Compensated dialect-independently: plugins/auditlog/middleware.go supplies
	// uuid.NewString() on every dialect, so no statement depends on a default.
	// This was cleat#958 -- zero audit events had ever been recorded on MySQL --
	// and the fix deliberately did not add a MySQL default, because supplying
	// the id removes the class instead of moving it (and needs no MySQL 8.0.13+
	// for DEFAULT (uuid())).
	"  audit_events.id: mysql requires a value, mssql supplies one (plugin audit-log)",

	// Compensated per-dialect: plugins/eventtriggers/queries.go carries a
	// MySQL-specific INSERT listing `id` where Default and MSSQL omit it.
	// Verified at queries.go:41. This is the weaker shape of the two -- the
	// statement that must supply the value and the schema that requires it are
	// in different files, with nothing tying them together.
	"  event_subscriptions.id: mysql requires a value, mssql supplies one (plugin event-triggers)",
}

// union returns every key present in either set.
func union(a, b map[string]bool) map[string]bool {
	out := make(map[string]bool, len(a)+len(b))
	for k := range a {
		out[k] = true
	}
	for k := range b {
		out[k] = true
	}
	return out
}

// notIn returns members of a that are absent from b.
func notIn(a, b []string) []string {
	in := make(map[string]bool, len(b))
	for _, s := range b {
		in[s] = true
	}
	var out []string
	for _, s := range a {
		if !in[s] {
			out = append(out, s)
		}
	}
	return out
}

// freshPluginSchema returns a database with no plugin tables in it.
//
// PostgreSQL's backend already bootstraps a scratch database that it drops and
// recreates, so it is used unchanged. MySQL and SQL Server hand back the shared
// test database, so this creates a scratch one and points a new connection at
// it -- otherwise RunMigrations finds its bookkeeping rows already present and
// applies nothing.
func freshPluginSchema(t *testing.T, backend pluginTestBackend) (*sql.DB, func()) {
	t.Helper()
	if backend.dialect == plugin.DialectPostgres {
		return backend.setup(t)
	}

	admin, adminDown := backend.setup(t)
	name := fmt.Sprintf("cleat_usable963_%d", time.Now().UnixNano()%1e9)

	if _, err := admin.Exec("CREATE DATABASE " + name); err != nil {
		adminDown()
		t.Fatalf("%s: creating scratch database: %v", backend.name, err)
	}
	drop := func() {
		_, _ = admin.Exec("DROP DATABASE IF EXISTS " + name)
		adminDown()
	}

	var dsn, driver string
	switch backend.dialect {
	case plugin.DialectMySQL:
		driver = "mysql"
		dsn = rewriteMySQLDatabase(os.Getenv("CLEAT_TEST_MYSQL"), name)
	case plugin.DialectMSSQL:
		driver = "sqlserver"
		dsn = rewriteMSSQLDatabase(os.Getenv("CLEAT_TEST_MSSQL"), name)
	}
	db, err := sql.Open(driver, dsn)
	if err != nil {
		drop()
		t.Fatalf("%s: opening scratch database: %v", backend.name, err)
	}
	if err := db.Ping(); err != nil {
		db.Close()
		drop()
		t.Fatalf("%s: scratch database unreachable: %v", backend.name, err)
	}
	return db, func() { db.Close(); drop() }
}

// rewriteMySQLDatabase replaces the database in `user:pass@tcp(host)/db?params`.
func rewriteMySQLDatabase(dsn, db string) string {
	slash := strings.LastIndex(dsn, "/")
	if slash < 0 {
		return dsn
	}
	tail := ""
	if q := strings.Index(dsn[slash:], "?"); q >= 0 {
		tail = dsn[slash+q:]
	}
	return dsn[:slash+1] + db + tail
}

// rewriteMSSQLDatabase replaces the database= parameter in a sqlserver:// URL.
func rewriteMSSQLDatabase(dsn, db string) string {
	if i := strings.Index(dsn, "database="); i >= 0 {
		rest := dsn[i+len("database="):]
		if amp := strings.Index(rest, "&"); amp >= 0 {
			return dsn[:i] + "database=" + db + rest[amp:]
		}
		return dsn[:i] + "database=" + db
	}
	sep := "?"
	if strings.Contains(dsn, "?") {
		sep = "&"
	}
	return dsn + sep + "database=" + db
}

// readRequiredColumns asks the database which columns have no source of a value
// other than the writer.
//
// Table and column names are lowercased so the three dialects compare: SQL
// Server reports them as declared and MySQL's case handling depends on the
// platform, neither of which is a real difference.
func readRequiredColumns(ctx context.Context, db *sql.DB, dialect plugin.Dialect) (requiredColumns, error) {
	var q string
	switch dialect {
	case plugin.DialectPostgres:
		// is_identity and is_generated cover the columns PostgreSQL fills in
		// itself; column_default covers the rest.
		q = `SELECT table_name, column_name
		     FROM information_schema.columns
		     WHERE table_schema = current_schema()
		       AND is_nullable = 'NO'
		       AND column_default IS NULL
		       AND is_identity = 'NO'
		       AND is_generated = 'NEVER'`
	case plugin.DialectMySQL:
		// EXTRA carries auto_increment and DEFAULT_GENERATED; both mean the
		// database supplies a value even though COLUMN_DEFAULT may be NULL.
		q = `SELECT TABLE_NAME, COLUMN_NAME
		     FROM information_schema.COLUMNS
		     WHERE TABLE_SCHEMA = DATABASE()
		       AND IS_NULLABLE = 'NO'
		       AND COLUMN_DEFAULT IS NULL
		       AND EXTRA NOT LIKE '%auto_increment%'
		       AND EXTRA NOT LIKE '%DEFAULT_GENERATED%'`
	case plugin.DialectMSSQL:
		// sys.columns rather than information_schema alone: IDENTITY does not
		// appear as a COLUMN_DEFAULT, so an identity column would otherwise
		// read as one the writer must supply.
		q = `SELECT c.TABLE_NAME, c.COLUMN_NAME
		     FROM INFORMATION_SCHEMA.COLUMNS c
		     JOIN sys.columns sc
		       ON sc.object_id = OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME))
		      AND sc.name = c.COLUMN_NAME
		     WHERE c.IS_NULLABLE = 'NO'
		       AND c.COLUMN_DEFAULT IS NULL
		       AND sc.is_identity = 0
		       AND sc.is_computed = 0`
	default:
		return nil, fmt.Errorf("unknown dialect %q", dialect)
	}

	rows, err := db.QueryContext(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := requiredColumns{}
	for rows.Next() {
		var table, col string
		if err := rows.Scan(&table, &col); err != nil {
			return nil, err
		}
		table, col = strings.ToLower(table), strings.ToLower(col)
		if out[table] == nil {
			out[table] = map[string]bool{}
		}
		out[table][col] = true
	}
	return out, rows.Err()
}
