package engine

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Python WASM end-to-end test
//
// Tests the full Python -> WASM -> Host -> WASM -> Python round trip:
//   1. Compile a Python workflow to a WASM component via componentize-py
//   2. Decompose the component to a core module via wasm-tools (if needed)
//   3. Load the module into the wazero runtime
//   4. Execute the workflow (calling a mocked external service)
//   5. Verify the event history contains the expected DurableCall events
//   6. Verify the result is correctly serialized back through the ABI
// ---------------------------------------------------------------------------

// TestPythonWasmEndToEnd validates the full Python WASM execution path.
//
// Prerequisites (skipped with clear message when not found):
//   - componentize-py >= 0.12.0   (pip install componentize-py)
//   - wasm-tools                   (cargo install wasm-tools)
//   - Python 3.10+
//   - cleat-sdk installed          (pip install -e python-sdk/)
func TestPythonWasmEndToEnd(t *testing.T) {

ctx := context.Background()

	// ---- Check prerequisites ----
	pythonWasm := newPythonWasmTestHelper(t)
	if !pythonWasm.toolsAvailable() {
		t.Skip("Python WASM prerequisites not met: " + pythonWasm.missingTools())
	}

	// ---- Step 1: Compile the Python workflow to WASM ----
	wasmPath := pythonWasm.compileWorkflow(t, "durable_call_workflow.py", "durable_call_workflow")
	t.Logf("Python WASM compiled to: %s", wasmPath)

	wasmBytes, err := os.ReadFile(wasmPath)
	if err != nil {
		t.Fatalf("read compiled WASM: %v", err)
	}

	// ---- Step 2: Decompose the component model binary to a core module ----
	// wasm-tools >= 1.230 removed "component decompose". The wasmtime
	// backend's ExecuteComponent handles component binaries natively, so
	// we only decompose if the tool is available (for wazero fallback).
	if pythonWasm.canDecompose() {
		coreWasmPath := pythonWasm.decomposeComponent(t, wasmPath)
		if coreWasmPath != wasmPath {
			coreBytes, err := os.ReadFile(coreWasmPath)
			if err != nil {
				t.Fatalf("read decomposed WASM: %v", err)
			}
			wasmBytes = coreBytes
			t.Logf("Using decomposed core module: %s (%d bytes)", coreWasmPath, len(coreBytes))
		}
	}

	// ---- Step 3: Create runtime and engine with wasmtime backend ----
	rt, err := NewRuntime(ctx, 0, 0)
	if err != nil {
		t.Fatalf("NewRuntime: %v", err)
	}
	defer rt.Close(ctx)

	caller := &mockCaller{}
	var engineOpts []EngineOption
	if true {
		if wt, wtErr := NewWasmtimeBackend(ctx); wtErr == nil {
			engineOpts = append(engineOpts, WithBackend("python", wt))
			t.Log("wasmtime backend registered for python")
		} else {
			t.Logf("wasmtime backend not available: %v (falling back to wazero)", wtErr)
		}
	}
	engine := NewEngine(rt, caller, engineOpts...)

	// ---- Step 4: Execute the workflow ----
	input := `{"request":{"user_id":"u-test-42","message":"Hello from Python WASM","channel":"email"}}`

	// The entry point exported by the Python workflow is the WIT "run" export.
	// Python WASM components generated by componentize-py always export "run"
	// as the sole entry point, which dispatches to @cleat_entry functions.
	entryPoint := "run"

	result, history, suspended, deferrals, queryState, err := engine.Execute(ctx, wasmBytes, entryPoint, json.RawMessage(input))
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if suspended != nil {
		t.Fatalf("unexpected workflow suspension: %v", suspended.Reason)
	}
	if result == "" {
		t.Error("expected non-empty result from durable_call_workflow")
	}

	t.Logf("Execution produced %d events, result=%q", len(history), result)
	t.Logf("Deferrals: %v", deferrals)
	t.Logf("QueryState: %v", queryState)

	// ---- Step 5: Verify event history ----
	// The durable_call_workflow should produce these events:
	//   0: cleat_call (notifier.SendNotification) -- wrapped by the SDK
	if len(history) < 1 {
		t.Fatalf("expected at least 1 history event, got %d: %+v", len(history), history)
	}

	// Verify the call event.
	callFound := false
	for _, rec := range history {
		if rec.EventType == EventTypeCall {
			callFound = true
			if rec.Service != "notifier" {
				t.Errorf("expected service 'notifier', got %q", rec.Service)
			}
			if rec.Op != "SendNotification" {
				t.Errorf("expected operation 'SendNotification', got %q", rec.Op)
			}
		}
		if false /* sleep events no longer recorded */ {
			t.Errorf("unexpected sleep event: %+v", rec)
		}
	}

	if !callFound {
		t.Error("expected at least one EventTypeCall event in history")
	}

	// Verify the result is valid JSON.
	var resultData interface{}
	if err := json.Unmarshal([]byte(result), &resultData); err != nil {
		t.Errorf("result is not valid JSON: %v (raw: %s)", err, result)
	}

	t.Log("Python WASM end-to-end test passed")
}

// ---------------------------------------------------------------------------
// TestPythonWasmAbiBoundary validates the ABI between Python WASM stubs and
// the Go host without requiring compilation — it's a static verification that
// catches regressions in the host function interface.
// ---------------------------------------------------------------------------

// TestPythonWasmAbiBoundary verifies that all host functions expected by the
// Python SDK's WASM imports are registered in the Go host runtime.
func TestPythonWasmAbiBoundary(t *testing.T) {
	// These are the host function names that the Python SDK expects
	// (documented in host_calls.py stubs as (import "env" "<name>")).
	pythonExpectedImports := []string{
		"cleat_call",
		"cleat_call_retry",
		"cleat_call_heartbeat",
		"cleat_sleep",
		"cleat_now",
		"cleat_random",
		"cleat_log",
		"cleat_version",
		"cleat_min_version",
		"cleat_defer",
		"cleat_poll_cancellation",
		"cleat_poll_signal",
		"cleat_continue_as_new",
		"cleat_child_workflow",
		"cleat_child_workflow_with_options",
		"cleat_await_child",
		"cleat_await_signals",
		"set_query_state",
		"cleat_await_all_children",
		"plugin_call",
		"plugin_call_streaming",
		"cleat_create_promise",
		"cleat_await_promise",
		"cleat_resolve_promise",
		"cleat_reject_promise",
		"cleat_send",
		"cleat_schedule_invoke",
		"cleat_register_update_handler",
		"cleat_register_query_handler",
		"cleat_workflow_id",
		"cleat_run_id",
		"cleat_send_signal_and_wait",
		"cleat_reply_to_signal",
		"cleat_signal_workflow",
		"cleat_acquire_lock",
		"cleat_release_lock",
		"cleat_side_effect",
		// Stream R host functions
		"cleat_run_detached",
		"cleat_set_state",
		"cleat_get_state",
		"cleat_delete_state",
		"cleat_incr_state",
		"cleat_has_state",
		"cleat_list_state",
		"cleat_fetch",
	}
	// The list of host functions that can be discovered through the
	// registerHostFunctions registrations. We verify every expected
	// import has a corresponding registration.
	hostRegistered := make(map[string]bool)
	for _, name := range registeredImportNames() {
		hostRegistered[name] = true
	}

	var missing []string
	for _, name := range pythonExpectedImports {
		if !hostRegistered[name] {
			missing = append(missing, name)
		}
	}

	if len(missing) > 0 {
		t.Errorf("Python SDK expects %d host imports that are not registered on the Go host:\n  %s",
			len(missing), strings.Join(missing, "\n  "))
		for _, name := range missing {
			t.Logf("  Missing: %s", name)
		}
	}

	// Also verify bit-packing conventions match.
	testBitPackingCleatCall(t)
	testBitPackingSleep(t)
	testBitPackingAwaitSignals(t)
	testBitPackingSimpleResult(t)
	testBitPackingExportResult(t)
}

func testBitPackingCleatCall(t *testing.T) {
	// Verify that the Python decode_cleat_call_result and Go
	// packDurableCallResult use the same bit layout.
	//
	// Python: bits 40-63 = responseLen, bits 8-39 = callErrorCode, bits 0-7 = errCode
	// Go:     same layout (packDurableCallResult)
	responseLen := 42
	callErrorCode := byte(2)
	errCode := byte(0)

	packed := packDurableCallResult(responseLen, callErrorCode, errCode)

	// Extract using Python's decode_cleat_call_result formula.
	r := uint64(packed)
	decodedResponseLen := (r >> 40) & 0xFFFFFF
	decodedCallErrorCode := (r >> 8) & 0xFFFFFFFF
	decodedErrCode := r & 0xFF

	if decodedResponseLen != uint64(responseLen) {
		t.Errorf("responseLen mismatch: Go packed %d, Python decodes %d", responseLen, decodedResponseLen)
	}
	if decodedCallErrorCode != uint64(callErrorCode) {
		t.Errorf("callErrorCode mismatch: Go packed %d, Python decodes %d", callErrorCode, decodedCallErrorCode)
	}
	if decodedErrCode != uint64(errCode) {
		t.Errorf("errCode mismatch: Go packed %d, Python decodes %d", errCode, decodedErrCode)
	}
}

func testBitPackingSleep(t *testing.T) {
	// Verify sleep result bit packing.
	// Python: bits 56-63 = status, bits 0-55 = durationMs
	// Go:     packSleepResult has same layout
	status := byte(1)
	durationMs := int64(5000)

	packed := packSleepResult(status, durationMs)

	r := uint64(packed)
	decodedStatus := (r >> 56) & 0xFF
	_ = r & 0x00FFFFFFFFFFFFFF // durationMs (not verified)

	if decodedStatus != uint64(status) {
		t.Errorf("sleep status mismatch: Go packed %d, Python decodes %d", status, decodedStatus)
	}
}

func testBitPackingAwaitSignals(t *testing.T) {
	// Verify await_signals result bit packing.
	// Python: bits 48-63 = sigNameLen, bits 32-47 = payloadLen, bits 16-31 = timedOut, bits 0-15 = errCode
	// Go:     packAwaitSignalsResult has same layout
	sigNameLen := uint32(5)
	payloadLen := uint32(10)
	timedOut := false
	errCode := uint32(0)

	packed := packAwaitSignalsResult(sigNameLen, payloadLen, timedOut, errCode)

	r := uint64(packed)
	decodedSigNameLen := (r >> 48) & 0xFFFF
	decodedPayloadLen := (r >> 32) & 0xFFFF
	decodedTimedOut := ((r >> 16) & 0xFFFF) != 0
	decodedErrCode := r & 0xFFFF

	if decodedSigNameLen != uint64(sigNameLen) {
		t.Errorf("sigNameLen mismatch: Go packed %d, Python decodes %d", sigNameLen, decodedSigNameLen)
	}
	if decodedPayloadLen != uint64(payloadLen) {
		t.Errorf("payloadLen mismatch: Go packed %d, Python decodes %d", payloadLen, decodedPayloadLen)
	}
	if decodedTimedOut != timedOut {
		t.Errorf("timedOut mismatch: Go packed %v, Python decodes %v", timedOut, decodedTimedOut)
	}
	if decodedErrCode != uint64(errCode) {
		t.Errorf("errCode mismatch: Go packed %d, Python decodes %d", errCode, decodedErrCode)
	}
}

func testBitPackingSimpleResult(t *testing.T) {
	// Verify simple result bit packing (used by defer, child_workflow, etc.).
	// Python: bits 32-63 = extra, bits 0-7 = errCode
	// Go:     packSimpleResult has same layout
	errCode := byte(0)
	extra := uint32(100)

	packed := packSimpleResult(errCode, extra)

	r := uint64(packed)
	decodedExtra := (r >> 32) & 0xFFFFFFFF
	decodedErrCode := r & 0xFF

	if decodedExtra != uint64(extra) {
		t.Errorf("extra mismatch: Go packed %d, Python decodes %d", extra, decodedExtra)
	}
	if decodedErrCode != uint64(errCode) {
		t.Errorf("errCode mismatch: Go packed %d, Python decodes %d", errCode, decodedErrCode)
	}
}

func testBitPackingExportResult(t *testing.T) {
	// Verify export result bit packing.
	// Python: encode_export_result(err_code, actual_len) -> bits 0-31 = errCode, bits 32-63 = actualLen
	// Go:     decodeExportResult same layout
	errCode := uint32(0)
	actualLen := uint32(50)

	// Simulate Go's writeJSONOut encoding: (int64(actualLen) << 32) | errCode
	packed := uint64(actualLen)<<32 | uint64(errCode)

	decodedErrCode := uint32(packed & 0xFFFFFFFF)
	decodedActualLen := uint32(packed >> 32)

	if decodedErrCode != errCode {
		t.Errorf("errCode mismatch: %d vs %d", errCode, decodedErrCode)
	}
	if decodedActualLen != actualLen {
		t.Errorf("actualLen mismatch: %d vs %d", actualLen, decodedActualLen)
	}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// pythonWasmTestHelper manages the Python WASM compilation toolchain.
type pythonWasmTestHelper struct {
	t        *testing.T
	repoRoot string
	sdkRoot  string
	missing  []string
}

func newPythonWasmTestHelper(t *testing.T) *pythonWasmTestHelper {
	h := &pythonWasmTestHelper{t: t}
	h.repoRoot = findRepoRoot(t)
	h.sdkRoot = filepath.Join(h.repoRoot, "python-sdk")
	h.missing = nil
	return h
}

func (h *pythonWasmTestHelper) toolsAvailable() bool {
	h.missing = nil

	// Check componentize-py.
	if _, err := exec.LookPath("componentize-py"); err != nil {
		h.missing = append(h.missing, "componentize-py (pip install componentize-py)")
	}

	// Check wasm-tools (needed to decompose component model -> core module).
	if _, err := exec.LookPath("wasm-tools"); err != nil {
		h.missing = append(h.missing, "wasm-tools (cargo install wasm-tools)")
	}

	// Check Python 3.
	if _, err := exec.LookPath("python3"); err != nil {
		h.missing = append(h.missing, "python3")
	}

	// Check that the SDK examples directory exists.
	examplesDir := filepath.Join(h.sdkRoot, "examples")
	if _, err := os.Stat(examplesDir); os.IsNotExist(err) {
		h.missing = append(h.missing, "python-sdk/examples/")
	}

	return len(h.missing) == 0
}

func (h *pythonWasmTestHelper) missingTools() string {
	return "missing: " + strings.Join(h.missing, ", ")
}

// compileWorkflow compiles a Python workflow to WASM using componentize-py.
func (h *pythonWasmTestHelper) compileWorkflow(t *testing.T, pyFile, funcName string) string {
	t.Helper()

	examplesDir := filepath.Join(h.sdkRoot, "examples")
	entry := filepath.Join(examplesDir, pyFile) + ":" + funcName

	output := filepath.Join(t.TempDir(), funcName+".wasm")

	// Use the cleat build_python.go path through BuildPythonWasm.
	cmd := exec.Command("python3",
		filepath.Join(h.sdkRoot, "scripts", "build_wasm.py"),
		"--entry", entry,
		"--output", output,
		"--verbose",
	)
	cmd.Dir = h.sdkRoot
	cmd.Env = append(os.Environ(), "PYTHONPATH="+h.sdkRoot)

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("componentize-py failed:\n%s\n%v", string(out), err)
	}
	t.Logf("componentize-py output:\n%s", string(out))

	if _, err := os.Stat(output); os.IsNotExist(err) {
		t.Fatalf("WASM output not found at %s", output)
	}
	return output
}

// canDecompose returns true if wasm-tools component decompose is available.
func (h *pythonWasmTestHelper) canDecompose() bool {
	wt, err := exec.LookPath("wasm-tools")
	if err != nil {
		return false
	}
	// Check that "wasm-tools component decompose" is a recognized subcommand.
	cmd := exec.Command(wt, "component", "decompose", "--help")
	if err := cmd.Run(); err != nil {
		return false
	}
	return true
}

// decomposeComponent converts a Component Model binary to a core WASM module.
// Returns the path to the core module. If wasm-tools is not available or the
// binary is already a core module, returns the original path.
func (h *pythonWasmTestHelper) decomposeComponent(t *testing.T, wasmPath string) string {
	t.Helper()

	if _, err := exec.LookPath("wasm-tools"); err != nil {
		t.Log("wasm-tools not available, skipping component decomposition")
		return wasmPath
	}

	// Component model binaries start with \x00asm, but core modules also do.
	// The real test is whether CompileModule succeeds.
	// We attempt decomposition; if it fails we assume it's already a core module.
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "core.wasm")

	cmd := exec.Command("wasm-tools", "component", "decompose", wasmPath, "-o", outputPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("wasm-tools decompose failed (may already be core module): %s\n%s", err, string(out))
		return wasmPath
	}

	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Log("decompose produced no output, using original")
		return wasmPath
	}

	return outputPath
}

// skipIfNoDecompose skips the test when wasm-tools component decompose is
// not available (removed in wasm-tools >= ~1.230).
func (h *pythonWasmTestHelper) skipIfNoDecompose(t *testing.T) {
	t.Helper()
	t.Skip("wasm-tools component decompose not available — removed in wasm-tools >= 1.230. " +
		"The engine requires decomposed core WASM. Install older wasm-tools or implement " +
		"native Component Model support in the wasmtime backend.")
}

// findRepoRoot locates the repository root by finding go.mod.
func findRepoRoot(t *testing.T) string {
	t.Helper()

	cwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	for dir := cwd; ; dir = filepath.Dir(dir) {
		if fi, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !fi.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("go.mod not found from %s", cwd)
		}
	}
}

// registeredImportNames returns the names of all registered host function imports.
// This is used by the ABI boundary test to verify against Python's expectations.
func registeredImportNames() []string {
	// This list must stay in sync with the Export("...") calls in registerHostFunctions
	// in imports.go. When adding new host functions, add them here too.
	return []string{
		"cleat_call",
		"cleat_sleep",
		"cleat_now",
		"cleat_random",
		"cleat_log",
		"cleat_version",
		"cleat_min_version",
		"cleat_defer",
		"cleat_poll_cancellation",
		"cleat_poll_signal",
		"cleat_continue_as_new",
		"cleat_continue_as_new_versioned",
		"cleat_child_workflow",
		"cleat_child_workflow_with_options",
		"cleat_child_workflow_in_schema",
		"cleat_await_child",
		"cleat_call_retry",
		"cleat_await_signals",
		"set_query_state",
		"cleat_call_heartbeat",
		"cleat_await_all_children",
		"cleat_create_promise",
		"cleat_await_promise",
		"plugin_call_streaming",
		"plugin_call",
		"cleat_register_update_handler",
		"cleat_send_signal_and_wait",
		"cleat_reply_to_signal",
		"cleat_signal_workflow",
		"cleat_set_scope",
		"cleat_get_scope",
		"cleat_uuid",
		"cleat_acquire_lock",
		"cleat_release_lock",
		"cleat_side_effect",
		"cleat_workflow_id",
		"cleat_run_id",
		"cleat_resolve_promise",
		"cleat_reject_promise",
		"cleat_send",
		"cleat_schedule_invoke",
		"cleat_register_query_handler",
		// Stream R host functions
		"cleat_run_detached",
		"cleat_set_state",
		"cleat_get_state",
		"cleat_delete_state",
		"cleat_incr_state",
		"cleat_has_state",
		"cleat_list_state",
		"cleat_fetch",
	}
}

// ---------------------------------------------------------------------------
// compile-time check: engine.go must have the new HostHandler methods
// ---------------------------------------------------------------------------

// Ensure the execSession implements the full HostHandler interface.
var _ HostHandler = (*execSession)(nil)
