package engine

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"golang.org/x/sys/unix"
)

// maxRedactDepth limits the recursion depth when redacting nested JSON values
// to prevent stack overflow from malicious deeply-nested input.
const maxRedactDepth = 50

// sensitivePatterns lists field name substrings whose values should be redacted.
// Matching is done case-insensitively.
var sensitivePatterns = []string{
	"token",
	"secret",
	"password",
	"credential",
	"api_key",
	"authorization",
	"api-key",
}

// isSensitiveField returns true if the field name matches any sensitive pattern.
//
// Note: Unicode homoglyphs (e.g., Cyrillic 'o' vs Latin 'o') can bypass
// substring matching because normalization is not applied. This is acceptable
// because field names in this system are programmatically generated by SDKs
// and are always ASCII. Normalization via golang.org/x/text/unicode/norm is
// a future enhancement if non-ASCII field names become relevant.
func isSensitiveField(name string) bool {
	lower := strings.ToLower(name)
	for _, p := range sensitivePatterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

// looksLikeJWT returns true if the string has three base64-ish segments separated
// by dots, which is the characteristic structure of a JSON Web Token.
func looksLikeJWT(s string) bool {
	parts := strings.Split(s, ".")
	if len(parts) != 3 {
		return false
	}
	// Each segment should be non-empty base64-url (no whitespace, valid chars).
	for _, p := range parts {
		if len(p) == 0 {
			return false
		}
		for _, c := range p {
			if !isBase64URLChar(c) {
				return false
			}
		}
	}
	return true
}

// isBase64URLChar returns true if c is a valid base64url character or '=' padding.
func isBase64URLChar(c rune) bool {
	return (c >= 'a' && c <= 'z') ||
		(c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') ||
		c == '-' || c == '_' || c == '='
}

// Redact processes a JSON string and returns a redacted version where
// sensitive fields have their values replaced with "[REDACTED]". It handles:
//   - Nested objects recursively
//   - String values that look like JWTs
//   - Field names matching token, secret, password, credential, api_key,
//     authorization, and similar patterns (case-insensitive)
//
// If the input is not valid JSON, it is returned as-is.
func Redact(raw string) string {
	if !json.Valid([]byte(raw)) {
		// If it's not valid JSON, still check if the whole string looks like a JWT.
		if looksLikeJWT(raw) {
			// BARE, not quoted: this branch is not JSON, so the placeholder is
			// the whole value rather than a literal spliced into a document.
			// TestRedact_NonJSON_JWT caught exactly this distinction.
			return redactedPlain
		}
		return raw
	}

	spans, err := collectRedactSpans(raw)
	if err != nil || len(spans) == 0 {
		// Nothing to redact means the input is returned BYTE FOR BYTE. See
		// the note on collectRedactSpans for why that is the whole point.
		return raw
	}

	var b strings.Builder
	b.Grow(len(raw))
	prev := 0
	for _, sp := range spans {
		b.WriteString(raw[prev:sp.start])
		b.WriteString(redactedJSON)
		prev = sp.end
	}
	b.WriteString(raw[prev:])
	return b.String()
}

// redactedJSON is the placeholder as it appears in a JSON document: a string
// literal, quotes included, because it is spliced into text rather than
// marshalled from a Go value.
const redactedJSON = `"[REDACTED]"`

// redactedPlain is the same placeholder for a value that is not part of a JSON
// document.
const redactedPlain = "[REDACTED]"

// redactSpan is a half-open byte range of the input that must be replaced.
type redactSpan struct{ start, end int }

// collectRedactSpans finds the byte ranges to replace, WITHOUT reserialising
// the document.
//
// THIS FUNCTION EXISTS BECAUSE THE OBVIOUS IMPLEMENTATION CORRUPTS DATA.
// Redact used to json.Unmarshal into map[string]any, walk it, and json.Marshal
// the result. That round trip rewrites every payload it touches, whether or
// not anything was redacted, because a Go map has no key order and every JSON
// number becomes a float64:
//
//	{"zebra":1,"apple":2}        -> {"apple":2,"zebra":1}
//	{"id":12345678901234567890}  -> {"id":12345678901234567000}
//	{"id":9007199254740993}      -> {"id":9007199254740992}
//	{"amount":1.0}               -> {"amount":1}
//	{"big":1e300}                -> {"big":1e+300}
//
// The last four are not cosmetic. Any integer above 2^53 -- a snowflake id, a
// bigint primary key, a cents amount on a large ledger -- comes back a
// DIFFERENT NUMBER. Redact is applied on the read path to ten fields of every
// event record (store_events.go and its MySQL and SQL Server twins), and the
// replay path loads history through exactly that read, so a resumed workflow
// was handed values its first run never saw. That is the one thing a durable
// engine must not do, and it was being done by the engine itself.
//
// Collecting spans and splicing makes the no-redaction case the identity
// function and confines every change to the values actually being hidden.
func collectRedactSpans(raw string) ([]redactSpan, error) {
	dec := json.NewDecoder(strings.NewReader(raw))
	dec.UseNumber()
	var spans []redactSpan
	if err := scanRedactValue(dec, raw, 0, false, &spans); err != nil {
		return nil, err
	}
	return spans, nil
}

// scanRedactValue consumes one JSON value, appending spans for what must be
// hidden. redact is true when an enclosing key was sensitive, in which case
// the whole value becomes one span and its interior is not walked -- nested
// spans inside a span would splice twice.
func scanRedactValue(dec *json.Decoder, raw string, depth int, redact bool, spans *[]redactSpan) error {
	pre := int(dec.InputOffset())
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	start := redactValueStart(raw, pre)

	if d, ok := tok.(json.Delim); ok {
		if redact {
			if err := skipRedactComposite(dec); err != nil {
				return err
			}
			*spans = append(*spans, redactSpan{start, int(dec.InputOffset())})
			return nil
		}
		// Beyond the depth cap the subtree is left alone, which is what the
		// recursive implementation did on the same bound.
		if depth > maxRedactDepth {
			return skipRedactComposite(dec)
		}
		if d == '{' {
			for dec.More() {
				ktok, kerr := dec.Token()
				if kerr != nil {
					return kerr
				}
				key, _ := ktok.(string)
				if err := scanRedactValue(dec, raw, depth+1, isSensitiveField(key), spans); err != nil {
					return err
				}
			}
		} else {
			for dec.More() {
				if err := scanRedactValue(dec, raw, depth+1, false, spans); err != nil {
					return err
				}
			}
		}
		_, err := dec.Token() // the closing delimiter
		return err
	}

	end := int(dec.InputOffset())
	if redact {
		*spans = append(*spans, redactSpan{start, end})
		return nil
	}
	if str, ok := tok.(string); ok && looksLikeJWT(str) {
		*spans = append(*spans, redactSpan{start, end})
	}
	return nil
}

// skipRedactComposite consumes the remainder of an object or array whose
// opening delimiter has already been read.
func skipRedactComposite(dec *json.Decoder) error {
	for depth := 1; depth > 0; {
		tok, err := dec.Token()
		if err != nil {
			return err
		}
		if d, ok := tok.(json.Delim); ok {
			switch d {
			case '{', '[':
				depth++
			case '}', ']':
				depth--
			}
		}
	}
	return nil
}

// redactValueStart walks forward from the end of the previous token to the
// first byte of the next value, stepping over the structural characters the
// decoder does not report as tokens.
//
// Only characters BEFORE the value are skipped, so a string value containing
// a colon or a comma is unaffected: the scan stops at its opening quote.
func redactValueStart(raw string, from int) int {
	for i := from; i < len(raw); i++ {
		switch raw[i] {
		case ' ', '\t', '\n', '\r', ':', ',':
			continue
		}
		return i
	}
	return len(raw)
}

// redactValueDepth recursively redacts sensitive values with a recursion depth
// limit to prevent stack overflow from deeply-nested input.
func redactValueDepth(v any, depth int) any {
	if depth > maxRedactDepth {
		return v
	}
	switch val := v.(type) {
	case map[string]any:
		return redactMapDepth(val, depth)
	case []any:
		return redactSliceDepth(val, depth)
	case string:
		if looksLikeJWT(val) {
			return "[REDACTED]"
		}
		return val
	default:
		return val
	}
}

// redactMap redacts sensitive fields in a JSON object.
func redactMap(m map[string]any) map[string]any {
	return redactMapDepth(m, 0)
}

// redactMapDepth redacts sensitive fields in a JSON object with a recursion
// depth limit.
func redactMapDepth(m map[string]any, depth int) map[string]any {
	result := make(map[string]any, len(m))
	for k, v := range m {
		if isSensitiveField(k) {
			result[k] = "[REDACTED]"
		} else {
			result[k] = redactValueDepth(v, depth+1)
		}
	}
	return result
}

// redactSlice recursively redacts each element of a JSON array.
func redactSlice(arr []any) []any {
	return redactSliceDepth(arr, 0)
}

// redactSliceDepth recursively redacts each element of a JSON array with a
// recursion depth limit.
func redactSliceDepth(arr []any, depth int) []any {
	result := make([]any, len(arr))
	for i, v := range arr {
		result[i] = redactValueDepth(v, depth+1)
	}
	return result
}

// RedactMap is like Redact but operates on a map[string]any in-place,
// returning the same map. This is useful when the input is already parsed.
func RedactMap(m map[string]any) {
	for k, v := range m {
		if isSensitiveField(k) {
			m[k] = "[REDACTED]"
		} else {
			switch nested := v.(type) {
			case map[string]any:
				m[k] = redactMapDepth(nested, 1)
			case []any:
				m[k] = redactSliceDepth(nested, 1)
			}
		}
	}
}

// customPatterns holds additional sensitive-field patterns loaded from a file.
var customPatterns []string

// patternsFileLoaded is true after LoadRedactPatterns succeeds. It prevents
// the custom patterns from being overwritten by a nil/empty file.
var patternsFileLoaded bool

// LoadRedactPatterns reads a newline-separated list of sensitive-field
// substrings from path and appends them to the built-in patterns. Blank lines
// and lines starting with '#' are ignored. Returns an error if the file cannot
// be read.
func LoadRedactPatterns(path string) error {
	f, err := os.OpenFile(path, os.O_RDONLY|unix.O_NOFOLLOW, 0)
	if err != nil {
		return fmt.Errorf("redact patterns: open %s: %w", path, err)
	}
	defer f.Close()

	var added int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Avoid duplicates.
		found := false
		for _, p := range sensitivePatterns {
			if strings.EqualFold(p, line) {
				found = true
				break
			}
		}
		if !found {
			for _, p := range customPatterns {
				if strings.EqualFold(p, line) {
					found = true
					break
				}
			}
		}
		if !found {
			customPatterns = append(customPatterns, line)
		}
		added++
	}
	if err := sc.Err(); err != nil {
		return fmt.Errorf("redact patterns: read %s: %w", path, err)
	}
	patternsFileLoaded = true
	return nil
}

// RedactOnRead applies retroactive redaction to a string that was loaded from
// persistent storage. It behaves identically to Redact but is named differently
// to clarify the caller's intent: this is read-path redaction for data that may
// have been stored before redaction was mandatory.
func RedactOnRead(data string) string {
	return Redact(data)
}

// ResetPatterns clears all custom patterns (for testing only).
func ResetPatterns() {
	customPatterns = nil
	patternsFileLoaded = false
}
