package auditlog

// The audit log's hash chain: what is hashed, and how (cleat#2047).
//
// Each tenant's audit rows form a chain. A row stores the hash of its own
// canonical content plus the previous row's hash, so editing a row changes its
// hash, and deleting or reordering rows breaks the link that follows.
//
// The precise encoding is a CONTRACT, because a verifier that is not this code
// (an auditor's script, a SIEM) has to reproduce it. testdata/audit_chain_reference.py
// is that contract written a second time in a different language, and
// testdata/chain_vectors.json is generated by it: chain_test.go asserts this file
// reproduces every hash. Two implementations of one prose spec agreeing is evidence;
// this one agreeing with its own output would not be.
//
// The hash is SHA-256, not the xxhash64 that engine.computeEventChecksum uses for
// event_history. That one detects corruption; anyone who edits a row can recompute a
// non-cryptographic hash in one line, so it would be a checksum and not tamper
// evidence.

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/google/uuid"
)

// chainDomain separates this hash from any other use of SHA-256 over similar bytes.
const chainDomain = "cleat-audit-chain-v1\x00"

// chainHashLen is the raw length of a hash. The first row of a tenant's chain has a
// prev_hash of this many zero bytes.
const chainHashLen = sha256.Size

// chainTimestampLayout is the timestamp as hashed: UTC, fixed-width, microseconds.
// Microseconds because PostgreSQL TIMESTAMPTZ and MySQL TIMESTAMP(6) cannot hold more
// (SQL Server's DATETIMEOFFSET can, and is truncated to match).
const chainTimestampLayout = "2006-01-02T15:04:05.000000Z"

// chainRecord is exactly the set of values a row's hash covers. Nullable columns are
// sql.Null* so that NULL and the empty string hash differently.
type chainRecord struct {
	TenantID   uuid.UUID
	Seq        int64
	ID         uuid.UUID
	Timestamp  time.Time
	Method     string
	Path       string
	StatusCode sql.NullInt64
	UserID     sql.NullString
	IPAddress  sql.NullString
	UserAgent  sql.NullString
	DurationMs sql.NullInt64
	// Metadata is the JSON as stored. NULL is Valid=false.
	Metadata sql.NullString
}

// canonicalTimestamp is t in UTC, truncated (never rounded) to the microsecond.
func canonicalTimestamp(t time.Time) string {
	return t.UTC().Truncate(time.Microsecond).Format(chainTimestampLayout)
}

// appendField writes one field: a presence byte (0 = NULL, 1 = present) and, when
// present, uvarint(len) and the bytes. Every field is text, so a value cannot be
// confused with its neighbour and there is no delimiter to forge.
func appendField(b []byte, v *string) []byte {
	if v == nil {
		return append(b, 0)
	}
	b = append(b, 1)
	b = binary.AppendUvarint(b, uint64(len(*v)))
	return append(b, *v...)
}

func strp(s string) *string { return &s }

func nullStr(n sql.NullString) *string {
	if !n.Valid {
		return nil
	}
	return &n.String
}

func nullInt(n sql.NullInt64) *string {
	if !n.Valid {
		return nil
	}
	return strp(strconv.FormatInt(n.Int64, 10))
}

// chainHash computes a row's hash from the previous row's hash (or the zero value for
// the first row of a tenant).
func chainHash(prev [chainHashLen]byte, r chainRecord) ([chainHashLen]byte, error) {
	var meta *string
	if r.Metadata.Valid {
		c, err := canonicalJSON(r.Metadata.String)
		if err != nil {
			return [chainHashLen]byte{}, fmt.Errorf("metadata of audit row %s is not JSON: %w", r.ID, err)
		}
		meta = strp(c)
	}
	var invalid string
	for _, s := range []string{r.Method, r.Path} {
		if !utf8.ValidString(s) {
			invalid = s
		}
	}
	if invalid != "" {
		return [chainHashLen]byte{}, fmt.Errorf("audit row %s has a value that is not valid UTF-8", r.ID)
	}

	buf := make([]byte, 0, 256)
	buf = append(buf, chainDomain...)
	buf = append(buf, prev[:]...)
	buf = appendField(buf, strp(r.TenantID.String()))
	buf = appendField(buf, strp(strconv.FormatInt(r.Seq, 10)))
	buf = appendField(buf, strp(r.ID.String()))
	buf = appendField(buf, strp(canonicalTimestamp(r.Timestamp)))
	buf = appendField(buf, strp(r.Method))
	buf = appendField(buf, strp(r.Path))
	buf = appendField(buf, nullInt(r.StatusCode))
	buf = appendField(buf, nullStr(r.UserID))
	buf = appendField(buf, nullStr(r.IPAddress))
	buf = appendField(buf, nullStr(r.UserAgent))
	buf = appendField(buf, nullInt(r.DurationMs))
	buf = appendField(buf, meta)
	return sha256.Sum256(buf), nil
}

// canonicalJSON re-encodes JSON text into the one form every dialect and language can
// reproduce. PostgreSQL JSONB, MySQL JSON and SQL Server text each normalise a document
// differently on the way in (key order, whitespace, number spelling), so the hash cannot
// be taken over what the database hands back. Rules: object keys sorted by code point,
// no whitespace, strings escaped only for the quote, the backslash and control
// characters below 0x20 (as \u00xx, lower-case hex) and otherwise verbatim, numbers as
// the original token.
func canonicalJSON(text string) (string, error) {
	dec := json.NewDecoder(strings.NewReader(text))
	dec.UseNumber()
	var v any
	if err := dec.Decode(&v); err != nil {
		return "", err
	}
	if _, err := dec.Token(); err != io.EOF {
		return "", fmt.Errorf("trailing data after the JSON value")
	}
	var b bytes.Buffer
	writeCanonical(&b, v)
	return b.String(), nil
}

func writeCanonical(b *bytes.Buffer, v any) {
	switch x := v.(type) {
	case nil:
		b.WriteString("null")
	case bool:
		if x {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	case json.Number:
		b.WriteString(string(x))
	case string:
		writeCanonicalString(b, x)
	case []any:
		b.WriteByte('[')
		for i, e := range x {
			if i > 0 {
				b.WriteByte(',')
			}
			writeCanonical(b, e)
		}
		b.WriteByte(']')
	case map[string]any:
		keys := make([]string, 0, len(x))
		for k := range x {
			keys = append(keys, k)
		}
		// Byte order of UTF-8 is code point order.
		sort.Strings(keys)
		b.WriteByte('{')
		for i, k := range keys {
			if i > 0 {
				b.WriteByte(',')
			}
			writeCanonicalString(b, k)
			b.WriteByte(':')
			writeCanonical(b, x[k])
		}
		b.WriteByte('}')
	default:
		// json.Decoder produces nothing else; refusing is louder than guessing.
		panic(fmt.Sprintf("auditlog: canonicalJSON: unexpected %T", v))
	}
}

func writeCanonicalString(b *bytes.Buffer, s string) {
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"':
			b.WriteString(`\"`)
		case r == '\\':
			b.WriteString(`\\`)
		case r < 0x20:
			fmt.Fprintf(b, `\u%04x`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
}
