// Code generated by cleat-gen plugin-client. DO NOT EDIT.

package email

import (
	"github.com/cleat-team/cleat/cleat"
)

type SendInput struct {
	To       string   `json:"to"`
	Subject  string   `json:"subject"`
	BodyHTML string   `json:"body_html"`
	BodyText string   `json:"body_text,omitempty"`
	From     string   `json:"from,omitempty"`
	ReplyTo  string   `json:"reply_to,omitempty"`
	CC       []string `json:"cc,omitempty"`
	BCC      []string `json:"bcc,omitempty"`
}

type SendOutput struct {
	MessageID string `json:"message_id"`
	Status    string `json:"status"`
}

type SendTemplateInput struct {
	To           string         `json:"to"`
	TemplateID   string         `json:"template_id"`
	TemplateData map[string]any `json:"template_data"`
	From         string         `json:"from,omitempty"`
	ReplyTo      string         `json:"reply_to,omitempty"`
}

type SendTemplateOutput struct {
	MessageID string `json:"message_id"`
	Status    string `json:"status"`
}

type CheckStatusInput struct {
	MessageID string `json:"message_id"`
}

type StatusEvent struct {
	Timestamp string `json:"timestamp"`
	Event     string `json:"event"`
}

type CheckStatusOutput struct {
	Status string        `json:"status"`
	Events []StatusEvent `json:"events"`
}

var CheckStatus = cleat.NewPluginFunc[CheckStatusInput, CheckStatusOutput]("email-notify", "check_status")

var Send = cleat.NewPluginFunc[SendInput, SendOutput]("email-notify", "send")

var SendTemplate = cleat.NewPluginFunc[SendTemplateInput, SendTemplateOutput]("email-notify", "send_template")
