package main

import (
	"bytes"
	"fmt"
	"go/token"
	"go/types"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/cleat-team/cleat/internal/analyzer"
	"github.com/fsnotify/fsnotify"
)

// devGenPrefix names the temp file buildDevRun generates. It has to live in
// the module directory so "go run" can resolve the workflow package import via
// go.mod -- which means that whenever the workflow package IS the module root,
// the generated file lands inside the tree runDevWithWatch is watching.
//
// The watch loop therefore has to skip it by name. It did not, and the result
// was that `cleat dev --watch` rebuilt itself forever: build writes a .go file,
// fsnotify reports a .go file, debounce fires, build writes another. Measured
// on a single-package module before this change: 76 rebuilds in 25 seconds
// with no file touched by anyone, and 34 abandoned cleat_dev_*.go files left
// sitting in the user's source directory.
//
// Keep the constant shared between the writer and the filter. Two string
// literals is how this drifts back.
const devGenPrefix = "cleat_dev_"

// shouldRebuild reports whether a filesystem event on path should trigger a
// rebuild: a Go source file that is not one of our own generated runners.
func shouldRebuild(path string) bool {
	base := filepath.Base(path)
	return strings.HasSuffix(base, ".go") && !strings.HasPrefix(base, devGenPrefix)
}

// paramInfo describes an entry-point parameter beyond cleat.HostCalls.
type paramInfo struct {
	Name    string // parameter name (e.g., "userID")
	TypeStr string // Go type expression (e.g., "string", "basic.CartItem")
	JSONTag string // JSON tag (e.g., "userID")
}

// returnKind classifies the entry-point return signature.
type returnKind int

const (
	returnStringError returnKind = iota // (string, error) — most common
	returnError                         // (error)
	returnString                        // (string)
	returnNothing                       // ()
)

// ---------------------------------------------------------------------------
// checkSigClassifies the entry-point return signature.

func classifyReturn(sig *types.Signature) (returnKind, string) {
	res := sig.Results()
	switch res.Len() {
	case 0:
		return returnNothing, ""
	case 1:
		// Could be error or just a value.
		if isErrorType(res.At(0).Type()) {
			return returnError, ""
		}
		return returnString, types.TypeString(res.At(0).Type(), nil)
	case 2:
		if isErrorType(res.At(1).Type()) {
			return returnStringError, types.TypeString(res.At(0).Type(), nil)
		}
		fallthrough
	default:
		return returnStringError, "string" // best effort
	}
}

func isErrorType(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	return named.Obj().Name() == "error" && named.Obj().Pkg() == nil
}

// ---------------------------------------------------------------------------
// Build parameter info for template

func buildParams(result *analyzer.AnalysisResult, fd *analyzer.FuncDecl) []paramInfo {
	sig := fd.Type
	params := sig.Params()
	if params.Len() <= 1 {
		return nil
	}

	// The first param is always cleat.HostCalls; skip it.
	targetPath := result.TargetPkg.Path

	var infos []paramInfo
	for i := 1; i < params.Len(); i++ {
		p := params.At(i)
		name := p.Name()
		if name == "" {
			name = fmt.Sprintf("arg%d", i)
		}
		// Build a qualifier that maps the target package to its own name,
		// and other packages to their bare names.
		typeStr := types.TypeString(p.Type(), func(other *types.Package) string {
			if other.Path() == targetPath {
				return result.TargetPkg.Name
			}
			return other.Name()
		})
		infos = append(infos, paramInfo{
			Name:    toExported(name),
			TypeStr: typeStr,
			JSONTag: name,
		})
	}
	return infos
}

// toExported capitalises the first letter of a name for use as an exported
// struct field.
func toExported(name string) string {
	if name == "" {
		return "X"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

// ---------------------------------------------------------------------------
// Generate the temp Go file

func generateDevMain(result *analyzer.AnalysisResult, funcName string, params []paramInfo, kind returnKind, concurrencyKey string) ([]byte, error) {
	pkgPath := result.TargetPkg.Path
	pkgName := result.TargetPkg.Name

	var buf bytes.Buffer

	// Header
	buf.WriteString("//go:build ignore\n")
	buf.WriteString("// Code generated by \"cleat dev\"; DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\n")

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"os\"\n")
	buf.WriteString("\t\"strings\"\n")
	if concurrencyKey != "" {
		buf.WriteString("\t\"time\"\n")
	}
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/cleat-team/cleat/cleat/localdev\"\n")
	fmt.Fprintf(&buf, "\t%q\n", pkgPath)
	buf.WriteString(")\n\n")

	// httpCaller implementation
	buf.WriteString("// httpCaller implements localdev.ServiceCaller by making HTTP requests.\n")
	buf.WriteString("// Configure service URLs via CLEAT_DEV_URL_<SERVICE> env vars.\n")
	buf.WriteString("type httpCaller struct{}\n\n")
	buf.WriteString("func (c *httpCaller) Call(ctx context.Context, service, operation, requestJSON string) (string, error) {\n")
	buf.WriteString("\tenvKey := \"CLEAT_DEV_URL_\" + strings.ToUpper(strings.ReplaceAll(service, \"-\", \"_\"))\n")
	buf.WriteString("\tbaseURL := os.Getenv(envKey)\n")
	buf.WriteString("\tif baseURL == \"\" {\n")
	buf.WriteString("\t\tbaseURL = \"http://localhost:8080/api/\" + service\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\turl := strings.TrimRight(baseURL, \"/\") + \"/\" + operation\n")
	buf.WriteString("\tresp, err := http.Post(url, \"application/json\", strings.NewReader(requestJSON))\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn \"\", fmt.Errorf(\"%s.%s: %w\", service, operation, err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n")
	buf.WriteString("\tbody, _ := io.ReadAll(resp.Body)\n")
	buf.WriteString("\tif resp.StatusCode >= 400 {\n")
	buf.WriteString("\t\treturn \"\", fmt.Errorf(\"%s.%s: status %d: %s\", service, operation, resp.StatusCode, string(body))\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn string(body), nil\n")
	buf.WriteString("}\n\n")

	// main function
	buf.WriteString("func main() {\n")
	buf.WriteString("\tinputJSON := \"\"\n")
	buf.WriteString("\tif len(os.Args) > 1 {\n")
	buf.WriteString("\t\tinputJSON = os.Args[1]\n")
	buf.WriteString("\t} else {\n")
	buf.WriteString("\t\tdata, err := io.ReadAll(os.Stdin)\n")
	buf.WriteString("\t\tif err == nil && len(data) > 0 {\n")
	buf.WriteString("\t\t\tinputJSON = strings.TrimSpace(string(data))\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")

	if concurrencyKey != "" {
		buf.WriteString("\t// Generate a unique workflow ID for concurrency key ownership.\n")
		buf.WriteString("\tworkflowID := fmt.Sprintf(\"dev-%d\", time.Now().UnixNano())\n\n")
	}

	buf.WriteString("\tcaller := &httpCaller{}\n")
	buf.WriteString("\trunner := localdev.NewLocalRunner(\n")
	buf.WriteString("\t\tlocaldev.WithServiceCaller(caller),\n")
	buf.WriteString("\t\tlocaldev.WithLogWriter(os.Stderr),\n")
	if concurrencyKey != "" {
		buf.WriteString("\t\tlocaldev.WithWorkflowID(workflowID),\n")
		fmt.Fprintf(&buf, "\t\tlocaldev.WithConcurrencyKey(%q),\n", concurrencyKey)
	}
	buf.WriteString("\t)\n")

	if concurrencyKey != "" {
		buf.WriteString("\n")
		buf.WriteString("\t// Acquire the concurrency key before executing the workflow.\n")
		buf.WriteString("\tacquired, err := runner.AcquireConcurrencyKey(")
		fmt.Fprintf(&buf, "%q, workflowID, localdev.ConcurrencyKeyTTL)\n", concurrencyKey)
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\tfmt.Fprintf(os.Stderr, \"error acquiring concurrency key: %v\\n\", err)\n")
		buf.WriteString("\t\tos.Exit(1)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif !acquired {\n")
		buf.WriteString("\t\tfmt.Fprintf(os.Stderr, \"concurrency key ")
		fmt.Fprintf(&buf, "%s already held by another workflow\\n\")\n", concurrencyKey)
		buf.WriteString("\t\tos.Exit(1)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tdefer runner.ReleaseConcurrencyKeys(workflowID)\n")
	}

	buf.WriteString("\th := runner.H()\n\n")

	// If there are params, generate parsing code
	hasParams := len(params) > 0

	if hasParams {
		// Generate struct type for JSON unmarshaling
		buf.WriteString("\ttype devArgs struct {\n")
		for _, p := range params {
			fmt.Fprintf(&buf, "\t\t%s %s `json:\"%s\"`\n", p.Name, p.TypeStr, p.JSONTag)
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tvar args devArgs\n")
		buf.WriteString("\tif inputJSON != \"\" {\n")
		buf.WriteString("\t\tif err := json.Unmarshal([]byte(inputJSON), &args); err != nil {\n")
		buf.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"error parsing input: %%v\\n\", err)\n")
		buf.WriteString("\t\t\tos.Exit(1)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t}\n\n")
	}

	// Generate function call with appropriate return handling
	callArgs := "h"
	for _, p := range params {
		callArgs += ", args." + p.Name
	}

	switch kind {
	case returnStringError:
		fmt.Fprintf(&buf, "\tresult, err := %s.%s(%s)\n", pkgName, funcName, callArgs)
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\temitError(runner, err)\n")
		buf.WriteString("\t\tos.Exit(1)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\temitResult(runner, result)\n")
	case returnError:
		fmt.Fprintf(&buf, "\terr := %s.%s(%s)\n", pkgName, funcName, callArgs)
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\temitError(runner, err)\n")
		buf.WriteString("\t\tos.Exit(1)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\temitResult(runner, \"ok\")\n")
	case returnString:
		fmt.Fprintf(&buf, "\tresult := %s.%s(%s)\n", pkgName, funcName, callArgs)
		buf.WriteString("\temitResult(runner, result)\n")
	default: // returnNothing
		fmt.Fprintf(&buf, "\t%s.%s(%s)\n", pkgName, funcName, callArgs)
		buf.WriteString("\temitResult(runner, \"ok\")\n")
	}

	buf.WriteString("}\n\n")

	// Helper functions
	buf.WriteString("func emitError(runner *localdev.LocalRunner, err error) {\n")
	buf.WriteString("\tjson.NewEncoder(os.Stdout).Encode(map[string]interface{}{\n")
	buf.WriteString("\t\t\"error\": err.Error(),\n")
	buf.WriteString("\t\t\"events\": runner.Events(),\n")
	buf.WriteString("\t})\n")
	buf.WriteString("}\n\n")
	buf.WriteString("func emitResult(runner *localdev.LocalRunner, result interface{}) {\n")
	buf.WriteString("\tjson.NewEncoder(os.Stdout).Encode(map[string]interface{}{\n")
	buf.WriteString("\t\t\"result\": result,\n")
	buf.WriteString("\t\t\"events\": runner.Events(),\n")
	buf.WriteString("\t})\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// runDev implements the "cleat dev" command.

func runDev(args []string) {
	var entryPointName string
	var inputJSON string
	var concurrencyKey string
	watch := false

	// Parse --flags before the package path.
	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "--entry-point" || args[i] == "-e":
			if i+1 < len(args) {
				entryPointName = args[i+1]
				args = append(args[:i], args[i+2:]...)
				i--
			}
		case args[i] == "--input" || args[i] == "-i":
			if i+1 < len(args) {
				inputJSON = args[i+1]
				args = append(args[:i], args[i+2:]...)
				i--
			}
		case strings.HasPrefix(args[i], "--input="):
			inputJSON = strings.TrimPrefix(args[i], "--input=")
			args = append(args[:i], args[i+1:]...)
			i--
		case strings.HasPrefix(args[i], "--entry-point="):
			entryPointName = strings.TrimPrefix(args[i], "--entry-point=")
			args = append(args[:i], args[i+1:]...)
			i--
		case args[i] == "--concurrency-key" || args[i] == "-c":
			if i+1 < len(args) {
				concurrencyKey = args[i+1]
				args = append(args[:i], args[i+2:]...)
				i--
			}
		case strings.HasPrefix(args[i], "--concurrency-key="):
			concurrencyKey = strings.TrimPrefix(args[i], "--concurrency-key=")
			args = append(args[:i], args[i+1:]...)
			i--
		case args[i] == "--watch" || args[i] == "-w":
			watch = true
			args = append(args[:i], args[i+1:]...)
			i--
		}
	}

	if len(args) < 1 {
		fmt.Fprintf(os.Stderr, "Usage: cleat dev [--input <json>] [--entry-point <name>] [--concurrency-key <key>] [--watch] <package>\n")
		fmt.Fprintf(os.Stderr, "Example: cleat dev --input '{\"userID\":\"u1\",\"cart\":[]}' ./testdata/basic/\n")
		os.Exit(1)
	}

	// If no --input was given, try reading from stdin (for pipeline usage).
	if inputJSON == "" {
		stat, _ := os.Stdin.Stat()
		if (stat.Mode() & os.ModeCharDevice) == 0 {
			// stdin is a pipe; read it.
			data, readErr := io.ReadAll(os.Stdin)
			if readErr == nil && len(data) > 0 {
				inputJSON = strings.TrimSpace(string(data))
			}
		}
	}

	pattern := args[0]

	if watch {
		runDevWithWatch(pattern, entryPointName, inputJSON, concurrencyKey)
		return
	}

	runDevOnce(pattern, entryPointName, inputJSON, concurrencyKey)
}

// runDevOnce performs a single dev cycle: analyze, generate, execute.
func runDevOnce(pattern, entryPointName, inputJSON, concurrencyKey string) {
	cmd, tmpPath, err := buildDevRun(pattern, entryPointName, inputJSON, concurrencyKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Running workflow...\n\n")
	runErr := cmd.Run()

	// Clean up the temp file before any exit.
	os.Remove(tmpPath)

	if runErr != nil {
		if exitErr, ok := runErr.(*exec.ExitError); ok {
			os.Exit(exitErr.ExitCode())
		}
		fmt.Fprintf(os.Stderr, "Error running workflow: %v\n", runErr)
		os.Exit(1)
	}
}

// runDevWithWatch watches the target package directory for .go file changes
// and automatically rebuilds and restarts the workflow runner.
func runDevWithWatch(pattern, entryPointName, inputJSON, concurrencyKey string) {
	// Resolve the target directory to watch. buildDevRun re-derives the module
	// directory for itself, so nothing is needed here beyond the watch root --
	// this used to bind and default a moduleDir that was never read again.
	targetDir := resolveDevTargetDir(pattern)

	// Set up fsnotify watcher.
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating file watcher: %v\n", err)
		os.Exit(1)
	}
	defer watcher.Close()

	// Walk target directory and watch all subdirectories.
	filepath.WalkDir(targetDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() && !strings.HasPrefix(d.Name(), ".") {
			if addErr := watcher.Add(path); addErr != nil {
				fmt.Fprintf(os.Stderr, "Warning: cannot watch %s: %v\n", path, addErr)
			}
		}
		return nil
	})

	fmt.Fprintf(os.Stderr, "Watching for changes in %s...\n\n", targetDir)

	// mu guards currentCmd and currentTmpPath. rebuildAndRun is invoked from a
	// time.AfterFunc goroutine, so two closely-spaced edits can overlap: both
	// read currentTmpPath, one wins the write, and the loser's generated file
	// is orphaned in the user's source tree with nothing left holding its path.
	// The signal handler below touches the same two variables from a third
	// goroutine.
	var mu sync.Mutex
	var currentCmd *exec.Cmd
	var currentTmpPath string
	var debounceTimer *time.Timer

	// Ctrl-C is how a watch session normally ends, and the deferred cleanup
	// below never runs on a signal -- so without this the generated runner is
	// left behind every single time. Exit 130 is the conventional shell status
	// for death by SIGINT.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-sigCh
		mu.Lock()
		if currentCmd != nil && currentCmd.Process != nil {
			currentCmd.Process.Kill()
		}
		if currentTmpPath != "" {
			os.Remove(currentTmpPath)
		}
		mu.Unlock()
		fmt.Fprintf(os.Stderr, "\nStopped.\n")
		os.Exit(130)
	}()

	// rebuildAndRun kills the current process (if any), re-analyzes,
	// regenerates, and starts a new runner.
	rebuildAndRun := func() {
		mu.Lock()
		defer mu.Unlock()

		if currentCmd != nil && currentCmd.Process != nil {
			currentCmd.Process.Kill()
			currentCmd.Wait()
		}
		if currentTmpPath != "" {
			os.Remove(currentTmpPath)
			currentTmpPath = ""
		}

		cmd, tmpPath, err := buildDevRun(pattern, entryPointName, inputJSON, concurrencyKey)
		if err != nil {
			fmt.Fprintf(os.Stderr, "\nBuild error: %v\n", err)
			fmt.Fprintf(os.Stderr, "Waiting for changes to retry...\n")
			return
		}

		currentCmd = cmd
		currentTmpPath = tmpPath

		fmt.Fprintf(os.Stderr, "Running workflow...\n\n")
		if err := cmd.Start(); err != nil {
			fmt.Fprintf(os.Stderr, "Error starting workflow: %v\n", err)
			os.Remove(tmpPath)
			currentTmpPath = ""
		}
	}

	// Initial build and run.
	rebuildAndRun()

	// Watch loop — rebuild on .go file changes with debounce.
	for {
		select {
		case event, ok := <-watcher.Events:
			if !ok {
				return
			}
			if !shouldRebuild(event.Name) {
				continue
			}
			if debounceTimer != nil {
				debounceTimer.Stop()
			}
			debounceTimer = time.AfterFunc(200*time.Millisecond, rebuildAndRun)

		case err, ok := <-watcher.Errors:
			if !ok {
				return
			}
			fmt.Fprintf(os.Stderr, "Watch error: %v\n", err)
		}
	}
}

// resolveDevTargetDir loads the target package (once) solely to determine the
// directory to watch.
func resolveDevTargetDir(pattern string) (targetDir string) {
	fset := token.NewFileSet()
	result, err := analyzer.LoadPackages(pattern, fset)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading package: %v\n", err)
		os.Exit(1)
	}
	return result.TargetPkg.Dir
}

// buildDevRun analyzes the package, selects the entry point, generates the
// runner code, writes a temp file, and returns an exec.Cmd ready to be
// started (or run). On failure it returns an error; the caller decides
// whether to retry or exit.
func buildDevRun(pattern, entryPointName, inputJSON, concurrencyKey string) (*exec.Cmd, string, error) {
	fset := token.NewFileSet()
	result, err := analyzer.LoadPackages(pattern, fset)
	if err != nil {
		return nil, "", fmt.Errorf("loading package: %w", err)
	}

	// Select the entry point.
	var funcName string
	if entryPointName != "" {
		found := false
		for _, ep := range result.EntryPoints {
			if analyzer.ShortName(ep) == entryPointName {
				funcName = ep
				found = true
				break
			}
		}
		if !found {
			names := make([]string, len(result.EntryPoints))
			for i, ep := range result.EntryPoints {
				names[i] = analyzer.ShortName(ep)
			}
			return nil, "", fmt.Errorf("entry point %q not found. Available: %s",
				entryPointName, strings.Join(names, ", "))
		}
	} else if len(result.EntryPoints) == 1 {
		funcName = result.EntryPoints[0]
	} else {
		var b strings.Builder
		b.WriteString("multiple entry points found. Use --entry-point to select one.\n")
		b.WriteString("Available entry points:\n")
		for _, ep := range result.EntryPoints {
			fmt.Fprintf(&b, "  %s\n", analyzer.ShortName(ep))
		}
		return nil, "", fmt.Errorf("%s", b.String())
	}

	fd := result.Funcs[funcName]
	if fd == nil {
		return nil, "", fmt.Errorf("function %q not found in analysis results", funcName)
	}

	params := buildParams(result, fd)
	kind, _ := classifyReturn(fd.Type)

	// Show what we are doing (to stderr).
	shortName := analyzer.ShortName(funcName)
	fmt.Fprintf(os.Stderr, "Workflow: %s.%s\n", result.TargetPkg.Name, shortName)
	fmt.Fprintf(os.Stderr, "Package:  %s\n", result.TargetPkg.Path)
	fmt.Fprintf(os.Stderr, "Module:   %s\n", result.ModulePath)
	if len(params) > 0 {
		fmt.Fprintf(os.Stderr, "Args:     ")
		for i, p := range params {
			if i > 0 {
				fmt.Fprintf(os.Stderr, ", ")
			}
			fmt.Fprintf(os.Stderr, "%s %s", p.JSONTag, p.TypeStr)
		}
		fmt.Fprintf(os.Stderr, "\n")
	}
	if concurrencyKey != "" {
		fmt.Fprintf(os.Stderr, "Concurrency: key=%s\n", concurrencyKey)
	}
	fmt.Fprintf(os.Stderr, "\n")

	// Generate the main.go source.
	src, err := generateDevMain(result, shortName, params, kind, concurrencyKey)
	if err != nil {
		return nil, "", fmt.Errorf("generating dev code: %w", err)
	}

	// Write a temp file inside the module directory so "go run" can resolve
	// the workflow package import via the module's go.mod.
	moduleDir := result.ModuleDir
	if moduleDir == "" {
		moduleDir = "."
	}

	tmpFile, err := os.CreateTemp(moduleDir, devGenPrefix+"*.go")
	if err != nil {
		return nil, "", fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmpFile.Name()

	if _, err := tmpFile.Write(src); err != nil {
		tmpFile.Close()
		os.Remove(tmpPath)
		return nil, "", fmt.Errorf("writing temp file: %w", err)
	}
	tmpFile.Close()

	// Create the "go run" command.
	cmd := exec.Command("go", "run", tmpPath)
	cmd.Dir = moduleDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if inputJSON != "" {
		cmd.Args = append(cmd.Args, inputJSON)
	}

	return cmd, tmpPath, nil
}
