package main

import (
	"bytes"
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"

	"github.com/cleat-team/cleat/migration"
)

// verify builds a database from the COMMITTED migrations, regenerates the
// baseline from it, and requires the regenerated files to be byte-identical to
// the ones in the tree.
//
// It exists because two guards were narrowed by cleat#2438 on the strength of
// the claim "this baseline is generated, so enumerating the policy list in it is
// not the hand-written list those guards forbid". That is a claim about the
// PROCESS, and until this mode existed nothing checked it of the ARTIFACT: a
// hand-edit to 001_schema.sql or 003_procedures.sql would have been undetectable,
// and the guards' justification would have been resting on a property the tree
// did not have. Named by cleat-review on the PR, which is where the distinction
// between "generated by construction" and "verified to be generated" was drawn.
//
// What it catches, and what it does not:
//
//   - A hand-edit in any style the emitter does not itself produce. The emitter
//     is deterministic -- tables alphabetically by schema then name, constraints
//     in four separate passes, plain identifiers, one clause per predicate row --
//     so an edit that survives this check has to reproduce all of that exactly.
//     In practice that means the check catches every hand-edit.
//   - An edit to the EMITTER that was not followed by a regeneration.
//   - It does NOT catch an edit that happens to be byte-identical to what the
//     emitter would emit, because such an edit is not a difference: the file
//     would then be exactly what the generator produces, which is the state
//     this mode asserts.
//
// 002_defaults.sql is exempt by construction: it is hand-assembled, because the
// rows a migration inserts are not recoverable from a catalogue read. The mode
// says so rather than silently skipping it.
//
// baselineFiles are the three files the generator owns, named explicitly so the
// build cannot pick up anything added after the baseline was cut.
var baselineFiles = []string{"001_schema.sql", "002_defaults.sql", "003_procedures.sql"}

// The database passed to -dsn must be EMPTY. verify builds into it, so pointing
// it at an existing database would compare the emitter's output for that
// database against the committed baseline for a different one.
func verify(ctx context.Context, db *sql.DB, committed string) error {
	// The empty-database precondition, ASSERTED rather than described.
	//
	// Pointing verify at a populated database compares the emitter's output for
	// that database against the committed baseline for a different one, and
	// reports a difference that means nothing -- a number that looks like a
	// finding. The CI step works around it by creating its own scratch
	// database, but nothing stopped a caller from not doing that, and the only
	// statement of the requirement was a comment.
	//
	// The assertion is here rather than only in the comment because this file
	// is the template for the PostgreSQL and MySQL verify modes: a comment does
	// not survive being copied into another dialect, and an assertion does.
	// Raised by cleat-review on cleat#2438.
	var dbName string
	var existing int
	if err := db.QueryRowContext(ctx, `SELECT DB_NAME()`).Scan(&dbName); err != nil {
		return fmt.Errorf("read the target database name: %w", err)
	}
	if err := db.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM sys.tables
		WHERE is_ms_shipped = 0 AND name <> 'schema_migrations'`).Scan(&existing); err != nil {
		return fmt.Errorf("probe %q for existing tables: %w", dbName, err)
	}
	if existing != 0 {
		return fmt.Errorf(
			"verify needs an EMPTY database and %q already holds %d user table(s). It BUILDS "+
				"into the database it is given, so a populated one would compare this database's "+
				"emit against the committed baseline for another. Create a scratch database first",
			dbName, existing)
	}

	// Build from the BASELINE FILES BY NAME, never from the migrations
	// directory.
	//
	// The runner applies every numbered file in the dialect directory, and emit
	// reads the live catalogue -- so building from `migrations` would fold the
	// first future 004_*.sql into the regenerated 001, and this check would
	// fail on a CORRECT tree, pointing at the generator when the cause is a
	// legitimate migration. The convention says the next core change IS a new
	// numbered file and that re-baselining is not per-change, so that is the
	// first thing anyone following the convention would hit. A guard that goes
	// red the first time someone does the right thing is worse than no guard,
	// because it teaches people to ignore it.
	//
	// The check's subject is "is the committed 001 exactly what the generator
	// produces", so the database it verifies against must be the baseline
	// alone. Found by WS-1 reading this file before mirroring it for PostgreSQL.
	staged, err := os.MkdirTemp("", "gen-mssql-baseline-verify-src-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(staged)
	stagedDir := filepath.Join(staged, string(migration.DialectMSSQL))
	if err := os.MkdirAll(stagedDir, 0o755); err != nil {
		return err
	}
	for _, name := range baselineFiles {
		b, err := os.ReadFile(filepath.Join(committed, name))
		if err != nil {
			return fmt.Errorf("read committed %s: %w", name, err)
		}
		if err := os.WriteFile(filepath.Join(stagedDir, name), b, 0o644); err != nil {
			return err
		}
	}
	if err := build(ctx, db, staged); err != nil {
		return fmt.Errorf("build from the committed baseline: %w", err)
	}

	tmp, err := os.MkdirTemp("", "gen-mssql-baseline-verify-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	if err := emit(ctx, db, tmp); err != nil {
		return fmt.Errorf("regenerate: %w", err)
	}

	// The two generated files. 002 is hand-assembled and is not compared.
	generated := []string{"001_schema.sql", "003_procedures.sql"}
	differing := 0
	for _, name := range generated {
		want, err := os.ReadFile(filepath.Join(tmp, name))
		if err != nil {
			return fmt.Errorf("read regenerated %s: %w", name, err)
		}
		have, err := os.ReadFile(filepath.Join(committed, name))
		if err != nil {
			return fmt.Errorf("read committed %s: %w", name, err)
		}
		if bytes.Equal(want, have) {
			fmt.Printf("identical   %s\n", filepath.Join(committed, name))
			continue
		}
		differing++
		fmt.Printf("DIFFERS     %s\n", filepath.Join(committed, name))
		fmt.Printf("            the committed file is not what the emitter produces from a\n")
		fmt.Printf("            database built from it. Either it was hand-edited, or the\n")
		fmt.Printf("            emitter changed without a regeneration.\n")
		fmt.Printf("            %s\n", firstDifference(have, want))
	}

	fmt.Printf("\n002_defaults.sql is hand-assembled by design and is not compared\n")
	if differing != 0 {
		return fmt.Errorf("%d of %d generated file(s) differ from a fresh emit", differing, len(generated))
	}
	fmt.Printf("verify: the committed baseline is exactly what the emitter produces\n")
	return nil
}

// firstDifference names the first differing line, so a failure points at
// something to look at rather than only at a byte count.
func firstDifference(have, want []byte) string {
	hl := bytes.Split(have, []byte("\n"))
	wl := bytes.Split(want, []byte("\n"))
	for i := 0; i < len(hl) && i < len(wl); i++ {
		if !bytes.Equal(hl[i], wl[i]) {
			return fmt.Sprintf("first difference at line %d:\n              committed: %s\n              emitted:   %s",
				i+1, truncate(hl[i]), truncate(wl[i]))
		}
	}
	return fmt.Sprintf("the shorter file ends first (committed %d line(s), emitted %d)", len(hl), len(wl))
}

func truncate(b []byte) string {
	const max = 120
	s := string(b)
	if len(s) > max {
		return s[:max] + "..."
	}
	return s
}
