-- Migration 005: Prepare columns for encryption at rest.
-- This migration ensures columns are TEXT type to accommodate encrypted
-- (base64-encoded) event payloads. The existing JSONB columns are altered
-- to TEXT when encryption is enabled so that encrypted values can be stored.
--
-- Encryption uses AES-256-GCM at the application layer with base64-encoded
-- output. No pgcrypto extension functions are needed.
--
-- NOTE: This migration is a no-op if columns are already TEXT-typed.
-- Run this before enabling --encrypt-sensitive-payloads.
--
-- The payload column on event_history is currently JSONB. When encryption
-- is enabled, encrypted payloads are stored as JSON string literals
-- ("base64_ciphertext") which are valid JSONB values. No type change is
-- needed for this column as JSONB can store string literals.
--
-- No schema changes required for the current encryption approach.
-- This migration serves as documentation and a hook for future use.
SELECT 1;
