-- cleat#1488.
-- cleat.assert_tenant_set() is VOLATILE, and nothing chose that: it is what
-- plpgsql gives a function that names no volatility. The consequence is not a
-- correctness bug, which is why it has survived thirty-four migrations -- it is
-- that EVERY RLS policy in this schema is built on a call the planner is
-- forbidden to optimise.
--
-- All thirteen core policies are the same shape:
--
--     USING (tenant_id = cleat.assert_tenant_set())
--
-- A VOLATILE function may not be used in an index condition and may not be
-- hoisted, so that predicate can only ever run as a per-row filter after the
-- heap is read. The schema carries a tenant_id-leading index on every one of
-- those tables -- idx_instances_tenant_status_created, idx_defs_tenant_name_version,
-- idx_event_history_tenant_wf and the rest -- and the tenant isolation predicate
-- cannot reach any of them.
--
-- MEASURED 2026-09-13, PostgreSQL 16, on a freshly migrated database with
-- 200,000 workflow_instances across 200 tenants, read by a non-superuser,
-- non-BYPASSRLS role. Each configuration run twice, and the whole pair run
-- again in the opposite order; the plans and the times were identical both
-- ways, so this is not a cache-warming artefact.
--
--   (a) a query carrying no tenant predicate of its own
--         VOLATILE  Seq Scan                                 97-105 ms
--         STABLE    Index Only Scan (idx_instances_created_at) 0.17-0.24 ms
--
--   (b) SELECT id ... WHERE tenant_id = $1 AND status = 'done'
--       ORDER BY created_at DESC LIMIT 50   -- the ordinary store path
--         VOLATILE  Bitmap Heap Scan, 1000 rows fetched then sorted  0.80-1.30 ms
--         STABLE    Index Scan (idx_instances_tenant_status_created),
--                   50 rows read                                    0.026-0.032 ms
--
-- (b) is the row worth reading twice, and it is the opposite of what I predicted.
-- The engine's own SQL already carries `tenant_id = $1`, so the obvious guess is
-- that the index is reached from the application predicate and the policy merely
-- adds a filter. It is not: under VOLATILE the planner abandons the ordered
-- (tenant_id, status, created_at DESC) index entirely, materialises all 1000
-- matching rows through a bitmap scan and sorts them to satisfy the LIMIT. The
-- volatile qual has to be evaluated on every candidate row, so an ordered index
-- walk cannot stop early. Marking the function STABLE restores the ordered scan
-- and it reads exactly the fifty rows asked for.
--
-- Re-derive:
--   psql -c 'ALTER FUNCTION cleat.assert_tenant_set() VOLATILE'   -- or STABLE
--   EXPLAIN (ANALYZE, TIMING OFF, COSTS OFF)
--     SELECT id FROM workflow_instances WHERE tenant_id = $1 AND status = 'done'
--     ORDER BY created_at DESC LIMIT 50;
--
-- WHY STABLE IS CORRECT, not merely faster. STABLE promises the function returns
-- the same result for the same arguments within a single statement. This function
-- takes no arguments and reads one GUC, cleat.tenant_id, which the engine sets
-- per transaction via set_config(..., true) before it issues any statement. A GUC
-- cannot change part-way through one statement, so the promise holds. current_setting
-- is itself marked STABLE in pg_catalog, which is the same judgement one level down.
--
-- What STABLE does NOT permit is worth stating, because it is the thing that would
-- be a security bug: it does not cache across statements. Measured, one transaction,
-- three statements, tenant changed between each -- A sees 2 rows, B sees 1, A sees 2
-- again -- identical under VOLATILE and under STABLE. And an unset tenant still
-- RAISES under STABLE; that control ran first, because a policy that stopped
-- refusing would look exactly like a policy that got faster.
--
-- cleat.tenant_row_is_visible is already declared STABLE (migration 063) and calls
-- this function, so the tree was already inconsistent: a STABLE function whose body
-- calls a VOLATILE one is making a promise its callee does not. PostgreSQL does not
-- check that, it just declines to inline. This migration makes the declaration true.
--
-- ALTER FUNCTION rather than CREATE OR REPLACE, deliberately. The body is not
-- changing and 034 is the file that should be read for what it does; re-stating it
-- here would give this repository two copies of a RAISE to keep in step, which is
-- the drift 065's header describes from the other direction.
ALTER FUNCTION cleat.assert_tenant_set() STABLE;
