-- Drop idx_instances_input_gin: no query in the codebase uses it, and it costs
-- 66% on every workflow start.
--
-- WHY THIS IS NOT SIMPLY REVERSING A MISTAKE. Migration 033 kept this index
-- deliberately and said why: `@>` containment is "the query this data shape is
-- actually suited to ... the narrower query operators should be pointed at
-- instead of a free-text ILIKE scan over serialized JSON". That reasoning is
-- sound and is not being disputed. What it did not include was a cost.
--
-- MEASURED on PostgreSQL 16, 20,000 rows with a representative payload
-- (an id, a small array, and a 300-byte note):
--
--     insert 20,000 rows WITH the GIN index     127.6 ms
--     insert 20,000 rows WITHOUT it              76.8 ms
--     index size                               3208 kB against an 8424 kB table
--
-- 66% slower inserts and 38% size overhead, paid by every deployment. `input`
-- is written once at workflow start and never updated, so the cost lands
-- entirely on the start path -- which is the hot one.
--
-- AND NOTHING READS IT. `grep -rn '@>' --include='*.go'` across the tree
-- returns no query against workflow_instances.input; the only hits are in
-- plugins/blobstore against unrelated tables. The index has been maintained on
-- every start since 001 and has never served a read.
--
-- SO THE TRADE IS: a certain cost on every deployment against a hypothetical
-- benefit for an operator writing containment queries by hand. An operator who
-- wants that can have it back in one statement, with the numbers above to
-- decide on:
--
--     CREATE INDEX CONCURRENTLY idx_instances_input_gin
--         ON workflow_instances USING GIN (input jsonb_path_ops);
--
-- That is the right way round: a deployment that needs it opts in, rather than
-- every deployment paying for a query most never write.
--
-- If cleat later exposes containment filtering through the API -- the shape
-- discussed for query_state in cleat#1571 -- this comes back WITH its reader,
-- and then it is not speculative.

DROP INDEX IF EXISTS idx_instances_input_gin;
