-- cleat migration 100 (postgres): a swept history leaves a marker
--
-- cleat#2038. DeleteExpiredEvents' event arm (--retention-days, default 30,
-- on by default) unconditionally deletes a terminal workflow's event_history,
-- with no per-row check for a call whose intent was written but never
-- resolved (engine/callintent.go's WriteAheadIntent semantics). ReReplay's
-- pending-intent guard (engine/admin_ops.go) reads that now-empty history and
-- cannot tell "this call was never attempted" from "this call's outcome was
-- swept before it could be recorded" -- both read as zero rows. cleat#1999's
-- TLA+ model (specs/CleatDurableCallIntent.tla) found and traced this as a
-- real S1 violation: sweep, then re-replay, then a silent unwitnessed
-- redispatch.
--
-- history_swept_at is the guard's missing signal. DeleteExpiredEvents sets it
-- on every workflow whose event_history it deletes, in the same sweep. The
-- guard then reads: empty history AND history_swept_at IS NULL -> never
-- attempted, allow (today's behaviour, unchanged). Empty history AND
-- history_swept_at IS NOT NULL -> swept, cannot tell if a call was left
-- pending, refuse.
--
-- NULLABLE, WITH NO BACKFILL, AND THE GAP THAT LEAVES IS STATED RATHER THAN
-- HIDDEN. A workflow whose history was ALREADY swept by a run of
-- DeleteExpiredEvents before this migration lands has no record of that
-- sweep -- nothing recorded it, the same way 099's worker_id backfill gap
-- has nothing to recover for a pre-migration queue_holders row. Such a
-- workflow reads history_swept_at IS NULL exactly like "never attempted" and
-- is NOT protected by this fix, even though its history is genuinely gone.
-- There is no query that recovers this: the fact this migration exists to
-- record was never captured anywhere. Only sweeps that run AFTER this
-- migration lands are covered.
--
-- Retention semantics are UNCHANGED: DeleteExpiredEvents still deletes
-- exactly the rows engine/retention_predicates.go's pgExpiredEventsWorkflows
-- predicate already matched. This column adds bookkeeping alongside that
-- delete, the same shape ClearExpiredCompactionState's existing
-- compaction_state/compaction_step/compacted_at UPDATE already is -- a
-- second, separate write next to the sweep, not a change to what the sweep
-- removes.

ALTER TABLE workflow_instances
    ADD COLUMN IF NOT EXISTS history_swept_at TIMESTAMPTZ;
