// Code generated by durable-gen. DO NOT EDIT.

package payments

import "github.com/rcownie/durable/durable"

type ChargeRequest struct {
	UserID      string `json:"user_id"`
	AmountCents int    `json:"amount_cents"`
	Currency    string `json:"currency"`
}

type ChargeResponse struct {
	ChargeID string `json:"charge_id"`
	Status   string `json:"status"`
}

type RefundRequest struct {
	ChargeID string `json:"charge_id"`
}

type Client struct {
	h durable.HostCalls
}

func NewClient(h durable.HostCalls) *Client {
	return &Client{h: h}
}

func (c *Client) Charge(req ChargeRequest) (*ChargeResponse, error) {
	var resp ChargeResponse
	if err := c.h.DurableCallTyped("payments", "Charge", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *Client) Refund(req RefundRequest) error {
	return c.h.DurableCallTyped("payments", "Refund", req, nil)
}
