package wasm

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"

	"github.com/cleat-team/cleat/internal/analyzer"
)

// GenerateExports produces the content of gen_wasm_exports.go.
// When target is "go", complex parameter types are deserialized via
// encoding/json instead of the manual extractJSONString fallback.
func GenerateExports(pkgName string, result *analyzer.AnalysisResult, target string) []byte {
	var buf bytes.Buffer

	buf.WriteString("//go:build wasip1\n\n")
	buf.WriteString("// Code generated by cleat build. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	needsJSON := hasComplexParams(result)

	buf.WriteString("import (\n")
	if needsJSON {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString("\t\"unsafe\"\n")
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/cleat-team/cleat/cleat\"\n")
	buf.WriteString(")\n\n")

	// Helper: extract a quoted JSON string value for a given key.
	buf.WriteString(`func extractJSONString(raw, key string) string {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return ""
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	if len(rest) == 0 || rest[0] != '"' {
		return ""
	}
	var buf []byte
	for i := 1; i < len(rest); i++ {
		c := rest[i]
		if c == '\\' && i+1 < len(rest) {
			i++
			switch rest[i] {
			case 'n':
				buf = append(buf, '\n')
			case 't':
				buf = append(buf, '\t')
			case 'r':
				buf = append(buf, '\r')
			case '"':
				buf = append(buf, '"')
			case '\\':
				buf = append(buf, '\\')
			case '/':
				buf = append(buf, '/')
			default:
				buf = append(buf, rest[i])
			}
			continue
		}
		if c == '"' {
			return string(buf)
		}
		buf = append(buf, c)
	}
	return ""
}

`)

	// Helper: extract an integer value for a given key.
	buf.WriteString(`func extractJSONInt(raw, key string) int {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return 0
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	n := 0
	for _, c := range rest {
		if c >= '0' && c <= '9' {
			n = n*10 + int(c-'0')
		} else {
			break
		}
	}
	return n
}

`)

	if needsJSON {
		// extractJSONRaw extracts the raw JSON text for a key, handling
		// objects, arrays, strings, numbers, and literals. Used as input
		// to json.Unmarshal for complex parameter types.
		buf.WriteString(`func extractJSONRaw(raw, key string) string {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return ""
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	if len(rest) == 0 {
		return ""
	}
	c := rest[0]
	switch c {
	case '"':
		// Return the quoted string including quotes.
		return ` + "`\"`" + ` + extractJSONString(raw, key) + ` + "`\"`" + `
	case '[':
		return extractBalanced(rest, '[', ']')
	case '{':
		return extractBalanced(rest, '{', '}')
	case 't', 'f':
		end := 0
		for end < len(rest) && rest[end] >= 'a' && rest[end] <= 'z' {
			end++
		}
		return rest[:end]
	case 'n':
		return "null"
	default:
		end := 0
		for end < len(rest) && rest[end] != ',' && rest[end] != '}' && rest[end] != ']' && rest[end] != ' ' && rest[end] != '\t' && rest[end] != '\n' && rest[end] != '\r' {
			end++
		}
		return strings.TrimSpace(rest[:end])
	}
}

func extractBalanced(s string, open, close byte) string {
	if len(s) == 0 || s[0] != open {
		return ""
	}
	depth := 0
	inString := false
	escaped := false
	for i, c := range s {
		if escaped {
			escaped = false
			continue
		}
		if c == '\\' && inString {
			escaped = true
			continue
		}
		if c == '"' {
			inString = !inString
			continue
		}
		if inString {
			continue
		}
		if byte(c) == open {
			depth++
		} else if byte(c) == close {
			depth--
			if depth == 0 {
				return s[:i+1]
			}
		}
	}
	return ""
}

`)
	}

	// writeJSONOut wraps a string as a JSON string value and copies it to the
	// output buffer. The input is the raw string content; it gets wrapped in
	// quotes with internal " and \ characters escaped.
	buf.WriteString(`func writeJSONOut(outPtr unsafe.Pointer, maxLen uint32, v interface{}) int64 {
	s := v.(string)
	var buf []byte
	buf = append(buf, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' || c == '\\' {
			buf = append(buf, '\\')
		}
		buf = append(buf, c)
	}
	buf = append(buf, '"')
	outLen := uint32(len(buf))
	if outLen > maxLen {
		return writeErrorOut(outPtr, maxLen,
			fmt.Errorf("response size %d exceeds buffer capacity %d", outLen, maxLen))
	}
	if outLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(outLen))
		copy(dst, buf)
	}
	return int64(outLen) << 32 // errCode = 0
}

// writeErrorOut writes an error message to the output buffer.
func writeErrorOut(outPtr unsafe.Pointer, maxLen uint32, err error) int64 {
	msg := err.Error()
	msgLen := uint32(len(msg))
	if msgLen > maxLen {
		msgLen = maxLen
	}
	if msgLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(msgLen))
		copy(dst, msg)
	}
	return (int64(msgLen) << 32) | 1
}

// writeSuspendOut returns a sentinel indicating the workflow suspended.
func writeSuspendOut() int64 {
	return 1 << 62
}

// encodeJSONString encodes a Go string as a JSON string (wraps in quotes,
// escapes " and \).
func encodeJSONString(s string) string {
	var buf []byte
	buf = append(buf, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' || c == '\\' {
			buf = append(buf, '\\')
		}
		buf = append(buf, c)
	}
	buf = append(buf, '"')
	return string(buf)
}

`)

	buf.WriteString(deferTableSource)

	qual := types.RelativeTo(result.TargetPkg.Types)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		generateExport(&buf, fd, qual, target)
	}

	// Only for a module that has workflows. A package with no entry points can
	// register no defers, so a runner for them would be an export with nothing
	// to run -- and TestGenerateExportsEmptyEntryPoints pins the broader
	// invariant that such a package produces no callable surface at all.
	if len(result.EntryPoints) > 0 {
		buf.WriteString(deferRunnerExportSource)
	}

	// The wasmtime backend calls _start which calls main(), which uses
	// cleat_poll_work + cleatDispatch to route work to entry points.
	// The wazero backend calls exports directly. Both paths coexist.
	if target == GoTarget {
		generateDispatch(&buf, result, qual)
	}

	return buf.Bytes()
}

// deferTableSource is the guest-side defer registry, emitted into every
// gen_wasm_exports.go.
//
// A defer body registered with DurableDeferFunc is a closure in the memory of
// the instance that registered it. The host runs defers by invoking an export
// on a FRESH instance, so it cannot reach one: the closure is not there, and
// there is no name to call it by either -- the ID is minted by the host at
// runtime, and no export name can be built from it at compile time. That is
// IMPROVEMENT-PLAN 3.70, and it is why every defer in every Go WASM workflow
// did nothing.
//
// So the guest runs its own. The registering instance still has the closures
// when the entry point returns, and that is the moment a defer is for.
//
// Two things this does NOT do, both deliberate:
//
//   - It does not run on suspension. A suspended workflow has not exited; its
//     defers are still pending, and running them there would fire every
//     cleanup at the first sleep. The final segment replays the entry point,
//     which re-registers the same IDs, and runs them when it completes.
//   - It does not run for a workflow that never returns -- cancelled, failed
//     terminally, or killed by the fence. The guest is not executing then.
//     Those need a host-driven path, which needs replay, and is 3.35 phase 4.
//
// Re-running is possible in one case: a defer that itself suspends leaves the
// defers after it unrun, and on resume the whole set runs again from the top.
// Durable calls inside them replay from history rather than re-executing, so
// this is ordinary replay semantics, but a defer's non-durable side effects
// can repeat. Defers are at-least-once, like everything else here.
const deferTableSource = `var _cleatDeferIDs []string
var _cleatDeferFuncs = map[string]func(){}

// _cleatInDeferPhase is true while _cleatRunDeferred is draining the table.
//
// IMPROVEMENT-PLAN 3.35 phase 4. Two things a defer body must not do, both
// measured 2026-09-02 before they were blocked, and both producing a workflow
// that reported SUCCESS with a durable record that could not be honoured:
//
//   - registering another defer. The table is drained BEFORE the first body
//     runs -- it has to be, or a body that registers would extend the slice
//     being walked -- so a new registration lands in a table nobody walks
//     again. The host had already minted an ID and written a durable defer
//     event, so a completed workflow's history carried a pending defer that
//     nothing anywhere could run.
//   - ContinueAsNew. Worse: the host recorded a continue_as_new event AND the
//     wrapper reported the workflow's already-decided result. One history,
//     two contradictory terminal facts; the worker stores 'done' and the
//     continuation silently never happens.
//
// Both guards are checked BEFORE the host call, in the generated adapters.
// Checking after would leave the durable event behind, which is the defect.
var _cleatInDeferPhase bool

// _cleatDeferPhaseError is the refusal both guarded adapters return.
//
// A named type rather than errors.New or fmt.Errorf: this source is emitted
// into every generated module, and adding an import that a module might not
// otherwise need is how generated code stops compiling for workflows that do
// nothing wrong.
type _cleatDeferPhaseError struct{ what string }

func (e _cleatDeferPhaseError) Error() string {
	return "cleat: " + e.what + " is not allowed from inside a defer body: " +
		"the defer table is drained before the first body runs and the workflow's " +
		"result is already decided, so this would be recorded durably and never " +
		"taken (IMPROVEMENT-PLAN 3.35 phase 4)"
}

func _cleatErrInDeferPhase(what string) error {
	return _cleatDeferPhaseError{what: what}
}

// _cleatRegisterDefer records a defer body under the ID the host minted for
// it. Called from the DurableDeferFunc adapter in gen_host_adapter.go.
func _cleatRegisterDefer(deferID string, fn func()) {
	if fn == nil {
		return
	}
	if _, seen := _cleatDeferFuncs[deferID]; !seen {
		_cleatDeferIDs = append(_cleatDeferIDs, deferID)
	}
	_cleatDeferFuncs[deferID] = fn
}

// _cleatRunDeferred runs registered defer bodies in LIFO order, the order Go's
// own defer uses and the order the worker's host-side runDefers uses.
//
// The table is drained BEFORE the first body runs. A defer that registers
// another defer would otherwise extend the slice while it is being walked, and
// a defer that panics would otherwise be retried by any later caller.
//
// A panic in one defer does not stop the others and does not disturb the
// workflow's own result, which is already decided by the time this runs --
// except for cleat.SuspendSentinel, which is not an error. That one must reach
// the entry point wrapper so the segment suspends; swallowing it would
// complete a workflow the host has already recorded as suspended.
// The count it returns is best-effort and exists for the host's log line, not
// for control flow: a SuspendSentinel leaves through the panic above, so the
// caller sees no value at all in that case. The evidence that a defer really
// ran is the host calls it made, never this number.
func _cleatRunDeferred() (ran int) {
	ids := _cleatDeferIDs
	_cleatDeferIDs = nil

	// Cleared on every exit, including the SuspendSentinel repanic below:
	// leaving it set would make the next segment's first DurableDeferFunc
	// refuse.
	_cleatInDeferPhase = true
	defer func() { _cleatInDeferPhase = false }()
	for i := len(ids) - 1; i >= 0; i-- {
		fn := _cleatDeferFuncs[ids[i]]
		delete(_cleatDeferFuncs, ids[i])
		if fn == nil {
			continue
		}
		ran++
		func() {
			defer func() {
				if r := recover(); r != nil {
					if _, ok := r.(cleat.SuspendSentinel); ok {
						panic(r)
					}
				}
			}()
			fn()
		}()
	}
	return ran
}


`

// writeRunDeferred emits the call to _cleatRunDeferred that both entry point
// wrappers make once the entry point has finished.
//
// It runs on the error path as well as the success path -- a defer is for
// cleanup, and a workflow that failed is the case that most needs it -- but
// not on suspension, and it runs BEFORE the result is reported to the host, so
// anything a defer records lands inside the segment that ran it.
//
// A defer that suspends turns the whole segment into a suspension. Its result
// is discarded, which is correct: the entry point will run again on resume and
// produce it again.
func writeRunDeferred(buf *bytes.Buffer, indent string) {
	w := func(s string) { buf.WriteString(indent + s + "\n") }
	w("if !__susSuspended {")
	w("\tfunc() {")
	w("\t\tdefer func() {")
	w("\t\t\tif r := recover(); r != nil {")
	w("\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {")
	w("\t\t\t\t\t__susSuspended = true")
	w("\t\t\t\t}")
	w("\t\t\t}")
	w("\t\t}()")
	w("\t\t_cleatRunDeferred()")
	w("\t}()")
	w("}")
	buf.WriteString("\n")
}

func generateExport(buf *bytes.Buffer, fd *analyzer.FuncDecl, qual types.Qualifier, target string) {
	exportName := ToSnakeCase(fd.Name)
	sig := fd.Type

	params := sig.Params()
	type argField struct {
		GoName  string
		GoType  string
		JSONTag string
	}
	var fields []argField

	startIdx := 0
	if params != nil && params.Len() > 0 {
		if analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			p := params.At(i)
			fields = append(fields, argField{
				GoName:  capitalize(p.Name()),
				GoType:  types.TypeString(p.Type(), qual),
				JSONTag: p.Name(),
			})
		}
	}

	results := sig.Results()
	var hasResultValue, hasErrorReturn bool
	if results != nil {
		for i := 0; i < results.Len(); i++ {
			typeName := types.TypeString(results.At(i).Type(), qual)
			if typeName == "error" {
				hasErrorReturn = true
			} else {
				hasResultValue = true
			}
		}
	}

	fmt.Fprintf(buf, "//go:wasmexport %s\n", exportName)
	fmt.Fprintf(buf, "func %s(argsPtr unsafe.Pointer, argsLen uint32, outPtr unsafe.Pointer, maxOutLen uint32) int64 {\n", exportName)

	// Only declare argsJSON when something below consumes it. An entry point
	// whose only parameter is the HostCalls handle has no fields, so an
	// unconditional declaration is an unused variable -- which is a COMPILE
	// ERROR in Go, not a warning. The guest failed to build with
	// "declared and not used: argsJSON", pointing at generated code the author
	// never wrote.
	//
	// This survived because every fixture and example in the repo happens to
	// take an input parameter, so no test ever generated the zero-field case.
	// cleatDispatch below is not affected and never was: argsJSON is a
	// PARAMETER there, and an unused parameter is legal Go.
	if len(fields) > 0 {
		buf.WriteString("\targsJSON := readString(argsPtr, argsLen)\n")
	}
	if len(fields) == 1 && fields[0].GoType == "string" {
		// Single string parameter: pass the raw argsJSON directly.
		buf.WriteString(fmt.Sprintf("\t%s := argsJSON\n", fields[0].GoName))
	} else if len(fields) > 0 {
		for _, f := range fields {
			switch f.GoType {
			case "string":
				fmt.Fprintf(buf, "\t%s := extractJSONString(argsJSON, %q)\n", f.GoName, f.JSONTag)
			case "int", "int64", "int32":
				fmt.Fprintf(buf, "\t%s := extractJSONInt(argsJSON, %q)\n", f.GoName, f.JSONTag)
			default:
				fmt.Fprintf(buf, "\tvar %s %s\n", f.GoName, f.GoType)
				fmt.Fprintf(buf, "\tif err := json.Unmarshal([]byte(extractJSONRaw(argsJSON, %q)), &%s); err != nil {\n", f.JSONTag, f.GoName)
				fmt.Fprintf(buf, "\t\treturn writeErrorOut(outPtr, maxOutLen, fmt.Errorf(\"unmarshal %s: %%w\", err))\n", f.JSONTag)
				buf.WriteString("\t}\n")
			}
		}
	}

	buf.WriteString("\n\th := makeHostCalls()\n\n")

	// Declare captured result/suspend variables.
	buf.WriteString("\tvar __susResultJSON []byte\n")
	buf.WriteString("\tvar __susResultErr error\n")
	buf.WriteString("\t__susSuspended := false\n\n")

	// Wrap entry point call in recover for suspend handling.
	buf.WriteString("\tfunc() {\n")
	buf.WriteString("\t\tdefer func() {\n")
	buf.WriteString("\t\t\tif r := recover(); r != nil {\n")
	buf.WriteString("\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {\n")
	buf.WriteString("\t\t\t\t\t__susSuspended = true\n")
	buf.WriteString("\t\t\t\t\treturn\n")
	buf.WriteString("\t\t\t\t}\n")
	buf.WriteString("\t\t\t\tpanic(r)\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}()\n\n")

	// Build call arguments: start with "h" (HostCalls), then each field.
	var callArgs []string
	callArgs = append(callArgs, "h")
	for _, f := range fields {
		callArgs = append(callArgs, f.GoName)
	}

	if hasResultValue && hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__r, __e := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\tif __e != nil {\n")
		buf.WriteString("\t\t\t__susResultErr = __e\n")
		buf.WriteString("\t\t\treturn\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\t__susResultJSON = []byte(__r)\n")
	} else if hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__susResultErr = %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	} else if hasResultValue {
		fmt.Fprintf(buf, "\t\t__r := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\t__susResultJSON = []byte(__r)\n")
	} else {
		fmt.Fprintf(buf, "\t\t%s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	}

	buf.WriteString("\t}()\n\n")

	writeRunDeferred(buf, "\t")

	buf.WriteString("\tif __susSuspended {\n")
	buf.WriteString("\t\treturn writeSuspendOut()\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif __susResultErr != nil {\n")
	buf.WriteString("\t\terrStr := encodeJSONString(__susResultErr.Error())\n")
	buf.WriteString("\t\terrPtr, errLen := stringPtr(errStr)\n")
	buf.WriteString("\t\tcleatCompleteImport(1, errPtr, errLen)\n")
	buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, __susResultErr)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tresultStr := string(__susResultJSON)\n")
	buf.WriteString("\tresultPtr, resultLen := stringPtr(resultStr)\n")
	buf.WriteString("\tcleatCompleteImport(0, resultPtr, resultLen)\n")
	buf.WriteString("\treturn writeJSONOut(outPtr, maxOutLen, resultStr)\n")

	buf.WriteString("}\n\n")
}

// hasComplexParams returns true if any entry point has parameters that are
// not simple primitives (string, int, int32, int64).
func hasComplexParams(result *analyzer.AnalysisResult) bool {
	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		sig := fd.Type
		params := sig.Params()
		if params == nil {
			continue
		}
		startIdx := 0
		if params.Len() > 0 && analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			typeName := types.TypeString(params.At(i).Type(), types.RelativeTo(result.TargetPkg.Types))
			switch typeName {
			case "string", "int", "int32", "int64":
				continue
			default:
				return true
			}
		}
	}
	return false
}

// The dispatcher poll-loop model (main() -> cleatPollWork -> cleatDispatch)
// was removed. Each workflow execution gets a fresh WASM instance via direct
// export calls, eliminating both the parameter-envelope mismatch and the risk
// of state bleed between invocations violating determinism.

func ToSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(r + 32))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
func generateDispatch(buf *bytes.Buffer, result *analyzer.AnalysisResult, qual types.Qualifier) {
	buf.WriteString(`
// cleatDispatch routes an entry point call from the main() dispatcher.
// It parses argsJSON into typed parameters, calls the entry point, and
// returns the JSON-encoded result or error.
func cleatDispatch(entryName string, argsJSON []byte) []byte {
	// Unwrap DispatchWrapper envelope set by host: {"inputJSON":"<inner>"}.
	inner := extractJSONString(string(argsJSON), "inputJSON")
		if inner != "" {
			argsJSON = []byte(inner)
		}
	h := makeHostCalls()
	switch entryName {
`)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		sig := fd.Type
		params := sig.Params()
		var fields []struct {
			GoName  string
			GoType  string
			JSONTag string
		}
		startIdx := 0
		if params != nil && params.Len() > 0 {
			if analyzer.IsHostCallsType(params.At(0).Type()) {
				startIdx = 1
			}
			for i := startIdx; i < params.Len(); i++ {
				p := params.At(i)
				fields = append(fields, struct {
					GoName  string
					GoType  string
					JSONTag string
				}{
					GoName:  capitalize(p.Name()),
					GoType:  types.TypeString(p.Type(), qual),
					JSONTag: p.Name(),
				})
			}
		}

		results := sig.Results()
		var hasResultValue, hasErrorReturn bool
		if results != nil {
			for i := 0; i < results.Len(); i++ {
				typeName := types.TypeString(results.At(i).Type(), qual)
				if typeName == "error" {
					hasErrorReturn = true
				} else {
					hasResultValue = true
				}
			}
		}

		snakeName := ToSnakeCase(fd.Name)
		fmt.Fprintf(buf, "\tcase %q, %q:\n", fd.Name, snakeName)

		// Parse args from JSON. For single-string-param entry points,
		// pass the already-unwrapped argsJSON directly (the outer
		// DispatchWrapper was removed above).
		if len(fields) == 1 && fields[0].GoType == "string" {
			fmt.Fprintf(buf, "\t\t%s := string(argsJSON)\n", fields[0].GoName)
		} else {
			for _, f := range fields {
				switch f.GoType {
				case "string":
					fmt.Fprintf(buf, "\t\t%s := extractJSONString(string(argsJSON), %q)\n", f.GoName, f.JSONTag)
				case "int", "int64", "int32":
					fmt.Fprintf(buf, "\t\t%s := extractJSONInt(string(argsJSON), %q)\n", f.GoName, f.JSONTag)
				default:
					// Complex type: use json.Unmarshal.
					fmt.Fprintf(buf, "\t\tvar %s %s\n", f.GoName, f.GoType)
					fmt.Fprintf(buf, "\t\tif err := json.Unmarshal([]byte(extractJSONRaw(string(argsJSON), %q)), &%s); err != nil {\n", f.JSONTag, f.GoName)
					// encodeJSONString, not concatenation: a json.Unmarshal
					// error routinely contains quotes (`invalid character '"'`),
					// and an unescaped one here makes the result unstorable --
					// FinalizeWorkflowSegment then replaces it with {} and the
					// reason the call failed is gone. Same class as 3.22.
					fmt.Fprintf(buf, "\t\t\treturn []byte(`{\"error\":` + encodeJSONString(\"unmarshal %s: \" + err.Error()) + `}`)\n", f.JSONTag)
					buf.WriteString("\t\t}\n")
				}
			}
		}

		// Build call.
		var callArgs []string
		callArgs = append(callArgs, "h")
		for _, f := range fields {
			callArgs = append(callArgs, f.GoName)
		}
		argStr := strings.Join(callArgs, ", ")

		// Declare result variables OUTSIDE the closure so they're
		// accessible for result encoding after the closure ends.
		if hasResultValue {
			buf.WriteString("\t\tvar __r string\n")
		}
		buf.WriteString("\t\tvar __e error\n")
		buf.WriteString("\t\t__susSuspended := false\n")
		buf.WriteString("\t\tfunc() {\n")
		buf.WriteString("\t\t\tdefer func() {\n")
		buf.WriteString("\t\t\t\tif r := recover(); r != nil {\n")
		buf.WriteString("\t\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {\n")
		buf.WriteString("\t\t\t\t\t\t__susSuspended = true\n")
		buf.WriteString("\t\t\t\t\t\treturn\n")
		buf.WriteString("\t\t\t\t\t}\n")
		buf.WriteString("\t\t\t\t\t// Report the error via cleatCompleteImport\n")
		buf.WriteString("\t\t\t\t\t// before returning so the host can capture it.\n")
		buf.WriteString("\t\t\t\t\terrStr := encodeJSONString(fmt.Sprintf(\"%v\", r))\n")
		buf.WriteString("\t\t\t\t\terrPtr, errLen := stringPtr(errStr)\n")
		buf.WriteString("\t\t\t\t\tcleatCompleteImport(1, errPtr, errLen)\n")
		buf.WriteString("\t\t\t\t\t__e = fmt.Errorf(\"%v\", r)\n")
		buf.WriteString("\t\t\t\t}\n")
		buf.WriteString("\t\t\t}()\n")

		if hasResultValue && hasErrorReturn {
			fmt.Fprintf(buf, "\t\t\t__r, __e = %s(%s)\n", fd.Name, argStr)
			buf.WriteString("\t\t\tif __e != nil { panic(__e) }\n")
		} else if hasErrorReturn {
			fmt.Fprintf(buf, "\t\t\t__e = %s(%s)\n", fd.Name, argStr)
			buf.WriteString("\t\t\tif __e != nil { panic(__e) }\n")
		} else if hasResultValue {
			fmt.Fprintf(buf, "\t\t\t__r = %s(%s)\n", fd.Name, argStr)
		} else {
			fmt.Fprintf(buf, "\t\t\t%s(%s)\n", fd.Name, argStr)
		}

		buf.WriteString("\t\t}()\n")

		writeRunDeferred(buf, "\t\t")

		// Encode result.
		buf.WriteString("\t\tif __susSuspended {\n")
		buf.WriteString("\t\t\treturn []byte(`\"__cleat_suspended__\"`)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tif __e != nil {\n")
		// encodeJSONString already wraps its argument in quotes (see its
		// definition above), so the quotes go around the *key* only. Wrapping
		// its output again produced {"error":""msg""} -- doubled quotes, not
		// valid JSON -- and FinalizeWorkflowSegment replaces an unstorable
		// result with {}, so every error returned through this path was
		// dropped. See IMPROVEMENT-PLAN 3.22. The __r branch below has always
		// used the helper this way.
		buf.WriteString("\t\t\treturn []byte(\"{\\\"error\\\":\" + encodeJSONString(__e.Error()) + \"}\")\n")
		buf.WriteString("\t\t}\n")
		if hasResultValue {
			// Pass through, do NOT re-encode.
			//
			// The contract at the WASM boundary is that an entry point returns a
			// STRING CONTAINING A JSON-ENCODED OBJECT. There is no "object" to
			// return -- the boundary carries a length and a byte range -- so the
			// string IS the serialised form, not a value awaiting serialisation.
			//
			// This used to be encodeJSONString(__r), which quoted and escaped it,
			// turning {"ok":true} into "{\"ok\":true}". The generated suspend
			// wrapper above has always used []byte(__r); the two disagreed, so the
			// same workflow returning the same string produced a different result
			// shape depending on which wrapper ran. They now agree.
			buf.WriteString("\t\treturn []byte(__r)\n")
		} else {
			buf.WriteString("\t\treturn []byte(`\"ok\"`)\n")
		}

		// Variables needed by the generated code.
		buf.WriteString("\n")
	}

	// An entry point the guest does not recognise is a FAILURE, reported on the
	// error channel -- not a result that happens to contain the word "error".
	//
	// This used to `return []byte("{\"error\":\"unknown entry point: ...\"}")`,
	// which the main-stub dispatcher then handed to cleatCompleteImport(0, ...)
	// -- status 0, success. So the host could not tell an entry point the guest
	// had never heard of from one that ran and returned that JSON. Measured
	// 2026-09-01 on a real Go guest: RunDefer for a nonexistent export and for
	// a plausible-but-absent one returned byte-identical results, both with a
	// nil error, so every caller's `if err != nil` was dead code.
	//
	// That is how every defer in every Go WASM workflow came to do nothing
	// while the host recorded success: the host invokes defers by entry-point
	// name, and no guest exports one. IMPROVEMENT-PLAN 3.70.
	//
	// Returning nil tells the dispatcher the completion has already been
	// signalled, so it must not also report success.
	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")
}

// deferRunnerExportSource is the export the HOST calls to drain the defer
// table. Emitted only for modules that have entry points.
const deferRunnerExportSource = `
// __cleat_run_deferred lets the HOST drain the defer table, for the workflows
// that never reach the entry point wrapper that normally does it: a guest
// killed by the execution fence, by the instruction limit, or by an
// unrecoverable runtime failure such as out-of-memory. IMPROVEMENT-PLAN 3.35
// phase 4.
//
// It is safe to call on an instance that has already run its defers -- the
// table is drained, so a second call runs nothing and returns 0.
//
// The name cannot collide with a workflow's own entry point. Export names are
// ToSnakeCase of an EXPORTED Go identifier, so they always begin with a
// lowercase letter; no entry point can produce a leading underscore.
//
// Every panic is swallowed here, INCLUDING cleat.SuspendSentinel, which is the
// one _cleatRunDeferred deliberately lets through. That is right for this
// caller and wrong for the other one: the entry point wrapper needs the
// sentinel so its segment suspends, but a workflow reached through this export
// is already dead and has no segment left to suspend. Letting it out would
// turn the host's cleanup call into a trap.
//
//go:wasmexport __cleat_run_deferred
func __cleat_run_deferred() (ran int64) {
	defer func() {
		_ = recover()
	}()
	ran = int64(_cleatRunDeferred())
	return ran
}
`
