package wasm

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"

	"github.com/cleat-team/cleat/internal/analyzer"
)

// GenerateExports produces the content of gen_wasm_exports.go.
// When target is "go", complex parameter types are deserialized via
// encoding/json instead of the manual extractJSONString fallback.
func GenerateExports(pkgName string, result *analyzer.AnalysisResult, target string) []byte {
	var buf bytes.Buffer

	buf.WriteString("//go:build wasip1\n\n")
	buf.WriteString("// Code generated by cleat build. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	needsJSON := hasComplexParams(result)

	buf.WriteString("import (\n")
	if needsJSON {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString("\t\"unsafe\"\n")
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/cleat-team/cleat/cleat\"\n")
	buf.WriteString(")\n\n")

	// Helper: extract a quoted JSON string value for a given key.
	buf.WriteString(`func extractJSONString(raw, key string) string {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return ""
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	if len(rest) == 0 || rest[0] != '"' {
		return ""
	}
	var buf []byte
	for i := 1; i < len(rest); i++ {
		c := rest[i]
		if c == '\\' && i+1 < len(rest) {
			i++
			switch rest[i] {
			case 'n':
				buf = append(buf, '\n')
			case 't':
				buf = append(buf, '\t')
			case 'r':
				buf = append(buf, '\r')
			case '"':
				buf = append(buf, '"')
			case '\\':
				buf = append(buf, '\\')
			case '/':
				buf = append(buf, '/')
			default:
				buf = append(buf, rest[i])
			}
			continue
		}
		if c == '"' {
			return string(buf)
		}
		buf = append(buf, c)
	}
	return ""
}

`)

	// Helper: extract an integer value for a given key.
	buf.WriteString(`func extractJSONInt(raw, key string) int {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return 0
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	n := 0
	for _, c := range rest {
		if c >= '0' && c <= '9' {
			n = n*10 + int(c-'0')
		} else {
			break
		}
	}
	return n
}

`)

	if needsJSON {
		// extractJSONRaw extracts the raw JSON text for a key, handling
		// objects, arrays, strings, numbers, and literals. Used as input
		// to json.Unmarshal for complex parameter types.
		buf.WriteString(`func extractJSONRaw(raw, key string) string {
	search := "\"" + key + "\":"
	idx := strings.Index(raw, search)
	if idx < 0 {
		return ""
	}
	rest := raw[idx+len(search):]
	rest = strings.TrimLeft(rest, " \t\n\r")
	if len(rest) == 0 {
		return ""
	}
	c := rest[0]
	switch c {
	case '"':
		// Return the quoted string including quotes.
		return ` + "`\"`" + ` + extractJSONString(raw, key) + ` + "`\"`" + `
	case '[':
		return extractBalanced(rest, '[', ']')
	case '{':
		return extractBalanced(rest, '{', '}')
	case 't', 'f':
		end := 0
		for end < len(rest) && rest[end] >= 'a' && rest[end] <= 'z' {
			end++
		}
		return rest[:end]
	case 'n':
		return "null"
	default:
		end := 0
		for end < len(rest) && rest[end] != ',' && rest[end] != '}' && rest[end] != ']' && rest[end] != ' ' && rest[end] != '\t' && rest[end] != '\n' && rest[end] != '\r' {
			end++
		}
		return strings.TrimSpace(rest[:end])
	}
}

func extractBalanced(s string, open, close byte) string {
	if len(s) == 0 || s[0] != open {
		return ""
	}
	depth := 0
	inString := false
	escaped := false
	for i, c := range s {
		if escaped {
			escaped = false
			continue
		}
		if c == '\\' && inString {
			escaped = true
			continue
		}
		if c == '"' {
			inString = !inString
			continue
		}
		if inString {
			continue
		}
		if byte(c) == open {
			depth++
		} else if byte(c) == close {
			depth--
			if depth == 0 {
				return s[:i+1]
			}
		}
	}
	return ""
}

`)
	}

	// writeJSONOut wraps a string as a JSON string value and copies it to the
	// output buffer. The input is the raw string content; it gets wrapped in
	// quotes with internal " and \ characters escaped.
	buf.WriteString(`func writeJSONOut(outPtr unsafe.Pointer, maxLen uint32, v interface{}) int64 {
	s := v.(string)
	var buf []byte
	buf = append(buf, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' || c == '\\' {
			buf = append(buf, '\\')
		}
		buf = append(buf, c)
	}
	buf = append(buf, '"')
	outLen := uint32(len(buf))
	if outLen > maxLen {
		return writeErrorOut(outPtr, maxLen,
			fmt.Errorf("response size %d exceeds buffer capacity %d", outLen, maxLen))
	}
	if outLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(outLen))
		copy(dst, buf)
	}
	return int64(outLen) << 32 // errCode = 0
}

// writeErrorOut writes an error message to the output buffer.
func writeErrorOut(outPtr unsafe.Pointer, maxLen uint32, err error) int64 {
	msg := err.Error()
	msgLen := uint32(len(msg))
	if msgLen > maxLen {
		msgLen = maxLen
	}
	if msgLen > 0 {
		dst := unsafe.Slice((*byte)(outPtr), int(msgLen))
		copy(dst, msg)
	}
	return (int64(msgLen) << 32) | 1
}

// writeSuspendOut returns a sentinel indicating the workflow suspended.
func writeSuspendOut() int64 {
	return 1 << 62
}

// encodeJSONString encodes a Go string as a JSON string (wraps in quotes,
// escapes " and \).
func encodeJSONString(s string) string {
	var buf []byte
	buf = append(buf, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' || c == '\\' {
			buf = append(buf, '\\')
		}
		buf = append(buf, c)
	}
	buf = append(buf, '"')
	return string(buf)
}

`)

	qual := types.RelativeTo(result.TargetPkg.Types)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		generateExport(&buf, fd, qual, target)
	}

	// The wasmtime backend calls _start which calls main(), which uses
	// cleat_poll_work + cleatDispatch to route work to entry points.
	// The wazero backend calls exports directly. Both paths coexist.
	if target == GoTarget {
		generateDispatch(&buf, result, qual)
	}

	return buf.Bytes()
}

func generateExport(buf *bytes.Buffer, fd *analyzer.FuncDecl, qual types.Qualifier, target string) {
	exportName := ToSnakeCase(fd.Name)
	sig := fd.Type

	params := sig.Params()
	type argField struct {
		GoName  string
		GoType  string
		JSONTag string
	}
	var fields []argField

	startIdx := 0
	if params != nil && params.Len() > 0 {
		if analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			p := params.At(i)
			fields = append(fields, argField{
				GoName:  capitalize(p.Name()),
				GoType:  types.TypeString(p.Type(), qual),
				JSONTag: p.Name(),
			})
		}
	}

	results := sig.Results()
	var hasResultValue, hasErrorReturn bool
	if results != nil {
		for i := 0; i < results.Len(); i++ {
			typeName := types.TypeString(results.At(i).Type(), qual)
			if typeName == "error" {
				hasErrorReturn = true
			} else {
				hasResultValue = true
			}
		}
	}

	fmt.Fprintf(buf, "//go:wasmexport %s\n", exportName)
	fmt.Fprintf(buf, "func %s(argsPtr unsafe.Pointer, argsLen uint32, outPtr unsafe.Pointer, maxOutLen uint32) int64 {\n", exportName)

	buf.WriteString("\targsJSON := readString(argsPtr, argsLen)\n")
	if len(fields) == 1 && fields[0].GoType == "string" {
		// Single string parameter: pass the raw argsJSON directly.
		buf.WriteString(fmt.Sprintf("\t%s := argsJSON\n", fields[0].GoName))
	} else if len(fields) > 0 {
		for _, f := range fields {
			switch f.GoType {
			case "string":
				fmt.Fprintf(buf, "\t%s := extractJSONString(argsJSON, %q)\n", f.GoName, f.JSONTag)
			case "int", "int64", "int32":
				fmt.Fprintf(buf, "\t%s := extractJSONInt(argsJSON, %q)\n", f.GoName, f.JSONTag)
			default:
				fmt.Fprintf(buf, "\tvar %s %s\n", f.GoName, f.GoType)
				fmt.Fprintf(buf, "\tif err := json.Unmarshal([]byte(extractJSONRaw(argsJSON, %q)), &%s); err != nil {\n", f.JSONTag, f.GoName)
				fmt.Fprintf(buf, "\t\treturn writeErrorOut(outPtr, maxOutLen, fmt.Errorf(\"unmarshal %s: %%w\", err))\n", f.JSONTag)
				buf.WriteString("\t}\n")
			}
		}
	}

	buf.WriteString("\n\th := makeHostCalls()\n\n")

	// Declare captured result/suspend variables.
	buf.WriteString("\tvar __susResultJSON []byte\n")
	buf.WriteString("\tvar __susResultErr error\n")
	buf.WriteString("\t__susSuspended := false\n\n")

	// Wrap entry point call in recover for suspend handling.
	buf.WriteString("\tfunc() {\n")
	buf.WriteString("\t\tdefer func() {\n")
	buf.WriteString("\t\t\tif r := recover(); r != nil {\n")
	buf.WriteString("\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {\n")
	buf.WriteString("\t\t\t\t\t__susSuspended = true\n")
	buf.WriteString("\t\t\t\t\treturn\n")
	buf.WriteString("\t\t\t\t}\n")
	buf.WriteString("\t\t\t\tpanic(r)\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}()\n\n")

	// Build call arguments: start with "h" (HostCalls), then each field.
	var callArgs []string
	callArgs = append(callArgs, "h")
	for _, f := range fields {
		callArgs = append(callArgs, f.GoName)
	}

	if hasResultValue && hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__r, __e := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\tif __e != nil {\n")
		buf.WriteString("\t\t\t__susResultErr = __e\n")
		buf.WriteString("\t\t\treturn\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\t__susResultJSON = []byte(__r)\n")
	} else if hasErrorReturn {
		fmt.Fprintf(buf, "\t\t__susResultErr = %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	} else if hasResultValue {
		fmt.Fprintf(buf, "\t\t__r := %s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
		buf.WriteString("\t\t__susResultJSON = []byte(__r)\n")
	} else {
		fmt.Fprintf(buf, "\t\t%s(%s)\n", fd.Name, strings.Join(callArgs, ", "))
	}

	buf.WriteString("\t}()\n\n")

	buf.WriteString("\tif __susSuspended {\n")
	buf.WriteString("\t\treturn writeSuspendOut()\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif __susResultErr != nil {\n")
	buf.WriteString("\t\terrStr := encodeJSONString(__susResultErr.Error())\n")
	buf.WriteString("\t\terrPtr, errLen := stringPtr(errStr)\n")
	buf.WriteString("\t\tcleatCompleteImport(1, errPtr, errLen)\n")
	buf.WriteString("\t\treturn writeErrorOut(outPtr, maxOutLen, __susResultErr)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tresultStr := string(__susResultJSON)\n")
	buf.WriteString("\tresultPtr, resultLen := stringPtr(resultStr)\n")
	buf.WriteString("\tcleatCompleteImport(0, resultPtr, resultLen)\n")
	buf.WriteString("\treturn writeJSONOut(outPtr, maxOutLen, resultStr)\n")

	buf.WriteString("}\n\n")
}

// hasComplexParams returns true if any entry point has parameters that are
// not simple primitives (string, int, int32, int64).
func hasComplexParams(result *analyzer.AnalysisResult) bool {
	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		sig := fd.Type
		params := sig.Params()
		if params == nil {
			continue
		}
		startIdx := 0
		if params.Len() > 0 && analyzer.IsHostCallsType(params.At(0).Type()) {
			startIdx = 1
		}
		for i := startIdx; i < params.Len(); i++ {
			typeName := types.TypeString(params.At(i).Type(), types.RelativeTo(result.TargetPkg.Types))
			switch typeName {
			case "string", "int", "int32", "int64":
				continue
			default:
				return true
			}
		}
	}
	return false
}

// The dispatcher poll-loop model (main() -> cleatPollWork -> cleatDispatch)
// was removed. Each workflow execution gets a fresh WASM instance via direct
// export calls, eliminating both the parameter-envelope mismatch and the risk
// of state bleed between invocations violating determinism.

func ToSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(r + 32))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
func generateDispatch(buf *bytes.Buffer, result *analyzer.AnalysisResult, qual types.Qualifier) {
	buf.WriteString(`
// cleatDispatch routes an entry point call from the main() dispatcher.
// It parses argsJSON into typed parameters, calls the entry point, and
// returns the JSON-encoded result or error.
func cleatDispatch(entryName string, argsJSON []byte) []byte {
	// Unwrap DispatchWrapper envelope set by host: {"inputJSON":"<inner>"}.
	inner := extractJSONString(string(argsJSON), "inputJSON")
		if inner != "" {
			argsJSON = []byte(inner)
		}
	h := makeHostCalls()
	switch entryName {
`)

	for _, epName := range result.EntryPoints {
		fd := result.Funcs[epName]
		if fd == nil || fd.Type == nil {
			continue
		}
		sig := fd.Type
		params := sig.Params()
		var fields []struct {
			GoName  string
			GoType  string
			JSONTag string
		}
		startIdx := 0
		if params != nil && params.Len() > 0 {
			if analyzer.IsHostCallsType(params.At(0).Type()) {
				startIdx = 1
			}
			for i := startIdx; i < params.Len(); i++ {
				p := params.At(i)
				fields = append(fields, struct {
					GoName  string
					GoType  string
					JSONTag string
				}{
					GoName:  capitalize(p.Name()),
					GoType:  types.TypeString(p.Type(), qual),
					JSONTag: p.Name(),
				})
			}
		}

		results := sig.Results()
		var hasResultValue, hasErrorReturn bool
		if results != nil {
			for i := 0; i < results.Len(); i++ {
				typeName := types.TypeString(results.At(i).Type(), qual)
				if typeName == "error" {
					hasErrorReturn = true
				} else {
					hasResultValue = true
				}
			}
		}

		snakeName := ToSnakeCase(fd.Name)
		fmt.Fprintf(buf, "\tcase %q, %q:\n", fd.Name, snakeName)

		// Parse args from JSON. For single-string-param entry points,
		// pass the already-unwrapped argsJSON directly (the outer
		// DispatchWrapper was removed above).
		if len(fields) == 1 && fields[0].GoType == "string" {
			fmt.Fprintf(buf, "\t\t%s := string(argsJSON)\n", fields[0].GoName)
		} else {
			for _, f := range fields {
				switch f.GoType {
				case "string":
					fmt.Fprintf(buf, "\t\t%s := extractJSONString(string(argsJSON), %q)\n", f.GoName, f.JSONTag)
				case "int", "int64", "int32":
					fmt.Fprintf(buf, "\t\t%s := extractJSONInt(string(argsJSON), %q)\n", f.GoName, f.JSONTag)
				default:
					// Complex type: use json.Unmarshal.
					fmt.Fprintf(buf, "\t\tvar %s %s\n", f.GoName, f.GoType)
					fmt.Fprintf(buf, "\t\tif err := json.Unmarshal([]byte(extractJSONRaw(string(argsJSON), %q)), &%s); err != nil {\n", f.JSONTag, f.GoName)
					fmt.Fprintf(buf, "\t\t\treturn []byte(`{\"error\":\"unmarshal %s: ` + err.Error() + `\"}`)\n", f.JSONTag)
					buf.WriteString("\t\t}\n")
				}
			}
		}

		// Build call.
		var callArgs []string
		callArgs = append(callArgs, "h")
		for _, f := range fields {
			callArgs = append(callArgs, f.GoName)
		}
		argStr := strings.Join(callArgs, ", ")

		// Declare result variables OUTSIDE the closure so they're
		// accessible for result encoding after the closure ends.
		if hasResultValue {
			buf.WriteString("\t\tvar __r string\n")
		}
		buf.WriteString("\t\tvar __e error\n")
		buf.WriteString("\t\t__susSuspended := false\n")
		buf.WriteString("\t\tfunc() {\n")
		buf.WriteString("\t\t\tdefer func() {\n")
		buf.WriteString("\t\t\t\tif r := recover(); r != nil {\n")
		buf.WriteString("\t\t\t\t\tif _, ok := r.(cleat.SuspendSentinel); ok {\n")
		buf.WriteString("\t\t\t\t\t\t__susSuspended = true\n")
		buf.WriteString("\t\t\t\t\t\treturn\n")
		buf.WriteString("\t\t\t\t\t}\n")
		buf.WriteString("\t\t\t\t\t// Report the error via cleatCompleteImport\n")
		buf.WriteString("\t\t\t\t\t// before returning so the host can capture it.\n")
		buf.WriteString("\t\t\t\t\terrStr := encodeJSONString(fmt.Sprintf(\"%v\", r))\n")
		buf.WriteString("\t\t\t\t\terrPtr, errLen := stringPtr(errStr)\n")
		buf.WriteString("\t\t\t\t\tcleatCompleteImport(1, errPtr, errLen)\n")
		buf.WriteString("\t\t\t\t\t__e = fmt.Errorf(\"%v\", r)\n")
		buf.WriteString("\t\t\t\t}\n")
		buf.WriteString("\t\t\t}()\n")

		if hasResultValue && hasErrorReturn {
			fmt.Fprintf(buf, "\t\t\t__r, __e = %s(%s)\n", fd.Name, argStr)
			buf.WriteString("\t\t\tif __e != nil { panic(__e) }\n")
		} else if hasErrorReturn {
			fmt.Fprintf(buf, "\t\t\t__e = %s(%s)\n", fd.Name, argStr)
			buf.WriteString("\t\t\tif __e != nil { panic(__e) }\n")
		} else if hasResultValue {
			fmt.Fprintf(buf, "\t\t\t__r = %s(%s)\n", fd.Name, argStr)
		} else {
			fmt.Fprintf(buf, "\t\t\t%s(%s)\n", fd.Name, argStr)
		}

		buf.WriteString("\t\t}()\n")

		// Encode result.
		buf.WriteString("\t\tif __susSuspended {\n")
		buf.WriteString("\t\t\treturn []byte(`\"__cleat_suspended__\"`)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tif __e != nil {\n")
		buf.WriteString("\t\t\treturn []byte(\"{\\\"error\\\":\\\"\" + encodeJSONString(__e.Error()) + \"\\\"}\")\n")
		buf.WriteString("\t\t}\n")
		if hasResultValue {
			buf.WriteString("\t\treturn []byte(encodeJSONString(__r))\n")
		} else {
			buf.WriteString("\t\treturn []byte(`\"ok\"`)\n")
		}

		// Variables needed by the generated code.
		buf.WriteString("\n")
	}

	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\treturn []byte(`{\"error\":\"unknown entry point: ` + entryName + `\"}`)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")
}
