#!/usr/bin/env python3
"""Reference implementation of the audit-log hash chain (cleat#2047).

This is the CONTRACT for an offline verifier, and the second, independent
derivation the Go implementation is checked against: chain_vectors.json is
generated by this file, and plugins/auditlog/chain_test.go asserts the Go code
reproduces every hash in it. Two implementations written from the same prose
agreeing is evidence; one implementation agreeing with its own output is not.

    python3 audit_chain_reference.py generate > chain_vectors.json
    python3 audit_chain_reference.py verify   < chain_vectors.json

The hash of a row is

    SHA-256( DOMAIN || prev_hash(32 raw bytes) || field(tenant_id) || field(seq) || ... )

over the fields, in this order, each encoded as: one presence byte (0 = SQL NULL,
1 = present) and, when present, uvarint(len(bytes)) followed by the UTF-8 bytes.
Every field is text: integers are decimal, UUIDs are lowercase and hyphenated, the
timestamp is UTC to the microsecond as YYYY-MM-DDTHH:MM:SS.ffffffZ, and metadata is
canonical JSON (see canonical_json). prev_hash of a tenant's first row is 32 zero bytes.
"""
import hashlib
import json
import re
import sys
from datetime import datetime, timedelta, timezone

DOMAIN = b"cleat-audit-chain-v1\x00"
GENESIS = bytes(32)
FIELDS = ["tenant_id", "seq", "id", "timestamp", "method", "path", "status_code",
          "user_id", "ip_address", "user_agent", "duration_ms", "metadata"]


def uvarint(n):
    out = bytearray()
    while n >= 0x80:
        out.append((n & 0x7F) | 0x80)
        n >>= 7
    out.append(n)
    return bytes(out)


def field(v):
    if v is None:
        return b"\x00"
    b = v.encode("utf-8")
    return b"\x01" + uvarint(len(b)) + b


_TS = re.compile(r"^(\d{4})-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)(?:\.(\d{1,9}))?(Z|[+-]\d\d:\d\d)$")


def canonical_timestamp(s):
    m = _TS.match(s)
    if not m:
        raise ValueError("not an RFC 3339 timestamp: %r" % s)
    y, mo, d, h, mi, sec, frac, zone = m.groups()
    micro = int((frac or "").ljust(6, "0")[:6])  # truncated, never rounded
    dt = datetime(int(y), int(mo), int(d), int(h), int(mi), int(sec), micro, tzinfo=timezone.utc)
    if zone != "Z":
        sign = 1 if zone[0] == "+" else -1
        off = timedelta(hours=int(zone[1:3]), minutes=int(zone[4:6]))
        dt = dt - sign * off
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _escape(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif o < 0x20:
            out.append("\\u%04x" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


class _Num(str):
    pass


def _enc(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, _Num):
        return str(v)
    if isinstance(v, str):
        return _escape(v)
    if isinstance(v, list):
        return "[" + ",".join(_enc(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(_escape(k) + ":" + _enc(v[k]) for k in sorted(v)) + "}"
    raise TypeError(type(v))


def canonical_json(text):
    """Sorted keys (code point order), no whitespace, strings escaped only for
    the quote, the backslash and control characters below 0x20 (as \\u00xx, lower
    case hex), everything else verbatim, numbers as their original token."""
    v = json.loads(text, parse_int=_Num, parse_float=_Num)
    return _enc(v)


def canonical_fields(rec):
    vals = []
    for name in FIELDS:
        v = rec[name]
        if v is None:
            vals.append(None)
        elif name == "timestamp":
            vals.append(canonical_timestamp(v))
        elif name == "metadata":
            vals.append(canonical_json(v))
        else:
            vals.append(str(v))
    return vals


def row_hash(prev_hash, rec):
    h = hashlib.sha256()
    h.update(DOMAIN)
    h.update(prev_hash)
    for v in canonical_fields(rec):
        h.update(field(v))
    return h.digest()


def rec(**kw):
    base = dict(tenant_id="11111111-1111-1111-1111-111111111111", seq=1,
                id="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                timestamp="2026-09-24T01:02:03.456789Z", method="GET", path="/workflows",
                status_code=200, user_id="alice", ip_address="10.0.0.1", user_agent="curl/8",
                duration_ms=12, metadata="{}")
    base.update(kw)
    return base


def cases():
    out = []
    first = rec()
    h1 = row_hash(GENESIS, first)
    out.append(("genesis row", GENESIS, first))
    second = rec(seq=2, id="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", method="POST", path="/workflows/start", status_code=201)
    out.append(("second row chains to the first", h1, second))
    out.append(("NULL is not the empty string (NULL)", GENESIS, rec(user_id=None)))
    out.append(("NULL is not the empty string (empty)", GENESIS, rec(user_id="")))
    out.append(("every nullable column NULL", GENESIS,
                rec(status_code=None, user_id=None, ip_address=None, user_agent=None, duration_ms=None, metadata=None)))
    out.append(("non-ASCII, non-BMP and control characters", GENESIS,
                rec(path="/caf\u00e9/\U0001F600", user_agent="a\tb\nc\x01d \"q\" \\ \u2028 end ")))
    out.append(("timestamp beyond microseconds is truncated, not rounded", GENESIS,
                rec(timestamp="2026-09-24T01:02:03.456789999Z")))
    out.append(("timestamp with an offset is normalised to UTC", GENESIS,
                rec(timestamp="2026-09-23T21:02:03.456789-04:00")))
    out.append(("metadata key order and whitespace do not matter (a)", GENESIS,
                rec(metadata='{"b": 1, "a": {"y": [1, 2.50, "x"], "x": null}, "c": true}')))
    out.append(("metadata key order and whitespace do not matter (b)", GENESIS,
                rec(metadata='{"c":true,"a":{"x":null,"y":[1,2.50,"x"]},"b":1}')))
    out.append(("a huge sequence number", h1, rec(seq=9007199254740993)))
    return out


def generate():
    doc = {"version": 1, "domain": DOMAIN.decode("ascii").rstrip("\x00") + "\\0",
           "note": "generated by audit_chain_reference.py; do not edit by hand", "cases": []}
    for name, prev, r in cases():
        doc["cases"].append({"name": name, "prev_hash": prev.hex(), "record": r,
                             "canonical_metadata": (canonical_json(r["metadata"]) if r["metadata"] is not None else None),
                             "canonical_timestamp": canonical_timestamp(r["timestamp"]),
                             "hash": row_hash(prev, r).hex()})
    json.dump(doc, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


def verify():
    doc = json.load(sys.stdin)
    bad = 0
    for c in doc["cases"]:
        got = row_hash(bytes.fromhex(c["prev_hash"]), c["record"]).hex()
        if got != c["hash"]:
            bad += 1
            print("MISMATCH %s: got %s want %s" % (c["name"], got, c["hash"]))
    print("%d cases, %d mismatches" % (len(doc["cases"]), bad))
    sys.exit(1 if bad else 0)


def verify_export():
    """Verify a `GET /audit/export` / `cleatctl audit export` stream from stdin, offline.

        verify-export [--require-full] [--expect-head SEQ:HASH] [--expect-floor SEQ:HASH]
                      [--expect-after SEQ:HASH] [--expect-unchained N]

    Exit status: 0 verified, 1 a break, 2 incomplete, unreadable, or a contradictory command line.

    WHAT THE FILE PROVES BY ITSELF. Every chained event hashes to its own `hash` from its own
    fields and `prev_hash`; event ids are unique; chained `seq` values strictly increase and
    consecutive ones link; the stream ends in exactly one checkpoint whose `events` matches the
    count; unchained events (no `seq`) come before every chained one. The checkpoint also says
    what KIND of export the file is, and the kind decides how much more is required:

      full     (no `from`/`to`, no `after_seq`)  no gaps; starts at floor_seq+1 linking to
                                                 floor_hash; ends at head_seq with head_hash
      resumed  (`after_seq`)                     no gaps; starts at after_seq+1; ends at the
                                                 head; no unchained events (they precede the
                                                 chained ones, so a resume never has any)
      range    (`from` or `to`)                  nothing about coverage: a range has gaps by
                                                 design, so a deletion from one is not detectable

    THE CHECKPOINT IS NOT SIGNED. Whoever can edit the file can edit the kind, and the ends
    it states, to match a deletion. So the file alone proves less than it seems, and the
    options say what the CALLER knows from somewhere the editor cannot reach. Each one pins the
    KIND the caller expects (a checkpoint claiming another is DOWNGRADED) and checks the RECORDS,
    not just the checkpoint:

      --require-full         the caller asked for a whole export: kind must be full
      --expect-floor S:H     kind full; the first chained event is seq S+1 linking to hash H
      --expect-head  S:H     the last chained event is seq S with hash H. Kind full, or
                             resumed when --expect-after is given
      --expect-after S:H     kind resumed with after_seq == S; the first chained event is seq
                             S+1 linking to hash H (the last record of the part you already
                             hold, which is what makes the join checkable)
      --expect-unchained N   exactly N unchained events (take N from `GET /audit/verify`'s
                             `unchained`). Kind full, or resumed with --expect-after (then N=0)

    WHY THE ANCHORS BIND THE RECORDS, NOT ONLY THE CHECKPOINT. For a full or resumed export the
    structure rules tie the records to the checkpoint (the first chained record is floor_seq+1 linking
    to floor_hash, or after_seq+1; the last is head_seq with head_hash), and the anchors tie the
    checkpoint to the values you trust; a range, which those rules do not cover, is refused as
    DOWNGRADED whenever an anchor is given. So an edit that moves the checkpoint to hide a deletion
    disagrees with the anchor, and one that leaves the checkpoint alone disagrees with the records.
    The join of a resumed export is the exception, and is checked directly: nothing in the file
    can say what precedes its first record.

    --expect-after cannot be combined with --require-full or --expect-floor: one asks for a
    whole export and the other for a resume. --expect-floor alone binds the START only, and
    --expect-head alone binds the END only; give both for a whole export.

    WHAT NO OPTION CAN DO. With none, a file whose checkpoint says range or resumed is held to
    nothing about coverage, and a whole export's ends are only as good as its unsigned
    checkpoint; the verifier says so in a NOTE. An unchained event has no hash, so the chain
    cannot say whether one was added at the FRONT of the file: only --expect-unchained can.
    """
    if len(sys.argv) > 2 and sys.argv[2] in ("-h", "--help"):
        print(verify_export.__doc__)
        sys.exit(0)

    def unreadable(msg):
        print("UNREADABLE: " + msg)
        sys.exit(2)

    expect = {}
    require_full = False
    expect_unchained = None
    argv = sys.argv[2:]
    while argv:
        flag = argv.pop(0)
        if flag == "--require-full":
            require_full = True
        elif flag in ("--expect-head", "--expect-floor", "--expect-after") and argv:
            seq, sep, h = argv.pop(0).partition(":")
            if not sep or not seq.isdigit() or not h:
                unreadable("%s wants SEQ:HASH" % flag)
            expect[flag] = (int(seq), h)
        elif flag == "--expect-unchained" and argv:
            v = argv.pop(0)
            if not v.isdigit():
                unreadable("--expect-unchained wants a count")
            expect_unchained = int(v)
        else:
            unreadable("unknown argument %r (verify-export --help lists them)" % flag)
    if "--expect-after" in expect and (require_full or "--expect-floor" in expect):
        unreadable("--expect-after asks for a resumed export, and --require-full / --expect-floor ask for a "
                   "whole one; they cannot both hold")

    events = unchained = breaks = 0
    seen_ids = set()
    chained = []  # (seq, prev_hash, hash)
    checkpoints = []

    def brk(msg):
        nonlocal breaks
        breaks += 1
        print(msg)

    for n, line in enumerate(sys.stdin, 1):
        if not line.strip():
            continue
        try:
            r = json.loads(line, parse_int=_Num, parse_float=_Num)
        except ValueError as e:
            print("UNREADABLE line %d: %s" % (n, e))
            sys.exit(2)
        t = r.get("type")
        if t == "checkpoint":
            checkpoints.append(r)
            continue
        if t != "event":
            print("UNREADABLE line %d: unknown record type %r" % (n, t))
            sys.exit(2)
        if checkpoints:
            print("UNREADABLE line %d: an event after the checkpoint" % n)
            sys.exit(2)
        events += 1
        if r["id"] in seen_ids:
            brk("DUPLICATE line %d: id %s appears more than once" % (n, r["id"]))
        seen_ids.add(r["id"])
        if r["seq"] is None:
            unchained += 1
            if chained:
                brk("UNCHAINED AFTER CHAINED line %d: an unchained event follows chained ones. An export "
                    "sends every unchained event first, so this one was added" % n)
            continue
        seq = int(r["seq"])
        meta = None if r["metadata"] is None else _enc(r["metadata"])
        rc = {k: (None if r[k] is None else (r[k] if k in ("timestamp", "metadata") else str(r[k])))
              for k in FIELDS if k not in ("metadata",)}
        rc["metadata"] = meta
        rc["seq"] = seq
        want = row_hash(bytes.fromhex(r["prev_hash"]), rc).hex()
        if want != r["hash"]:
            brk("EDITED seq %d: hash %s is not the hash of the record's fields %s" % (seq, r["hash"][:12], want[:12]))
        chained.append((seq, r["prev_hash"], r["hash"]))

    if len(checkpoints) != 1:
        print("TRUNCATED: %d checkpoint line(s), want exactly 1. The stream is incomplete." % len(checkpoints))
        sys.exit(2)
    cp = checkpoints[0]
    if int(cp["events"]) != events:
        print("TRUNCATED: the checkpoint says %s events, the stream has %d" % (cp["events"], events))
        sys.exit(2)

    ranged = cp.get("from") is not None or cp.get("to") is not None
    after = None if cp.get("after_seq") is None else int(cp["after_seq"])
    have = "a range" if ranged else ("a resumed export" if after is not None else "a full export")
    if "--expect-after" in expect:
        want_kind = "a resumed export"
    elif require_full or "--expect-head" in expect or "--expect-floor" in expect or expect_unchained is not None:
        want_kind = "a full export"
    else:
        want_kind = None
    if want_kind and have != want_kind:
        brk("DOWNGRADED: %s was required, and the checkpoint claims %s. A range claims no coverage, and an edit "
            "that deletes an event and changes the kind in the checkpoint would look like this." % (want_kind, have))
    if "--expect-after" in expect and after is not None and not ranged and after != expect["--expect-after"][0]:
        brk("ANCHOR MISMATCH: the checkpoint says the export resumed after seq %d, the anchor is seq %d" % (
            after, expect["--expect-after"][0]))
    if after is not None and not ranged and unchained:
        brk("UNCHAINED IN A RESUMED EXPORT: %d unchained event(s) in an export that resumed after seq %d, which "
            "starts in the chained part and so has none" % (unchained, after))
    if expect_unchained is not None and unchained != expect_unchained:
        brk("UNCHAINED COUNT: the export has %d unchained event(s), the caller expected %d" % (unchained, expect_unchained))
    head_seq, floor_seq = int(cp["head_seq"]), int(cp["floor_seq"])

    prev = None
    for seq, prev_hash, h in chained:
        if prev is not None:
            pseq, phash = prev
            if seq <= pseq:
                brk("OUT OF ORDER seq %d after seq %d: seq must strictly increase" % (seq, pseq))
            elif seq == pseq + 1:
                if prev_hash != phash:
                    brk("RELINKED seq %d: prev_hash does not match seq %d's hash" % (seq, pseq))
            elif not ranged:
                brk("GAP: seq %d follows seq %d, so seq %d..%d are missing from an export that claims the whole chain" % (seq, pseq, pseq + 1, seq - 1))
        prev = (seq, h)

    if not ranged:
        start = floor_seq + 1 if after is None else after + 1
        if chained:
            first_seq, first_prev, _ = chained[0]
            last_seq, _, last_hash = chained[-1]
            if first_seq != start:
                brk("MISSING START: the first chained event is seq %d, want seq %d (%s)" % (
                    first_seq, start, "the row after the floor" if after is None else "the row after the cursor"))
            elif after is None and first_prev != cp["floor_hash"]:
                brk("FLOOR MISMATCH: seq %d links to %s, the checkpoint's floor hash is %s" % (first_seq, first_prev[:12], cp["floor_hash"][:12]))
            if last_seq != head_seq:
                brk("MISSING END: the last chained event is seq %d, the checkpoint's head is seq %d" % (last_seq, head_seq))
            elif last_hash != cp["head_hash"]:
                brk("HEAD MISMATCH: seq %d hashes to %s, the checkpoint records %s" % (last_seq, last_hash[:12], cp["head_hash"][:12]))
        else:
            # No chained events: only a chain with nothing in it may say so.
            want_head = floor_seq if after is None else after
            if head_seq != want_head:
                brk("MISSING EVENTS: no chained events, but the checkpoint's head is seq %d and the export started after seq %d" % (head_seq, want_head))
            elif after is None and cp["head_hash"] != cp["floor_hash"]:
                brk("HEAD MISMATCH: no chained events, so the head must be the floor, and the checkpoint's head hash %s is not its floor hash %s" % (
                    cp["head_hash"][:12], cp["floor_hash"][:12]))

    # The anchors bind the RECORDS, not only the checkpoint, and for --expect-head and --expect-floor
    # that is by construction rather than by a second comparison: the structure rules above already
    # require the last chained record to be the checkpoint's head and the first to follow the
    # checkpoint's floor, so once the checkpoint agrees with the anchor the records do too. What makes
    # it hold is that a range, the one kind those rules do not apply to, is refused as DOWNGRADED
    # before any of this. (A second comparison here could never decide anything a run could observe.)
    first = chained[0] if chained else None
    if "--expect-head" in expect:
        eseq, ehash = expect["--expect-head"]
        if head_seq != eseq or cp["head_hash"] != ehash:
            brk("ANCHOR MISMATCH: the checkpoint's head is seq %d %s, the anchor is seq %d %s" % (head_seq, cp["head_hash"][:12], eseq, ehash[:12]))
    if "--expect-floor" in expect:
        eseq, ehash = expect["--expect-floor"]
        if floor_seq != eseq or cp["floor_hash"] != ehash:
            brk("ANCHOR MISMATCH: the checkpoint's floor is seq %d %s, the anchor is seq %d %s" % (floor_seq, cp["floor_hash"][:12], eseq, ehash[:12]))
    if "--expect-after" in expect:
        eseq, ehash = expect["--expect-after"]
        if first is None:
            if head_seq != eseq:
                brk("ANCHOR MISMATCH: no chained events, but the export should continue after seq %d and the head is seq %d" % (eseq, head_seq))
        elif first[0] != eseq + 1 or first[1] != ehash:
            brk("JOIN MISMATCH: the first chained event is seq %d linking to %s; the part you hold ends at seq %d %s, so it must be seq %d linking to it" % (
                first[0], first[1][:12], eseq, ehash[:12], eseq + 1))

    # NOTEs say what the run did NOT establish, so an exit 0 is not read as more than it is.
    if unchained and expect_unchained is None:
        print("NOTE: %d unchained event(s) are not covered by the chain and were not checked. Pass "
              "--expect-unchained N (the `unchained` count of GET /audit/verify) to bind their number." % unchained)
    if want_kind is None:
        if have != "a full export":
            print("NOTE: coverage not checked: %s claims none. Pass --require-full for a whole export, or "
                  "--expect-after SEQ:HASH for a resume." % have)
        else:
            print("NOTE: the ends of this export are the checkpoint's own, and the checkpoint is unsigned. Pass "
                  "--expect-head and --expect-floor with values recorded elsewhere.")
    else:
        if "--expect-head" not in expect:
            print("NOTE: the end is not anchored: pass --expect-head SEQ:HASH, or the last records may have been cut.")
        if want_kind == "a full export" and "--expect-floor" not in expect:
            print("NOTE: the start is not anchored: pass --expect-floor SEQ:HASH, or the first records may have been cut.")
    print("%d events (%d chained checked, %d unchained not covered), %s, %d breaks" % (events, len(chained), unchained, have, breaks))
    sys.exit(1 if breaks else 0)


if __name__ == "__main__":
    {"generate": generate, "verify": verify, "verify-export": verify_export}[sys.argv[1]]()
