#!/usr/bin/env python3
"""Reference implementation of the audit-log hash chain (cleat#2047).

This is the CONTRACT for an offline verifier, and the second, independent
derivation the Go implementation is checked against: chain_vectors.json is
generated by this file, and plugins/auditlog/chain_test.go asserts the Go code
reproduces every hash in it. Two implementations written from the same prose
agreeing is evidence; one implementation agreeing with its own output is not.

    python3 audit_chain_reference.py generate > chain_vectors.json
    python3 audit_chain_reference.py verify   < chain_vectors.json

The hash of a row is

    SHA-256( DOMAIN || prev_hash(32 raw bytes) || field(tenant_id) || field(seq) || ... )

over the fields, in this order, each encoded as: one presence byte (0 = SQL NULL,
1 = present) and, when present, uvarint(len(bytes)) followed by the UTF-8 bytes.
Every field is text: integers are decimal, UUIDs are lowercase and hyphenated, the
timestamp is UTC to the microsecond as YYYY-MM-DDTHH:MM:SS.ffffffZ, and metadata is
canonical JSON (see canonical_json). prev_hash of a tenant's first row is 32 zero bytes.
"""
import hashlib
import json
import re
import sys
from datetime import datetime, timedelta, timezone

DOMAIN = b"cleat-audit-chain-v1\x00"
GENESIS = bytes(32)
FIELDS = ["tenant_id", "seq", "id", "timestamp", "method", "path", "status_code",
          "user_id", "ip_address", "user_agent", "duration_ms", "metadata"]


def uvarint(n):
    out = bytearray()
    while n >= 0x80:
        out.append((n & 0x7F) | 0x80)
        n >>= 7
    out.append(n)
    return bytes(out)


def field(v):
    if v is None:
        return b"\x00"
    b = v.encode("utf-8")
    return b"\x01" + uvarint(len(b)) + b


_TS = re.compile(r"^(\d{4})-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)(?:\.(\d{1,9}))?(Z|[+-]\d\d:\d\d)$")


def canonical_timestamp(s):
    m = _TS.match(s)
    if not m:
        raise ValueError("not an RFC 3339 timestamp: %r" % s)
    y, mo, d, h, mi, sec, frac, zone = m.groups()
    micro = int((frac or "").ljust(6, "0")[:6])  # truncated, never rounded
    dt = datetime(int(y), int(mo), int(d), int(h), int(mi), int(sec), micro, tzinfo=timezone.utc)
    if zone != "Z":
        sign = 1 if zone[0] == "+" else -1
        off = timedelta(hours=int(zone[1:3]), minutes=int(zone[4:6]))
        dt = dt - sign * off
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _escape(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif o < 0x20:
            out.append("\\u%04x" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


class _Num(str):
    pass


def _enc(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, _Num):
        return str(v)
    if isinstance(v, str):
        return _escape(v)
    if isinstance(v, list):
        return "[" + ",".join(_enc(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(_escape(k) + ":" + _enc(v[k]) for k in sorted(v)) + "}"
    raise TypeError(type(v))


def canonical_json(text):
    """Sorted keys (code point order), no whitespace, strings escaped only for
    the quote, the backslash and control characters below 0x20 (as \\u00xx, lower
    case hex), everything else verbatim, numbers as their original token."""
    v = json.loads(text, parse_int=_Num, parse_float=_Num)
    return _enc(v)


def canonical_fields(rec):
    vals = []
    for name in FIELDS:
        v = rec[name]
        if v is None:
            vals.append(None)
        elif name == "timestamp":
            vals.append(canonical_timestamp(v))
        elif name == "metadata":
            vals.append(canonical_json(v))
        else:
            vals.append(str(v))
    return vals


def row_hash(prev_hash, rec):
    h = hashlib.sha256()
    h.update(DOMAIN)
    h.update(prev_hash)
    for v in canonical_fields(rec):
        h.update(field(v))
    return h.digest()


def rec(**kw):
    base = dict(tenant_id="11111111-1111-1111-1111-111111111111", seq=1,
                id="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                timestamp="2026-09-24T01:02:03.456789Z", method="GET", path="/workflows",
                status_code=200, user_id="alice", ip_address="10.0.0.1", user_agent="curl/8",
                duration_ms=12, metadata="{}")
    base.update(kw)
    return base


def cases():
    out = []
    first = rec()
    h1 = row_hash(GENESIS, first)
    out.append(("genesis row", GENESIS, first))
    second = rec(seq=2, id="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", method="POST", path="/workflows/start", status_code=201)
    out.append(("second row chains to the first", h1, second))
    out.append(("NULL is not the empty string (NULL)", GENESIS, rec(user_id=None)))
    out.append(("NULL is not the empty string (empty)", GENESIS, rec(user_id="")))
    out.append(("every nullable column NULL", GENESIS,
                rec(status_code=None, user_id=None, ip_address=None, user_agent=None, duration_ms=None, metadata=None)))
    out.append(("non-ASCII, non-BMP and control characters", GENESIS,
                rec(path="/caf\u00e9/\U0001F600", user_agent="a\tb\nc\x01d \"q\" \\ \u2028 end ")))
    out.append(("timestamp beyond microseconds is truncated, not rounded", GENESIS,
                rec(timestamp="2026-09-24T01:02:03.456789999Z")))
    out.append(("timestamp with an offset is normalised to UTC", GENESIS,
                rec(timestamp="2026-09-23T21:02:03.456789-04:00")))
    out.append(("metadata key order and whitespace do not matter (a)", GENESIS,
                rec(metadata='{"b": 1, "a": {"y": [1, 2.50, "x"], "x": null}, "c": true}')))
    out.append(("metadata key order and whitespace do not matter (b)", GENESIS,
                rec(metadata='{"c":true,"a":{"x":null,"y":[1,2.50,"x"]},"b":1}')))
    out.append(("a huge sequence number", h1, rec(seq=9007199254740993)))
    return out


def generate():
    doc = {"version": 1, "domain": DOMAIN.decode("ascii").rstrip("\x00") + "\\0",
           "note": "generated by audit_chain_reference.py; do not edit by hand", "cases": []}
    for name, prev, r in cases():
        doc["cases"].append({"name": name, "prev_hash": prev.hex(), "record": r,
                             "canonical_metadata": (canonical_json(r["metadata"]) if r["metadata"] is not None else None),
                             "canonical_timestamp": canonical_timestamp(r["timestamp"]),
                             "hash": row_hash(prev, r).hex()})
    json.dump(doc, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


def verify():
    doc = json.load(sys.stdin)
    bad = 0
    for c in doc["cases"]:
        got = row_hash(bytes.fromhex(c["prev_hash"]), c["record"]).hex()
        if got != c["hash"]:
            bad += 1
            print("MISMATCH %s: got %s want %s" % (c["name"], got, c["hash"]))
    print("%d cases, %d mismatches" % (len(doc["cases"]), bad))
    sys.exit(1 if bad else 0)


def verify_export():
    """Verify a `GET /audit/export` / `cleatctl audit export` stream from stdin, offline.

    Every chained event must hash to its own `hash` from its own fields and `prev_hash`;
    consecutive seq values must link; and the stream must end with a checkpoint line (a
    stream without one is TRUNCATED, and says so with status 2). Where the last event is
    the chain head the checkpoint names, its hash must be the checkpoint's. Rows written
    before the chain existed carry no seq and are counted, not verified.

    Exit status: 0 verified, 1 a break, 2 the stream is incomplete or unreadable.
    """
    events = unchained = breaks = 0
    prev_seq = prev_hash = None
    last_seq = last_hash = None
    checkpoints = []
    for n, line in enumerate(sys.stdin, 1):
        if not line.strip():
            continue
        try:
            r = json.loads(line, parse_int=_Num, parse_float=_Num)
        except ValueError as e:
            print("UNREADABLE line %d: %s" % (n, e))
            sys.exit(2)
        t = r.get("type")
        if t == "checkpoint":
            checkpoints.append(r)
            continue
        if t != "event":
            print("UNREADABLE line %d: unknown record type %r" % (n, t))
            sys.exit(2)
        if checkpoints:
            print("UNREADABLE line %d: an event after the checkpoint" % n)
            sys.exit(2)
        events += 1
        if r["seq"] is None:
            unchained += 1
            continue
        seq = int(r["seq"])
        meta = None if r["metadata"] is None else _enc(r["metadata"])
        rc = {k: (None if r[k] is None else (r[k] if k in ("timestamp", "metadata") else str(r[k])))
              for k in FIELDS if k not in ("metadata",)}
        rc["metadata"] = meta
        rc["seq"] = seq
        want = row_hash(bytes.fromhex(r["prev_hash"]), rc).hex()
        if want != r["hash"]:
            breaks += 1
            print("EDITED seq %d: hash %s is not the hash of the record's fields %s" % (seq, r["hash"][:12], want[:12]))
        if prev_seq is not None and seq == prev_seq + 1 and r["prev_hash"] != prev_hash:
            breaks += 1
            print("RELINKED seq %d: prev_hash does not match seq %d's hash" % (seq, prev_seq))
        prev_seq, prev_hash = seq, r["hash"]
        last_seq, last_hash = seq, r["hash"]
    if len(checkpoints) != 1:
        print("TRUNCATED: %d checkpoint line(s), want exactly 1. The stream is incomplete." % len(checkpoints))
        sys.exit(2)
    cp = checkpoints[0]
    if int(cp["events"]) != events:
        print("TRUNCATED: the checkpoint says %s events, the stream has %d" % (cp["events"], events))
        sys.exit(2)
    if last_seq is not None and last_seq == int(cp["head_seq"]) and last_hash != cp["head_hash"]:
        breaks += 1
        print("HEAD MISMATCH: the newest row (seq %d) hashes to %s, the checkpoint records %s" % (last_seq, last_hash[:12], cp["head_hash"][:12]))
    print("%d events (%d chained verified, %d unchained not covered), %d breaks" % (events, events - unchained, unchained, breaks))
    sys.exit(1 if breaks else 0)


if __name__ == "__main__":
    {"generate": generate, "verify": verify, "verify-export": verify_export}[sys.argv[1]]()
