# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Extended lifecycle (ABI 2.15)
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def continue_as_new_versioned(input: str, new_version: int) -> int:
    """
    Continue as new with an explicit version.
    """
    raise NotImplementedError
def side_effect(value: str) -> str:
    """
    Record non-deterministic computation result in event history.
    Returns the previously recorded result on replay.
    
    Raises: `componentize_py_types.Err(wit_world.imports.outcomes.CallFailure)`
    """
    raise NotImplementedError
def durable_run_detached(name: str, input: str) -> int:
    """
    Start a workflow that outlives this one (fire-and-forget).
    
    Takes a workflow NAME and input, not a closure: a closure cannot cross
    the ABI, which is why the SDK method that took one was never wired to
    this call and ran inline instead (IMPROVEMENT-PLAN 3.253).
    
    Returns the host's packed result rather than a string: cleat_run_detached
    has no output buffer, so there is only an error code to report. Declared
    u64 for the same reason durable-signal-workflow is.
    """
    raise NotImplementedError
