# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Workflow and run identity introspection.
"""



def durable_workflow_id() -> str:
    """
    Get the current workflow's unique identifier.
    """
    raise NotImplementedError
def durable_run_id() -> str:
    """
    Get the current workflow run's unique identifier.
    """
    raise NotImplementedError
