# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Fire-and-forget and scheduled messaging.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_send(service: str, operation: str, request: str) -> int:
    """
    Send a fire-and-forget request to an external service.
    """
    raise NotImplementedError
def durable_schedule_invoke(service: str, operation: str, request: str, delay_ms: int) -> int:
    """
    Schedule a delayed one-shot invocation.
    """
    raise NotImplementedError
