# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Workflow lifecycle operations (defer, compaction, cancellation).
"""




def durable_defer(desc_ptr: int, desc_len: int, defer_id_ptr: int, defer_id_max_len: int) -> int:
    """
    Register a deferred cleanup action to run on workflow exit.
    """
    raise NotImplementedError
def durable_continue_as_new(input_ptr: int, input_len: int) -> int:
    """
    Replace workflow input and restart execution (history compaction).
    """
    raise NotImplementedError
def durable_poll_cancellation(reason_ptr: int, reason_max_len: int) -> int:
    """
    Check if workflow cancellation has been requested.
    """
    raise NotImplementedError
