# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Update and query handler registration.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_register_update_handler(name: str) -> int:
    """
    Register an update handler for external update calls.
    """
    raise NotImplementedError
def durable_register_query_handler(name: str) -> int:
    """
    Register a read-only query handler for external queries.
    """
    raise NotImplementedError
