# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Fire-and-forget and scheduled messaging.
"""




def durable_send(svc_ptr: int, svc_len: int, op_ptr: int, op_len: int, req_ptr: int, req_len: int) -> int:
    """
    Send a fire-and-forget request to an external service.
    """
    raise NotImplementedError
def durable_schedule_invoke(svc_ptr: int, svc_len: int, op_ptr: int, op_len: int, req_ptr: int, req_len: int, delay_ms: int) -> int:
    """
    Schedule a delayed one-shot invocation.
    """
    raise NotImplementedError
