# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Timer, clock, random, and log operations.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_sleep(duration_ms: int) -> int:
    """
    Suspend workflow execution for a duration (in milliseconds).
    """
    raise NotImplementedError
def durable_now() -> int:
    """
    Get current wall-clock time in milliseconds since Unix epoch.
    """
    raise NotImplementedError
def durable_random() -> int:
    """
    Get a deterministic random 64-bit value.
    """
    raise NotImplementedError
def durable_log(msg: str) -> int:
    """
    Log a message to the workflow event history.
    """
    raise NotImplementedError
