# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
HTTP fetch (ABI 2.45)
"""

def fetch(method: str, url: str, headers: str, body: str) -> str:
    raise NotImplementedError
