# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Queryable state management.
"""




def set_query_state(key_ptr: int, key_len: int, val_ptr: int, val_len: int) -> int:
    """
    Set a key-value pair in the workflow's queryable state.
    """
    raise NotImplementedError
