# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Extended child workflow operations (ABI 2.10)
"""

def child_workflow_in_schema(schema: str, name: str, input: str, version: int, priority: int, policy: str) -> str:
    raise NotImplementedError
