# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Service call operations: recorded, retried, or heartbeated.
"""




def durable_call(service_ptr: int, service_len: int, operation_ptr: int, operation_len: int, request_ptr: int, request_len: int, response_ptr: int, response_max_len: int) -> int:
    """
    Make a durable (deterministically replayed) call to an external service.
    """
    raise NotImplementedError
def durable_call_retry(service_ptr: int, service_len: int, operation_ptr: int, operation_len: int, request_ptr: int, request_len: int, max_attempts: int, initial_interval_ms: int, backoff_coefficient_100x: int, max_interval_ms: int, non_retryable_errors_ptr: int, non_retryable_errors_len: int, response_ptr: int, response_max_len: int) -> int:
    """
    Make a durable call with server-side retry policy.
    """
    raise NotImplementedError
def durable_call_heartbeat(service_ptr: int, service_len: int, operation_ptr: int, operation_len: int, request_ptr: int, request_len: int, heartbeat_interval_ms: int, response_ptr: int, response_max_len: int) -> int:
    """
    Make a durable call with periodic heartbeat/progress updates.
    """
    raise NotImplementedError
