# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Child workflow spawn and await operations.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_child_workflow(name: str, input: str) -> str:
    """
    Start a child workflow instance (async).
    Returns the child run ID string.
    
    Raises: `componentize_py_types.Err(wit_world.imports.outcomes.CallFailure)`
    """
    raise NotImplementedError
def durable_await_child(run_id: str) -> str:
    """
    Wait for a single child workflow to complete.
    Returns the child result JSON string.
    """
    raise NotImplementedError
def durable_await_all_children(run_ids_json: str) -> str:
    """
    Wait for multiple child workflows to complete (batch).
    Returns the combined results JSON string.
    """
    raise NotImplementedError
def durable_await_any_child(run_ids_json: str) -> str:
    """
    Wait for the FIRST of several child workflows to complete.
    Returns that child's result JSON string.
    
    Distinct from durable-await-all-children, which waits for every one:
    this returns as soon as any single child finishes, which is the
    primitive a race or a first-wins fan-out needs.
    """
    raise NotImplementedError
def durable_poll_child(run_id: str) -> str:
    """
    Check a child workflow without waiting.
    Returns the child's status JSON; does not suspend.
    """
    raise NotImplementedError
def durable_child_workflow_with_options(name: str, input: str, version: int, priority: int, parent_close_policy: str) -> str:
    """
    Start a child workflow with version, priority, and parent-close-policy options.
    Returns the child run ID string.
    
    Raises: `componentize_py_types.Err(wit_world.imports.outcomes.CallFailure)`
    """
    raise NotImplementedError
