# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Update and query handler registration.
"""




def durable_register_update_handler(name_ptr: int, name_len: int) -> int:
    """
    Register an update handler for external update calls.
    """
    raise NotImplementedError
def durable_register_query_handler(name_ptr: int, name_len: int) -> int:
    """
    Register a read-only query handler for external queries.
    """
    raise NotImplementedError
