# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Extended lifecycle (ABI 2.15)
"""

def continue_as_new_versioned(input: str, new_version: int) -> int:
    raise NotImplementedError

def side_effect(result: str) -> str:
    raise NotImplementedError
