# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Recurring workflow triggers.

Mirrors HostCalls.ScheduleCron / DeleteCron / ListCrons in the Go SDK
(cleat/runtime.go) and cleat_schedule_cron / cleat_delete_cron /
cleat_list_crons on the ABI. The engine owns the schedule; the workflow
only registers and removes them.

Delivery is at-least-once: a firing may be delivered more than once and
will not be silently skipped. See tiers.yaml, workflow-callable-cron.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_schedule_cron(workflow_name: str, cron_expr: str, timezone: str, input: str) -> str:
    """
    Register a recurring trigger for another workflow.
    
    ``timezone`` is an IANA name ("Europe/Berlin"); empty means UTC. The
    cron expression is evaluated in that zone, not the worker's.
    Returns the schedule ID.
    """
    raise NotImplementedError
def durable_delete_cron(schedule_id: str) -> None:
    """
    Remove a recurring trigger by schedule ID.
    """
    raise NotImplementedError
def durable_list_crons() -> str:
    """
    List this tenant's recurring triggers as a JSON array.
    """
    raise NotImplementedError
