# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Scoped state / virtual object operations (ABI 2.26-2.28)
"""

def set_scope(obj_type: str, inst_key: str) -> str:
    raise NotImplementedError

def get_scope(obj_type_ptr: int, obj_type_max_len: int, inst_key_ptr: int, inst_key_max_len: int) -> int:
    raise NotImplementedError

def uuid(seed: str) -> str:
    raise NotImplementedError
