# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Durable distributed lock operations.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_acquire_lock(key: str, ttl_ms: int) -> int:
    """
    Acquire a distributed lock with the given key and TTL.
    """
    raise NotImplementedError
def durable_release_lock(key: str) -> int:
    """
    Release a previously acquired distributed lock.
    """
    raise NotImplementedError
