# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
State operations (Stream R) (ABI 2.37-2.44)
"""

def set_state(key: str, val: str) -> int:
    raise NotImplementedError

def get_state(key: str) -> str:
    raise NotImplementedError

def delete_state(key: str) -> int:
    raise NotImplementedError

def incr_state(key: str, delta: int) -> int:
    raise NotImplementedError

def has_state(key: str) -> int:
    raise NotImplementedError

def list_state(prefix: str) -> str:
    raise NotImplementedError
