# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Extended lifecycle (ABI 2.15)
"""

def continue_as_new_versioned(input_ptr: int, input_len: int, new_version: int) -> int:
    raise NotImplementedError

def side_effect(result_ptr: int, result_len: int, out_ptr: int, out_max_len: int) -> int:
    raise NotImplementedError
