# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Child workflow spawn and await operations.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_child_workflow(name_ptr: int, name_len: int, input_ptr: int, input_len: int, run_id_ptr: int, run_id_max_len: int) -> int:
    """
    Start a child workflow instance (async).
    """
    raise NotImplementedError
def durable_await_child(run_id_ptr: int, run_id_len: int, result_ptr: int, result_max_len: int) -> int:
    """
    Wait for a single child workflow to complete.
    """
    raise NotImplementedError
def durable_await_all_children(run_ids_json_ptr: int, run_ids_json_len: int, results_ptr: int, results_max_len: int) -> int:
    """
    Wait for multiple child workflows to complete (batch).
    """
    raise NotImplementedError
def durable_child_workflow_with_options(name: str, input: str, version: int) -> str:
    """
    Start a child workflow with explicit version options.
    """
    raise NotImplementedError
