# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Durable distributed lock operations.
"""




def durable_acquire_lock(key: str, ttl_ms: int) -> int:
    """
    Acquire a distributed lock with the given key and TTL.
    """
    raise NotImplementedError
def durable_release_lock(key: str) -> int:
    """
    Release a previously acquired distributed lock.
    """
    raise NotImplementedError
