# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Workflow and run identity introspection.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def durable_workflow_id() -> str:
    """
    Get the current workflow's unique identifier.
    """
    raise NotImplementedError
def durable_run_id() -> str:
    """
    Get the current workflow run's unique identifier.
    """
    raise NotImplementedError
