# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Child workflow spawn and await operations.
"""



def durable_child_workflow(name: str, input: str) -> str:
    """
    Start a child workflow instance (async).
    """
    raise NotImplementedError
def durable_await_child(run_id: str) -> str:
    """
    Wait for a single child workflow to complete.
    """
    raise NotImplementedError
def durable_await_all_children(run_ids_json: str) -> str:
    """
    Wait for multiple child workflows to complete (batch).
    """
    raise NotImplementedError
def durable_child_workflow_with_options(
    name: str,
    input: str,
    version: int,
    priority: int,
    parent_close_policy: str,
) -> str:
    """
    Start a child workflow with version, priority, and parent-close-policy options.
    """
    raise NotImplementedError
