# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Durable promise create, await, resolve, and reject operations.
"""



def durable_create_promise(name: str, ttl_ms: int) -> str:
    """
    Create a durable promise with the given name.
    """
    raise NotImplementedError
def durable_await_promise(id: str, timeout_ms: int) -> str:
    """
    Wait for a durable promise to resolve, with a timeout.
    """
    raise NotImplementedError
def durable_resolve_promise(id: str, value: str) -> int:
    """
    Resolve a durable promise with a value.
    """
    raise NotImplementedError
def durable_reject_promise(id: str, error: str) -> int:
    """
    Reject a durable promise with an error.
    """
    raise NotImplementedError
