# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Plugin host function extension interface.
"""



def plugin_call(plugin_name: str, function_name: str, input: str) -> str:
    """
    Call a plugin host function.
    """
    raise NotImplementedError
def plugin_call_streaming(plugin_name: str, function_name: str, input: str) -> str:
    """
    Call a streaming plugin host function (for workstream D2b).
    """
    raise NotImplementedError
