// Code generated by durable-gen. DO NOT EDIT.

package restaurant

import "github.com/rcownie/durable/durable"

type NotifyOrderRequest struct {
	RestaurantID string `json:"restaurant_id"`
	Items        string `json:"items"`
	ETAMinutes   int    `json:"eta_minutes"`
}

type CancelOrderRequest struct {
	OrderID string `json:"order_id"`
}

type Client struct {
	h durable.HostCalls
}

func NewClient(h durable.HostCalls) *Client {
	return &Client{h: h}
}

func (c *Client) NotifyOrder(req NotifyOrderRequest) error {
	return c.h.DurableCallTyped("restaurant", "NotifyOrder", req, nil)
}

func (c *Client) CancelOrder(req CancelOrderRequest) error {
	return c.h.DurableCallTyped("restaurant", "CancelOrder", req, nil)
}
