// AssemblyScript workflow example for cleat durable execution.
//
// Compiled to WASM with: npx asc assembly/index.ts --target release
//   --transform ./node_modules/@cleat/transform/index.js
//
// Uses @cleatEntry decorator.  The transformer generates the ABI-compatible
// WASM export wrapper automatically.
//
// ABI export signature (generated by the transformer):
//   (argsPtr: usize, argsLen: i32, outPtr: usize, maxOutLen: i32) -> i64
//
// Workflow functions receive a HostCalls instance and the raw input JSON
// string.  The transformer handles reading input from linear memory, creating
// the HostCalls instance, and writing the result back to the output buffer.

import {
  HostCalls,
  cleatEntry,
  CleatCallOutcome,
  deferFunc,
  isWorkflowSuspended,
} from "@cleat/sdk";

// ---------------------------------------------------------------------------
// Manual JSON helpers
//
// AS 0.27.32 with --runtime stub has no JSON.parse<T>().  We implement minimal
// field extraction for our known flat JSON objects.
// ---------------------------------------------------------------------------

/** Extract a string field value from a flat JSON object. */
function extractStringField(json: string, field: string): string {
  let searchKey: string = '"' + field + '":"';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return "";
  let start: i32 = keyIdx + searchKey.length;
  let end: i32 = indexOf(json, '"', start);
  if (end < 0) return "";
  return json.substring(start, end);
}

/** Extract an i64 integer field value from a flat JSON object. */
function extractI64Field(json: string, field: string): i64 {
  let searchKey: string = '"' + field + '":';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return 0;
  let start: i32 = keyIdx + searchKey.length;
  while (start < json.length && json.charAt(start) == ' ') start++;
  let end: i32 = start;
  while (end < json.length && isDigit(json.charAt(end))) end++;
  if (end <= start) return 0;
  let numStr: string = json.substring(start, end);
  return parseI64(numStr);
}

/** Extract a raw JSON array value for a field (preserving array structure). */
function extractRawArray(json: string, field: string): string {
  let searchKey: string = '"' + field + '":[';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return "";
  let start: i32 = keyIdx + searchKey.length - 1; // include '['
  let depth: i32 = 1;
  let pos: i32 = start + 1;
  while (pos < json.length && depth > 0) {
    if (json.charAt(pos) == '[') depth++;
    if (json.charAt(pos) == ']') depth--;
    pos++;
  }
  return json.substring(start, pos);
}

/** Simple indexOf for strings with optional start position. */
function indexOf(s: string, search: string, start: i32 = 0): i32 {
  if (search.length === 0) return start;
  if (s.length < search.length) return -1;
  let max: i32 = s.length - search.length;
  for (let i: i32 = start; i <= max; i++) {
    let found: bool = true;
    for (let j: i32 = 0; j < search.length; j++) {
      if (s.charAt(i + j) !== search.charAt(j)) {
        found = false;
        break;
      }
    }
    if (found) return i;
  }
  return -1;
}

function isDigit(c: string): bool {
  return c >= "0" && c <= "9";
}

/** Parse a decimal string into an i64 (ASCII digits only). */
function parseI64(s: string): i64 {
  let result: i64 = 0;
  let negative: bool = false;
  let i: i32 = 0;
  if (s.length > 0 && s.charAt(0) == "-") {
    negative = true;
    i = 1;
  }
  while (i < s.length) {
    let c: string = s.charAt(i);
    if (c < "0" || c > "9") break;
    result = result * 10 + (c.charCodeAt(0) - 48);
    i++;
  }
  if (negative) result = -result;
  return result;
}

// ---------------------------------------------------------------------------
// Workflow: place_order
//
// Saga-like orchestration with compensation:
//   1. Reserve inventory
//   2. Charge payment  (on failure: release inventory)
//   3. Create shipment (on failure: refund + release inventory)
//   4. Notify customer (best-effort, no compensation needed)
// ---------------------------------------------------------------------------

@cleatEntry("PlaceOrder")
export function place_order(h: HostCalls, input: string): string {
  // ---- Read and parse input ----
  let userID: string = extractStringField(input, "userID");
  let itemsJson: string = extractRawArray(input, "items");

  if (itemsJson.length <= 2) { // "[]" or empty
    return '{"error":"cart is empty"}';
  }

  // --- Step 1: Reserve inventory -------------------------------------------

  let reserveReq: string = '{"user_id":"' + userID + '","items":' + itemsJson + '}';
  let reserveResult: CleatCallOutcome = h.cleatCall("inventory", "Reserve", reserveReq);
  if (reserveResult.isError) {
    return '{"error":"inventory reserve failed"}';
  }
  // snake_case, because these read a *service response*, not this workflow's own
  // input. The services return reservation_id / total_cents / charge_id, and this
  // file already emits snake_case when it builds requests. Reading camelCase here
  // silently returned "" and 0 -- every step ran, none of them received anything.
  let reservationID: string = extractStringField(reserveResult.response, "reservation_id");
  let totalCents: i64 = extractI64Field(reserveResult.response, "total_cents");

  // --- Step 2: Charge payment ----------------------------------------------

  let chargeReq: string = '{"user_id":"' + userID + '","amount_cents":' + totalCents.toString() + '}';
  let chargeResult: CleatCallOutcome = h.cleatCall("payments", "Charge", chargeReq);
  if (chargeResult.isError) {
    // Compensate: release the reserved inventory.
    h.cleatCall("inventory", "Release", '{"reservation_id":"' + reservationID + '"}');
    return '{"error":"payment failed"}';
  }
  let chargeID: string = extractStringField(chargeResult.response, "charge_id");

  // --- Step 3: Create shipment --------------------------------------------

  let shipReq: string = '{"reservation_id":"' + reservationID + '","charge_id":"' + chargeID + '"}';
  let shipResult: CleatCallOutcome = h.cleatCall("shipping", "CreateShipment", shipReq);
  if (shipResult.isError) {
    // Compensate: refund the payment and release inventory.
    h.cleatCall("payments", "Refund", '{"charge_id":"' + chargeID + '"}');
    h.cleatCall("inventory", "Release", '{"reservation_id":"' + reservationID + '"}');
    return '{"error":"shipping failed"}';
  }

  // --- Step 4: Notify customer (best-effort) -------------------------------

  h.cleatCall("notifications", "SendEmail", '{"user_id":"' + userID + '","message":"Order shipped"}');

  return '{"status":"shipped","reservation_id":"' + reservationID + '"}';
}

// ---------------------------------------------------------------------------
// Workflow: cancel_order
//
// A cancellation-aware entry point that checks cancellation before proceeding.
// ---------------------------------------------------------------------------

@cleatEntry("CancelOrder")
export function cancel_order(h: HostCalls, input: string): string {
  // ---- Read and parse input ----
  let userID: string = extractStringField(input, "userID");
  let itemsJson: string = extractRawArray(input, "items");

  // ---- Check cancellation ----
  let cancelledStatus = h.pollCancellation();
  if (cancelledStatus.cancelled) {
    return '{"status":"cancelled","reason":"cancelled before processing"}';
  }

  if (itemsJson.length <= 2) {
    return '{"error":"cart is empty"}';
  }

  let reserveReq: string = '{"user_id":"' + userID + '","items":' + itemsJson + '}';
  let reserveResult: CleatCallOutcome = h.cleatCall("inventory", "Reserve", reserveReq);
  if (reserveResult.isError) {
    return '{"error":"inventory reserve failed"}';
  }

  return '{"status":"reserved"}';
}

// ---------------------------------------------------------------------------
// deferOrder — defer bodies actually run (IMPROVEMENT-PLAN §3.73)
//
// `h.defer(description)` registers a DESCRIPTION with the host and nothing
// else; no code anywhere runs it. `deferFunc` is the one with a body, and the
// generated wrapper drains the table when this returns, so the calls below
// arrive in the order body, second, first — LIFO, because a defer releases
// what the defer before it acquired.
//
// The bodies are top-level functions taking an explicit payload rather than
// closures, which is this SDK's existing idiom (see `saga.ts`) and is forced
// by `--runtime stub`.
// ---------------------------------------------------------------------------

/** First defer body. Runs LAST, because it was registered first. */
function notifyFirst(h: HostCalls, payload: string): void {
  h.cleatCall("notifications", "first", payload);
}

/** Second defer body. Runs FIRST, because it was registered last. */
function notifySecond(h: HostCalls, payload: string): void {
  h.cleatCall("notifications", "second", payload);
}

@cleatEntry("DeferOrder")
export function defer_order(h: HostCalls, input: string): string {
  let userID: string = extractStringField(input, "userID");

  // The state each body needs travels in its payload, not in a capture.
  deferFunc(h, "notify first", notifyFirst, '{"user":"' + userID + '"}');
  deferFunc(h, "notify second", notifySecond, "{}");

  h.cleatCall("inventory", "body", "{}");
  return '{"deferred":true}';
}

// ---------------------------------------------------------------------------
// deferSuspend — defers do NOT run when the workflow suspends
//
// A suspended workflow has not exited. Its defers are still pending, and
// firing them at the first sleep would release locks a workflow that is about
// to continue still holds.
//
// This SDK needs that stated as a test more than the others do. Go, Rust,
// Python and Java suspend by unwinding, so their drain sits on a path the
// unwind skips and gets the ordering for free. AssemblyScript has no
// exceptions: suspension is a flag, the entry point returns normally either
// way, and the guard in the generated wrapper is the only thing keeping the
// defer from running. Move the drain one line earlier and this workflow
// releases the lock it is still holding.
// ---------------------------------------------------------------------------

@cleatEntry("DeferSuspend")
export function defer_suspend(h: HostCalls, input: string): string {
  deferFunc(h, "must not run while suspended", notifyFirst, '{"user":"suspended"}');

  h.cleatSleep(60);

  // Returning early on the flag is how an AssemblyScript workflow suspends.
  // There is no exception to unwind on, so a suspending host call sets the
  // flag and RETURNS -- the rest of the function body runs unless the author
  // stops it. `Saga.run` does exactly this check after every step. Without it
  // the line below would execute during the suspending segment and be
  // replayed on the next one.
  if (isWorkflowSuspended()) {
    return "";
  }

  h.cleatCall("inventory", "after_sleep", "{}");
  return '{"slept":true}';
}

// ---------------------------------------------------------------------------
// spinForever — a runaway workflow with cleanup outstanding
//
// For IMPROVEMENT-PLAN §3.35 phase 4: a workflow the HOST kills never reaches
// the generated wrapper's drain, so the only thing that can run its defers is
// the host calling __cleat_run_deferred. This entry point exists to be killed.
// ---------------------------------------------------------------------------

/** Sink for the spin loop, so the optimiser cannot delete it. */
let _spinSink: i64 = 0;

/** The cleanup a killed workflow must still get. */
function releaseTheFencedLock(h: HostCalls, payload: string): void {
  h.cleatCall("inventory", "the_fenced_workflows_defer", payload);
}

@cleatEntry("SpinForever")
export function spin_forever(h: HostCalls, input: string): string {
  deferFunc(h, "release the lock the runaway workflow took", releaseTheFencedLock, "{}");

  // Not `while (true)`: AssemblyScript's optimiser treats a provably infinite
  // loop with a dead tail as unreachable code. Reading the sink keeps it.
  while (_spinSink >= 0) {
    _spinSink += 1;
  }
  return '{"unreachable":true}';
}

// ---------------------------------------------------------------------------
// trapAfterDefer — a workflow that traps with cleanup outstanding
//
// The fence cannot be used to make this happen on wazero: a compute-bound
// guest cannot be interrupted there at all (CLAUDE.md records three ways that
// were tried and failed). An explicit trap is the one abnormal exit both
// runtimes can produce, which is what makes it the right fixture for asking
// whether the wazero path runs a dead workflow's defers the way the wasmtime
// path now does.
// ---------------------------------------------------------------------------

@cleatEntry("TrapAfterDefer")
export function trap_after_defer(h: HostCalls, input: string): string {
  deferFunc(h, "release the lock the trapped workflow took", releaseTheFencedLock, "{}");
  unreachable();
  return "";
}
