// AssemblyScript workflow example for cleat durable execution.
//
// Compiled to WASM with: npx asc assembly/index.ts --target release
//   --transform ./node_modules/@cleat/transform/index.js
//
// Uses @cleatEntry decorator.  The transformer generates the ABI-compatible
// WASM export wrapper automatically.
//
// ABI export signature (generated by the transformer):
//   (argsPtr: usize, argsLen: i32, outPtr: usize, maxOutLen: i32) -> i64
//
// Workflow functions receive a HostCalls instance and the raw input JSON
// string.  The transformer handles reading input from linear memory, creating
// the HostCalls instance, and writing the result back to the output buffer.

import {
  HostCalls,
  cleatEntry,
  CleatCallOutcome,
} from "../../../packages/cleat-as/assembly/index";

// ---------------------------------------------------------------------------
// Manual JSON helpers
//
// AS 0.27.32 with --runtime stub has no JSON.parse<T>().  We implement minimal
// field extraction for our known flat JSON objects.
// ---------------------------------------------------------------------------

/** Extract a string field value from a flat JSON object. */
function extractStringField(json: string, field: string): string {
  let searchKey: string = '"' + field + '":"';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return "";
  let start: i32 = keyIdx + searchKey.length;
  let end: i32 = indexOf(json, '"', start);
  if (end < 0) return "";
  return json.substring(start, end);
}

/** Extract an i64 integer field value from a flat JSON object. */
function extractI64Field(json: string, field: string): i64 {
  let searchKey: string = '"' + field + '":';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return 0;
  let start: i32 = keyIdx + searchKey.length;
  while (start < json.length && json.charAt(start) == ' ') start++;
  let end: i32 = start;
  while (end < json.length && isDigit(json.charAt(end))) end++;
  if (end <= start) return 0;
  let numStr: string = json.substring(start, end);
  return parseI64(numStr);
}

/** Extract a raw JSON array value for a field (preserving array structure). */
function extractRawArray(json: string, field: string): string {
  let searchKey: string = '"' + field + '":[';
  let keyIdx: i32 = indexOf(json, searchKey);
  if (keyIdx < 0) return "";
  let start: i32 = keyIdx + searchKey.length - 1; // include '['
  let depth: i32 = 1;
  let pos: i32 = start + 1;
  while (pos < json.length && depth > 0) {
    if (json.charAt(pos) == '[') depth++;
    if (json.charAt(pos) == ']') depth--;
    pos++;
  }
  return json.substring(start, pos);
}

/** Simple indexOf for strings with optional start position. */
function indexOf(s: string, search: string, start: i32 = 0): i32 {
  if (search.length === 0) return start;
  if (s.length < search.length) return -1;
  let max: i32 = s.length - search.length;
  for (let i: i32 = start; i <= max; i++) {
    let found: bool = true;
    for (let j: i32 = 0; j < search.length; j++) {
      if (s.charAt(i + j) !== search.charAt(j)) {
        found = false;
        break;
      }
    }
    if (found) return i;
  }
  return -1;
}

function isDigit(c: string): bool {
  return c >= "0" && c <= "9";
}

/** Parse a decimal string into an i64 (ASCII digits only). */
function parseI64(s: string): i64 {
  let result: i64 = 0;
  let negative: bool = false;
  let i: i32 = 0;
  if (s.length > 0 && s.charAt(0) == "-") {
    negative = true;
    i = 1;
  }
  while (i < s.length) {
    let c: string = s.charAt(i);
    if (c < "0" || c > "9") break;
    result = result * 10 + (c.charCodeAt(0) - 48);
    i++;
  }
  if (negative) result = -result;
  return result;
}

// ---------------------------------------------------------------------------
// Workflow: place_order
//
// Saga-like orchestration with compensation:
//   1. Reserve inventory
//   2. Charge payment  (on failure: release inventory)
//   3. Create shipment (on failure: refund + release inventory)
//   4. Notify customer (best-effort, no compensation needed)
// ---------------------------------------------------------------------------

@cleatEntry("PlaceOrder")
export function place_order(h: HostCalls, input: string): string {
  // ---- Read and parse input ----
  let userID: string = extractStringField(input, "userID");
  let itemsJson: string = extractRawArray(input, "items");

  if (itemsJson.length <= 2) { // "[]" or empty
    return '{"error":"cart is empty"}';
  }

  // --- Step 1: Reserve inventory -------------------------------------------

  let reserveReq: string = '{"user_id":"' + userID + '","items":' + itemsJson + '}';
  let reserveResult: CleatCallOutcome = h.cleatCall("inventory", "Reserve", reserveReq);
  if (reserveResult.isError) {
    return '{"error":"inventory reserve failed"}';
  }
  let reservationID: string = extractStringField(reserveResult.response, "reservationID");
  let totalCents: i64 = extractI64Field(reserveResult.response, "totalCents");

  // --- Step 2: Charge payment ----------------------------------------------

  let chargeReq: string = '{"user_id":"' + userID + '","amount_cents":' + totalCents.toString() + '}';
  let chargeResult: CleatCallOutcome = h.cleatCall("payments", "Charge", chargeReq);
  if (chargeResult.isError) {
    // Compensate: release the reserved inventory.
    h.cleatCall("inventory", "Release", '{"reservation_id":"' + reservationID + '"}');
    return '{"error":"payment failed"}';
  }
  let chargeID: string = extractStringField(chargeResult.response, "chargeID");

  // --- Step 3: Create shipment --------------------------------------------

  let shipReq: string = '{"reservation_id":"' + reservationID + '","charge_id":"' + chargeID + '"}';
  let shipResult: CleatCallOutcome = h.cleatCall("shipping", "CreateShipment", shipReq);
  if (shipResult.isError) {
    // Compensate: refund the payment and release inventory.
    h.cleatCall("payments", "Refund", '{"charge_id":"' + chargeID + '"}');
    h.cleatCall("inventory", "Release", '{"reservation_id":"' + reservationID + '"}');
    return '{"error":"shipping failed"}';
  }

  // --- Step 4: Notify customer (best-effort) -------------------------------

  h.cleatCall("notifications", "SendEmail", '{"user_id":"' + userID + '","message":"Order shipped"}');

  return '{"status":"shipped","reservation_id":"' + reservationID + '"}';
}

// ---------------------------------------------------------------------------
// Workflow: cancel_order
//
// A cancellation-aware entry point that checks cancellation before proceeding.
// ---------------------------------------------------------------------------

@cleatEntry("CancelOrder")
export function cancel_order(h: HostCalls, input: string): string {
  // ---- Read and parse input ----
  let userID: string = extractStringField(input, "userID");
  let itemsJson: string = extractRawArray(input, "items");

  // ---- Check cancellation ----
  let cancelledStatus = h.pollCancellation();
  if (cancelledStatus.cancelled) {
    return '{"status":"cancelled","reason":"cancelled before processing"}';
  }

  if (itemsJson.length <= 2) {
    return '{"error":"cart is empty"}';
  }

  let reserveReq: string = '{"user_id":"' + userID + '","items":' + itemsJson + '}';
  let reserveResult: CleatCallOutcome = h.cleatCall("inventory", "Reserve", reserveReq);
  if (reserveResult.isError) {
    return '{"error":"inventory reserve failed"}';
  }

  return '{"status":"reserved"}';
}
