// Workflow versioning: the problem that makes WASM loadable modules necessary.
//
// Build & run:
//   GOTOOLCHAIN=local /home/rcownie/go/bin/go build -o /tmp/versioning ./cluster/versioning.go
//   /tmp/versioning

package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.Repeat("=", 72))
	fmt.Println("  Workflow Versioning — Why Loadable Modules Matter")
	fmt.Println(strings.Repeat("=", 72))

	theProblem()
	temporalsApproach()
	wasmApproach()
	hostInterfaceVersioning()
	bottomLine()
}

func theProblem() {
	fmt.Println()
	fmt.Println("── 1. THE PROBLEM ──")
	fmt.Println()
	fmt.Println("  Monday, 09:00:")
	fmt.Println("    Developer deploys PlaceOrder v1.")
	fmt.Println("    User Alice starts an order. The workflow:")
	fmt.Println("      step 0: catalog.LookupItem → OK")
	fmt.Println("      step 1: inventory.Reserve → OK")
	fmt.Println("      step 2: WAIT FOR MANAGER APPROVAL (could take days)")
	fmt.Println()
	fmt.Println("  Tuesday, 14:00:")
	fmt.Println("    Developer deploys PlaceOrder v2.")
	fmt.Println("    v2 changes the order: charge BEFORE inventory check.")
	fmt.Println("    Bob's order starts with v2 code.")
	fmt.Println("    Alice's order is STILL WAITING for approval.")
	fmt.Println()
	fmt.Println("  Wednesday, 03:00:")
	fmt.Println("    Worker node crashes. Alice's workflow is reassigned.")
	fmt.Println("    THE QUESTION: which code does the new worker replay with?")
	fmt.Println()
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  If v2 code replays Alice's v1 event history:              │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │    Event history says:    v2 code expects:                  │")
	fmt.Println("  │    step 0: catalog        step 0: payments.Charge ← DIVERGE│")
	fmt.Println("  │    step 1: inventory      step 1: catalog                   │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  🔴 REPLAY DIVERGENCE → workflow is corrupted               │")
	fmt.Println("  │  🔴 Alice's order is stuck forever                          │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  This is not theoretical. Long-running workflows are the")
	fmt.Println("  NORMAL case in business processes:")
	fmt.Println("    • Loan approval: 2-4 weeks")
	fmt.Println("    • Insurance claim: days to months")
	fmt.Println("    • Employee onboarding: days")
	fmt.Println("    • Order fulfillment with backorder: weeks")
	fmt.Println("    • Any process with human-in-the-loop steps")
	fmt.Println()
}

func temporalsApproach() {
	fmt.Println("── 2. TEMPORAL's APPROACH ──")
	fmt.Println()
	fmt.Println("  Temporal's solution: task queues + GetVersion()")
	fmt.Println()
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  Deployment model:                                          │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  ┌──────────────────┐    ┌──────────────────┐              │")
	fmt.Println("  │  │  Worker Pool A   │    │  Worker Pool B   │              │")
	fmt.Println("  │  │  task_queue: v1  │    │  task_queue: v2  │              │")
	fmt.Println("  │  │  PlaceOrder v1   │    │  PlaceOrder v2   │              │")
	fmt.Println("  │  └────────┬─────────┘    └────────┬─────────┘              │")
	fmt.Println("  │           │                       │                         │")
	fmt.Println("  │           ▼                       ▼                         │")
	fmt.Println("  │  ┌─────────────────────────────────────────────────────┐   │")
	fmt.Println("  │  │              Temporal Matching Service               │   │")
	fmt.Println("  │  │  Routes task_queue=v1 → Pool A                      │   │")
	fmt.Println("  │  │  Routes task_queue=v2 → Pool B                      │   │")
	fmt.Println("  │  └─────────────────────────────────────────────────────┘   │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  Alice's workflow (started on v1): routed to Pool A        │")
	fmt.Println("  │  Bob's workflow (started on v2):   routed to Pool B        │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Operational burden:")
	fmt.Println("    • Must keep old worker pools running until all v1 workflows")
	fmt.Println("      complete (weeks or months)")
	fmt.Println("    • Must manage task queue names and routing")
	fmt.Println("    • Must coordinate worker pool lifecycle with workflow")
	fmt.Println("      completion (drain old pools when empty)")
	fmt.Println("    • GetVersion() API for patching workflow logic within a")
	fmt.Println("      version — complex, error-prone")
	fmt.Println()
	fmt.Println("  This works at scale (Uber does it), but it's operational")
	fmt.Println("  complexity layered on top of the already-complex 4+ services.")
	fmt.Println()
}

func wasmApproach() {
	fmt.Println("── 3. THE WASM LOADABLE-MODULE APPROACH ──")
	fmt.Println()
	fmt.Println("  Instead of routing to different worker pools, each workflow")
	fmt.Println("  instance carries a POINTER to its code version. The worker")
	fmt.Println("  loads the right code from the database at execution time.")
	fmt.Println()
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  ┌──────────┐  ┌──────────┐  ┌──────────┐                 │")
	fmt.Println("  │  │ Worker 1 │  │ Worker 2 │  │ Worker N │                 │")
	fmt.Println("  │  │          │  │          │  │          │                 │")
	fmt.Println("  │  | Load v1 │  | Load v2 │  | Load v1 │                │")
	fmt.Println("  │  | for Alice|  | for Bob |  | for Carol|                │")
	fmt.Println("  │  └────┬─────┘  └────┬─────┘  └────┬─────┘                 │")
	fmt.Println("  │       │              │              │                       │")
	fmt.Println("  │       └──────────────┼──────────────┘                       │")
	fmt.Println("  │                      │                                      │")
	fmt.Println("  │                      ▼                                      │")
	fmt.Println("  │  ┌──────────────────────────────────────────────────────┐  │")
	fmt.Println("  │  │                  PostgreSQL                           │  │")
	fmt.Println("  │  │                                                      │  │")
	fmt.Println("  │  │  workflow_defs:                     event_history:   │  │")
	fmt.Println("  │  │  ┌────────────────────┐             ┌──────────────┐ │  │")
	fmt.Println("  │  │  │ name=PlaceOrder    │             │ wf_id=Alice  │ │  │")
	fmt.Println("  │  │  │ version=1          │◄────────────│ def_version=1│ │  │")
	fmt.Println("  │  │  │ wasm_bytes=<blob>  │             │ step=0: ...  │ │  │")
	fmt.Println("  │  │  └────────────────────┘             └──────────────┘ │  │")
	fmt.Println("  │  │                                                     │  │")
	fmt.Println("  │  │  ┌────────────────────┐             ┌──────────────┐ │  │")
	fmt.Println("  │  │  │ name=PlaceOrder    │             │ wf_id=Bob    │ │  │")
	fmt.Println("  │  │  │ version=2          │◄────────────│ def_version=2│ │  │")
	fmt.Println("  │  │  │ wasm_bytes=<blob>  │             │ step=0: ...  │ │  │")
	fmt.Println("  │  │  └────────────────────┘             └──────────────┘ │  │")
	fmt.Println("  │  └──────────────────────────────────────────────────────┘  │")
	fmt.Println("  │                                                             │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Key properties:")
	fmt.Println()
	fmt.Println("  1. Worker binary NEVER changes for workflow version deploys.")
	fmt.Println("     Workers are a stable runtime (like a JVM or WASM runtime).")
	fmt.Println()
	fmt.Println("  2. Deploying v2 = INSERT INTO workflow_defs. No worker restart.")
	fmt.Println()
	fmt.Println("  3. Alice's workflow (v1) and Bob's workflow (v2) run on the")
	fmt.Println("     SAME worker, even in the SAME goroutine pool.")
	fmt.Println()
	fmt.Println("  4. When all v1 workflows complete (Alice's finishes), v1 can")
	fmt.Println("     be marked deprecated. No worker pools to drain.")
	fmt.Println()
	fmt.Println("  5. The worker just needs to know the host interface — which")
	fmt.Println("     is versioned separately and must be backwards-compatible.")
	fmt.Println()
}

func hostInterfaceVersioning() {
	fmt.Println("── 4. HOST INTERFACE COMPATIBILITY ──")
	fmt.Println()
	fmt.Println("  The worker provides host functions to the WASM module:")
	fmt.Println("    • durable_call(service, operation, request) → (response, error)")
	fmt.Println("    • durable_log(message)")
	fmt.Println("    • durable_now() → timestamp")
	fmt.Println()
	fmt.Println("  This interface IS a versioned API contract. There are three")
	fmt.Println("  kinds of changes:")
	fmt.Println()
	fmt.Println("  ┌──────────────────┬─────────────────────────────────────────┐")
	fmt.Println("  │ Change            │ Strategy                                │")
	fmt.Println("  ├──────────────────┼─────────────────────────────────────────┤")
	fmt.Println("  │ Add new host      │ Safe: old WASM modules don't import it. │")
	fmt.Println("  │ function          │ New modules can use it.                 │")
	fmt.Println("  ├──────────────────┼─────────────────────────────────────────┤")
	fmt.Println("  │ Change host func  │ NOT safe: requires host API versioning. │")
	fmt.Println("  │ signature         │ Worker must support multiple host API   │")
	fmt.Println("  │                   │ versions. Imports encode which version  │")
	fmt.Println("  │                   │ they need (e.g., durable_call_v2).      │")
	fmt.Println("  ├──────────────────┼─────────────────────────────────────────┤")
	fmt.Println("  │ Remove host func  │ NOT safe while any module imports it.   │")
	fmt.Println("  │                   │ Deprecation period → check DB for       │")
	fmt.Println("  │                   │ active modules using it.                │")
	fmt.Println("  └──────────────────┴─────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  This is manageable because the host interface surface area")
	fmt.Println("  is SMALL (3-5 functions) and changes rarely. It's not like")
	fmt.Println("  a user-facing API with hundreds of endpoints.")
	fmt.Println()
	fmt.Println("  The workflow definitions change frequently (business logic).")
	fmt.Println("  The host interface changes slowly (durable execution runtime).")
	fmt.Println("  These are different versioning cadences, decoupled by WASM.")
	fmt.Println()
}

func bottomLine() {
	fmt.Println("── 5. WHAT THIS MEANS FOR THE ARCHITECTURE ──")
	fmt.Println()
	fmt.Println("  The WASM compilation step is NOT primarily about security.")
	fmt.Println("  It's about making workflow code a versioned artifact that is")
	fmt.Println("  stored in the database and loaded on demand, decoupled from")
	fmt.Println("  the worker binary lifecycle.")
	fmt.Println()
	fmt.Println("  Temporal's alternative — versioned task queues + multiple")
	fmt.Println("  worker pools + GetVersion() patching — is proven but requires")
	fmt.Println("  operating multiple stateful services with overlapping")
	fmt.Println("  lifecycles. The WASM approach collapses this to:")
	fmt.Println()
	fmt.Println("    • One worker binary (the wazero host, stable)")
	fmt.Println("    • One database (workflow code + state, versioned together)")
	fmt.Println()
	fmt.Println("  The operational win: deploying a new workflow version is a")
	fmt.Println("  database INSERT, not a service deployment. Rolling back is")
	fmt.Println("  a database UPDATE (mark version deprecated). No worker pool")
	fmt.Println("  lifecycle to manage, no task queue routing, no draining.")
	fmt.Println()
	fmt.Println("  ── Comparison ──")
	fmt.Println()
	fmt.Println("  ┌────────────────────┬──────────────────┬────────────────────┐")
	fmt.Println("  │ Concern            │ Temporal          │ WASM Loadable      │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ Deploy new wf ver  │ Deploy new worker │ INSERT wasm_bytes  │")
	fmt.Println("  │                    │ pool + route      │                    │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ Old wf still runs  │ Keep old pool     │ Same workers, load │")
	fmt.Println("  │                    │ running (weeks)   │ old blob from DB   │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ Rollback           │ Deploy old worker │ UPDATE deprecation │")
	fmt.Println("  │                    │ pool, reroute     │ flag in DB         │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ Deprecate old ver  │ Drain queue,      │ Wait for active    │")
	fmt.Println("  │                    │ shut down pool    │ instances to finish│")
	fmt.Println("  │                    │                   │ (queryable!)       │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ Worker upgrade     │ Redeploy all      │ Deploy new worker  │")
	fmt.Println("  │ (new host API)     │ pools             │ binary ONCE        │")
	fmt.Println("  │                    │                   │ (host interface)   │")
	fmt.Println("  ├────────────────────┼──────────────────┼────────────────────┤")
	fmt.Println("  │ In-flight wf        │ GetVersion() API  │ v1 WASM blob stays │")
	fmt.Println("  │ logic change        │ (in-workflow)     │ unchanged; new execs│")
	fmt.Println("  │                     │                   │ use new blob       │")
	fmt.Println("  └────────────────────┴──────────────────┴────────────────────┘")
	fmt.Println()
	fmt.Println("  This is the real argument for WASM: it makes workflow code")
	fmt.Println("  a pure data artifact — versioned, stored, loaded, and garbage")
	fmt.Println("  collected — independent of the runtime that executes it.")
	fmt.Println()
}
