apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cleat.fullname" . }}
  labels:
    {{- include "cleat.labels" . | nindent 4 }}
data:
  database-url: "postgres://{{ .Values.postgres.username }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}?sslmode={{ .Values.postgres.sslmode }}"
