{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cleat.fullname" . }}
  labels:
    {{- include "cleat.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "cleat.databaseURL" . | b64enc | quote }}
{{- end }}
{{- if and (not .Values.auth.existingSecret) .Values.auth.adminApiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cleat.fullname" . }}-auth
  labels:
    {{- include "cleat.labels" . | nindent 4 }}
type: Opaque
data:
  admin-api-key: {{ .Values.auth.adminApiKey | b64enc | quote }}
{{- end }}
