#!/usr/bin/env python3
"""Curly quotes in Python sources -- and why Go is deliberately OUT of scope (cleat#2987).

WHAT THIS CHECKS

A "smart quote" pass -- a word processor, a chat client, an editor plugin, a
copy-paste through something that thinks it is helping -- turns a straight quote
into a curly one. In source that is a defect: the character is not the one the
code or the comment intended, it renders as an ordinary quote so it is invisible
in review, and no linter here sees it.

This check refuses U+2018, U+2019, U+201C and U+201D in tracked `.py` files.

WHY GO IS NOT CHECKED, WHICH IS THE FINDING THIS PR IS ACTUALLY ABOUT

cleat#2987 reported 24 curly quotes across 12 files and asked for a guard over Go
and Python sources. All 24 are in `.go` files, and they are there because **gofmt
puts them there**. Measured 2026-10-02 with a probe and the tree:

    in a comment gofmt treats as documentation, gofmt rewrites
                                      ''  ->  U+201D
                                      ``  ->  U+201C

"Documentation comment" is the precise scope, and it took a probe to get right.
gofmt rewrites `''` in a comment attached to a declaration AND in the one above the
`package` clause, including inside a backtick code span. A comment separated from
its declaration by a blank line, an inline comment inside a function body, and an
end-of-file comment are all left alone; string literals and `""` are untouched
everywhere. An earlier draft of this docstring said "free-floating comment" -- true
at the top of a file, false in the middle -- and a reader who probes it finds the
difference.

So a curly quote in a doc comment is a *fixpoint*: `lint-go`'s own `gofmt -l`
accepts the file, and `''` is rewritten back on the next `gofmt -w`. The first
version of this PR repaired all 24 to ASCII, and CI's `gofmt -l` refused exactly
the 10 files that had taken a `''` repair while accepting the 2 that had not
(`build_python.go`, whose repair used `"`, and `mysql_tenant_predicate_test.go`,
whose repair used a backtick) -- 10 of 10 and 2 of 2.

That oracle answers "is this curly character what gofmt makes of `''`", which is
not the same question as "can this site be written in ASCII at all", and conflating
the two is how an earlier draft of this file came to claim no site was repairable.
The predicate is what matters, not the count: a site whose curly character stands
for a QUOTE PAIR has no ASCII form gofmt keeps, and a site whose curly character
stands for `"` can simply be written `"`. For the record, since an earlier draft of
this docstring understated it -- all 11 of the `"` sites are repairable: CI accepted
the 9 in build_python.go and mysql_tenant_predicate_test.go, and the remaining 2
became `""`, which gofmt leaves alone.

The transient form is not unguarded, it is guarded by something better: write
`''` in a Go comment and `gofmt -l`, already a step in `lint-go`, fails the job.
So Go is excluded from this check on purpose, with the reason recorded here rather
than the exclusion left to be discovered by whoever next wonders why.

That leaves the Python half, where nothing normalizes anything and the codepoints
really are mistakes. It is not redundant with the linters already running: `ruff
check python-sdk/` reads only that directory, so every Python file outside it --
including `cmd/cleat/templates/agent-python/agent.py`, which is shipped to users --
is unguarded today.

SCOPE AND THE TWO EXCLUSIONS

  * The population is tracked files ending in `.py`, from `git ls-files` rather
    than from a walk of the tree, so a scratch checkout under .claude/worktrees is
    not mistaken for the repository -- the same reason check-go-toolchain-pins.py
    reads git ls-files.
  * `python-sdk/cleat_sdk/_wit/` is skipped. Its 27 .py files are generated by
    componentize-py, and `python-sdk/pyproject.toml` excludes that same path from
    ruff for the same reason: it is not ours to lint or to fix.
  * Binary files are skipped: a compiled fixture can hold byte sequences that
    decode to these codepoints by accident, and nobody can edit them.

MEASURED 2026-10-02, and stated because an exclusion that never fires cannot be
told from one that does not work: 136 tracked .py files, 0 of them containing any
of the four codepoints, and 0 of them binary. Neither exclusion fires on today's
tree. Both are kept, and both have a `--self-test` case that makes them fire.

EXIT STATUS, and why there are three:

  0  no curly quote in any Python file that was scanned
  1  a finding: at least one is present, each reported as path:line:col
  2  UNMEASURED: the population could not be established -- `git ls-files` failed,
     or it returned fewer files than MIN_FILES. A scan that finds nothing agrees
     with every tree, correct or not, so finding nothing is reported as a failure
     of the CHECK and never as a pass. See CLAUDE.md, "Is this result real?".

`--self-test` builds fixture trees and asserts on the TEXT of each verdict, not
only on the status.
"""
import os
import subprocess
import sys
import tempfile

# Built with chr() rather than written as literals or as \u escapes, because this
# file is a .py file and therefore INSIDE its own population: a literal quotation
# mark here would make the check fail on itself. A \u escape is no better -- it is
# silently decoded to the character by much of the tooling this file passes
# through. chr(0x201C) is the same character with nothing to decode.
CURLY = {
    chr(0x2018): "U+2018 LEFT SINGLE QUOTATION MARK",
    chr(0x2019): "U+2019 RIGHT SINGLE QUOTATION MARK",
    chr(0x201C): "U+201C LEFT DOUBLE QUOTATION MARK",
    chr(0x201D): "U+201D RIGHT DOUBLE QUOTATION MARK",
}

SOURCE_SUFFIXES = (".py",)
# Generated, in the same words python-sdk/pyproject.toml's ruff `exclude` uses.
EXCLUDED_PREFIXES = ("python-sdk/cleat_sdk/_wit/",)
# Tracks .py today (2026-10-02): 136, of which 109 are scanned (27 generated).
# Fewer than this means the scan read the wrong files.
MIN_FILES = 50


class Unmeasured(Exception):
    pass


def tracked_source_files(root):
    try:
        out = subprocess.run(["git", "-C", root, "ls-files", "-z", "*.py"],
                             capture_output=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise Unmeasured(f"git ls-files failed in {root}: {e}")
    return sorted(f for f in out.decode().split("\0") if f)


def is_excluded(rel: str) -> bool:
    rel = rel.replace(os.sep, "/")
    return any(rel.startswith(p) for p in EXCLUDED_PREFIXES)


def is_binary(data: bytes) -> bool:
    """git's own heuristic, near enough: a NUL byte in the content, or not UTF-8."""
    if b"\0" in data:
        return True
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return True
    return False


def scan_text(rel, text):
    hits = []
    for lineno, line in enumerate(text.split("\n"), 1):
        for col, ch in enumerate(line, 1):
            if ch in CURLY:
                hits.append((rel, lineno, col, ch, line.strip()))
    return hits


def check(root):
    files = tracked_source_files(root)
    scanned = excluded = binary = 0
    hits = []
    for rel in files:
        if is_excluded(rel):
            excluded += 1
            continue
        with open(os.path.join(root, rel), "rb") as fh:
            data = fh.read()
        if is_binary(data):
            binary += 1
            continue
        hits.extend(scan_text(rel, data.decode("utf-8")))
        scanned += 1
    if scanned < MIN_FILES:
        raise Unmeasured(f"scanned {scanned} tracked Python files, expected at least "
                         f"{MIN_FILES}: the scan read the wrong files")
    return hits, {"scanned": scanned, "excluded": excluded, "binary": binary}


def main(root):
    try:
        hits, facts = check(root)
    except Unmeasured as e:
        print(f"UNMEASURED: {e}", file=sys.stderr)
        print("This is a failure of the check, not a finding about the tree.", file=sys.stderr)
        return 2
    if hits:
        print(f"check-curly-quotes: {len(hits)} curly quote(s) in Python sources:")
        for rel, lineno, col, ch, line in hits:
            print(f"  {rel}:{lineno}:{col}: {CURLY[ch]}")
            print(f"      {line}")
        print("\nReplace each with the ASCII character that was meant: a straight \" or\n"
              "a straight ' for a quotation, or '' for an empty-string literal. Do not\n"
              "simply delete it.")
        return 1
    print(f"check-curly-quotes: OK, no curly quotes in {facts['scanned']} tracked Python "
          f"files ({facts['excluded']} generated, {facts['binary']} binary skipped)")
    print("  Go sources are out of scope on purpose: gofmt rewrites '' and `` to curly\n"
          "  quotes in Go comments, so a Go check would flag a state gofmt enforces. See\n"
          "  this script's docstring and cleat#2987.")
    return 0


# -------------------------------------------------------------------------------------------------
# self-test
# -------------------------------------------------------------------------------------------------

LSQ, RSQ = chr(0x2018), chr(0x2019)
LDQ, RDQ = chr(0x201C), chr(0x201D)

# Straight quotes only: the control. A checker that flagged every quotation mark
# would pass each case below and fail this one.
CLEAN_PY = '# a "double" and a \'single\' straight quote are fine.\nx = "y"\n'
CURLY_PY = "# a " + RSQ + "curly single" + LSQ + " quote\nx = 1\n"
# The shape that cost this PR a CI cycle: gofmt rewrites '' in a Go comment to a
# curly quote, so a tree full of these is gofmt-CLEAN and must not be reported.
CURLY_GO = "package a\n\n// the " + LDQ + "flag" + RDQ + " became curly\n"


def run_fixture(files, min_files=1):
    global MIN_FILES
    old = MIN_FILES
    MIN_FILES = min_files
    try:
        with tempfile.TemporaryDirectory() as d:
            subprocess.run(["git", "init", "-q", d], check=True)
            for rel, content in files.items():
                p = os.path.join(d, rel)
                os.makedirs(os.path.dirname(p) or d, exist_ok=True)
                with open(p, "wb" if isinstance(content, bytes) else "w") as fh:
                    fh.write(content)
            subprocess.run(["git", "-C", d, "add", "-A", "-f"], check=True)
            import io
            from contextlib import redirect_stderr, redirect_stdout
            out, err = io.StringIO(), io.StringIO()
            with redirect_stdout(out), redirect_stderr(err):
                rc = main(d)
            return rc, out.getvalue() + err.getvalue()
    finally:
        MIN_FILES = old


def self_test():
    failures = []

    def expect(name, files, want_rc, want_text, **kw):
        rc, text = run_fixture(files, **kw)
        ok = rc == want_rc and want_text in text
        print(f"  {'ok  ' if ok else 'FAIL'} {name}: rc={rc} (want {want_rc}), "
              f"text has {want_text!r}: {want_text in text}")
        if not ok:
            failures.append(name)
            print(text)

    print("check-curly-quotes --self-test")
    # The known-negative first, deliberately: a version of this check that flagged
    # every quotation mark passes each positive below and fails only this one.
    expect("straight quotes only", {"a.py": CLEAN_PY}, 0, "OK, no curly quotes")
    expect("a curly single in a Python file", {"a.py": CURLY_PY}, 1, "U+2018")
    expect("the finding names path:line:col", {"a.py": CURLY_PY}, 1, "a.py:1:")
    # The scope decision, pinned as a case: Go comments are gofmt's business.
    expect("a curly quote in a .go comment is OUT of scope",
           {"a.py": CLEAN_PY, "b.go": CURLY_GO}, 0, "OK, no curly quotes")
    expect("and the success line says so",
           {"a.py": CLEAN_PY}, 0, "Go sources are out of scope on purpose")
    # The two exclusions, each required to FIRE.
    expect("a .py under the generated _wit tree is skipped",
           {"a.py": CLEAN_PY, "python-sdk/cleat_sdk/_wit/wit.py": CURLY_PY},
           0, "1 generated")
    expect("a binary .py file (NUL byte) is skipped",
           {"a.py": CLEAN_PY, "blob.py": b"# " + LDQ.encode() + b"\x00\n"}, 0, "1 binary")
    expect("a non-UTF-8 .py file is skipped",
           {"a.py": CLEAN_PY, "blob2.py": b"# " + LDQ.encode() + b"\xff\xfe\n"}, 0, "1 binary")
    # UNMEASURED, both causes: nothing to scan, and not enough to scan.
    expect("an empty population is UNMEASURED, not a pass",
           {"README.md": "x\n"}, 2, "UNMEASURED")
    expect("a population under the floor is UNMEASURED",
           {"a.py": CLEAN_PY}, 2, "expected at least 50", min_files=50)
    if failures:
        print(f"SELF-TEST FAILED: {failures}")
        return 1
    print("self-test passed")
    return 0


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--self-test":
        sys.exit(self_test())
    root = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.exit(main(root))
