#!/usr/bin/env bash
#
# The known-positive battery for the MSSQL baseline generated by
# scripts/gen-mssql-baseline. cleat#2434.
#
# A clean diff is worth nothing until the checks have been shown CATCHING a
# deliberate difference, and each compared class needs its own case: a check
# that passes is satisfied by every broken version of itself, so "it went green
# on a good tree" is not evidence.
#
# The cases split into two kinds, and the second kind is the point of the whole
# exercise:
#
#   * catalogdiff catches it  -- proves the main acceptance instrument works.
#   * catalogdiff is CLEAN and the supplementary check catches it -- proves the
#     supplementary check is not decoration. Every one of these classes is
#     invisible to migration/catalogdiff/mssql.go by construction: it compares a
#     column's type NAME but not its width, and an index's key columns but not
#     its filter. A baseline could lose every column width and every filtered
#     index and still report an empty diff.
#
#     Security policies/predicates, schemas and database roles used to be in
#     this second group too, until cleat#2432 moved them into catalogdiff
#     itself -- they are now "catalogdiff catches it" cases (below), and the
#     supplementary checks no longer read sys.security_policies or
#     sys.database_principals at all. Trigger is_disabled stayed supplementary
#     (catalogdiff compares a trigger's name/body/schema, not its settings),
#     so disabling a trigger is still a "supplementary check catches it" case.
#
# Usage: scripts/mssql-baseline-known-positive.sh <A-dsn> <B-dsn>
#
# A must already be built from the chain and B must be REBUILDABLE from the
# generated files; this script rebuilds B before every case, so each case starts
# from a known-good B. That rebuild is what makes the identity control (case 0)
# meaningful rather than a restatement of the previous case's state.

set -u

A_DSN="${1:?usage: $0 <A-dsn> <B-dsn>}"
B_DSN="${2:?usage: $0 <A-dsn> <B-dsn>}"
CONTAINER="${CLEAT_MSSQL_CONTAINER:-ws2-2340-mssql}"
SA_PASSWORD="${CLEAT_MSSQL_SA_PASSWORD:-CleatTest123!}"
B_DB="${CLEAT_MSSQL_B_DB:-cleat_core_b}"
REPO="${CLEAT_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "$REPO" || exit 1

# -b is load-bearing: without it sqlcmd exits 0 even when the batch fails, so
# every failed mutation would be reported as "applied and made no difference" --
# the case would pass or fail on a tree it never touched. That is the
# "operation reports success without doing the thing" trap, inside the harness
# whose whole job is to prove the checks can fail.
sql() {
    docker exec "$CONTAINER" /opt/mssql-tools18/bin/sqlcmd \
        -S localhost -U sa -P "$SA_PASSWORD" -C -b -d "$B_DB" -Q "$1" >/dev/null 2>&1
}

rebuild_b() {
    "${REBUILD_B:-/tmp/rebuild_b.sh}" >/dev/null 2>&1
}

# Prints "diff=<clean|CATCH> supp=<pass|CATCH>".
check() {
    local d s
    if go run ./scripts/gen-mssql-baseline -mode=diff -dsn "$A_DSN" -bdsn "$B_DSN" >/dev/null 2>&1; then
        d=clean
    else
        d=CATCH
    fi
    if go run ./scripts/gen-mssql-baseline -mode=supplementary -dsn "$A_DSN" -bdsn "$B_DSN" >/dev/null 2>&1; then
        s=pass
    else
        s=CATCH
    fi
    echo "diff=$d supp=$s"
}

fails=0
case_no=0

# expect <label> <want-diff> <want-supp> <mutation-sql>
expect() {
    local label="$1" want_d="$2" want_s="$3" mut="$4"
    case_no=$((case_no + 1))
    rebuild_b
    if [ -n "$mut" ]; then
        if ! sql "$mut"; then
            printf '%-4s %-46s UNMEASURED (mutation did not apply)\n' "$case_no" "$label"
            fails=$((fails + 1))
            return
        fi
    fi
    local got
    got=$(check)
    # Parameter expansion rather than sed: shellcheck's SC2001, and the parse is
    # simple enough that a subprocess buys nothing.
    local gd gs
    gd="${got#*diff=}"; gd="${gd%% *}"
    gs="${got#*supp=}"; gs="${gs%% *}"
    if [ "$gd" = "$want_d" ] && [ "$gs" = "$want_s" ]; then
        printf '%-4s %-46s %-18s ok\n' "$case_no" "$label" "$got"
    else
        printf '%-4s %-46s %-18s WANT diff=%s supp=%s\n' \
            "$case_no" "$label" "$got" "$want_d" "$want_s"
        fails=$((fails + 1))
    fi
}

echo "== identity control: B rebuilt from the same files as A, no mutation =="
expect "no mutation (identity control)" clean pass ""

echo
echo "== classes catalogdiff catches =="
# deployment_secrets.disabled_at, chosen because it is genuinely standalone:
# a column chosen for convenience usually has a default constraint, an index or
# a check depending on it, and the ALTER then fails with "one or more objects
# access this column" -- which the harness reports as UNMEASURED, exercising
# nothing. Two earlier picks (admin.orgs.name, workflow_defs.entry_points) did
# exactly that.
expect "drop a column" CATCH CATCH \
    "ALTER TABLE dbo.deployment_secrets DROP COLUMN disabled_at"
expect "drop an index" CATCH CATCH \
    "DROP INDEX idx_event_history_pending ON dbo.event_history"
# supp=pass is correct here, not a gap: check constraints ARE a class
# catalogdiff reads (by name and definition), so the supplementary checks
# deliberately do not duplicate it. Expecting a supplementary catch would have
# been expecting the wrong instrument.
expect "drop a check constraint" CATCH pass \
    "ALTER TABLE dbo.workflow_update_requests DROP CONSTRAINT ck_workflow_update_requests_payload"
expect "alter a routine body" CATCH CATCH \
    "EXEC('ALTER PROCEDURE dbo.finalize_workflow_status AS BEGIN SELECT 1 END')"
# These two moved here from "classes ONLY the supplementary checks can see"
# when cleat#2432 moved security policies and database roles into catalogdiff
# itself. supp=pass is correct, not a gap, for the same reason "drop a check
# constraint" above is: the supplementary checks deliberately don't duplicate
# a class catalogdiff now reads.
expect "DROP A SECURITY POLICY" CATCH pass \
    "DROP SECURITY POLICY dbo.TenantFilter_Defs"
expect "drop the cleat_admin role" CATCH pass \
    "DROP ROLE cleat_admin"

echo
echo "== classes ONLY the supplementary checks can see =="
# task_queue, not name: workflow_defs.name is part of the primary key, so
# ALTER COLUMN on it fails with "The index 'pk_workflow_defs' is dependent on
# column 'name'" and the case would report UNMEASURED rather than exercising
# anything.
expect "widen a column (nvarchar 255 -> 300)" clean CATCH \
    "ALTER TABLE dbo.workflow_defs ALTER COLUMN task_queue nvarchar(300) NOT NULL"
# SET QUOTED_IDENTIFIER ON is required and is not incidental: without it the
# CREATE fails with "the following SET options have incorrect settings:
# 'QUOTED_IDENTIFIER'", because sqlcmd's default differs from the setting the
# migration runner uses. The filter is changed from `[checksum] IS NULL` to
# `IS NOT NULL` -- a bare `AND 1=1` is rejected as an "incorrect WHERE clause
# for filtered index", since a clause that is always true cannot be a filter.
expect "change a filtered index's filter" clean CATCH \
    "SET QUOTED_IDENTIFIER ON;
     DROP INDEX idx_event_history_pending ON dbo.event_history;
     CREATE NONCLUSTERED INDEX idx_event_history_pending ON dbo.event_history ([workflow_id],[step]) WHERE [intent_at] IS NOT NULL AND [checksum] IS NOT NULL"
expect "insert a seed row" clean CATCH \
    "INSERT INTO admin.orgs (org_id, name) VALUES ('11111111-1111-1111-1111-111111111111', N'intruder')"
# Proves G1's fix: catalogdiff compares a trigger's name/body/schema, not its
# settings, so a disabled trigger is invisible to -mode=diff by the same
# construction as every other case in this section. Module settings'
# is_disabled column (supplementary.go) is the only thing that catches it.
expect "disable a trigger" clean CATCH \
    "DISABLE TRIGGER admin.trg_tenants_org_id_immutable ON admin.tenants"

echo
echo "== restore B and confirm it is clean again =="
expect "rebuilt, no mutation" clean pass ""

echo
if [ "$fails" -eq 0 ]; then
    echo "known-positive battery: all $case_no case(s) behaved as expected"
else
    echo "known-positive battery: $fails of $case_no case(s) DID NOT match expectation"
    exit 1
fi
