// Analysis: making PostgreSQL the rock-solid source of truth for durable workflows.
//
// In this system, PostgreSQL stores the event history that IS the workflow's
// memory. Every durable_call records its result. On replay, the cached results
// are replayed in order. If the database is lost:
//
//   - A workflow that already charged a credit card has no record of it
//   - On resume, it will re-execute the charge (double charge) or fail
//   - The compensation chain is broken (refund relies on having the charge_id)
//
// The database is not optional. It must survive:
//   - Disk failure
//   - Machine failure
//   - Availability zone failure
//   - Operator error (accidental DROP TABLE)
//   - Corruption (bit rot, bad controller, PostgreSQL bug)
//
// Build it into the binary:
//   GOTOOLCHAIN=local /home/rcownie/go/bin/go build -o /tmp/pg_resilience ./cluster/postgres_resilience.go
//   /tmp/pg_resilience

package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.Repeat("=", 72))
	fmt.Println("  PostgreSQL Resilience for Durable Workflow State")
	fmt.Println(strings.Repeat("=", 72))

	failureModes()
	minimumSetup()
	streamingReplication()
	patroniAutoFailover()
	walArchivingPitr()
	operatorSafety()
	verification()
	stagedRecommendation()
}

func failureModes() {
	fmt.Println()
	fmt.Println("── 1. WHAT ACTUALLY KILLS DATABASES ──")
	fmt.Println()
	fmt.Println("  Failure mode              Likelihood    Impact on this system")
	fmt.Println("  ─────────────────────     ──────────    ─────────────────────")
	fmt.Println("  Disk failure              Low/medium    Complete data loss if")
	fmt.Println("                            (1-3% AFR)    no replica. All in-flight")
	fmt.Println("                                         workflows unrecoverable.")
	fmt.Println()
	fmt.Println("  Machine failure (PSU,      Medium       Same as disk if no replica.")
	fmt.Println("  RAM, motherboard)         (3-5% AFR)")
	fmt.Println()
	fmt.Println("  Operator error            HIGH          DROP TABLE, DELETE without")
	fmt.Println("  (wrong command, wrong     (most common   WHERE, or bad migration.")
	fmt.Println("   terminal)                 cause)        WAL replay can't help if")
	fmt.Println("                                          the mistake was committed.")
	fmt.Println()
	fmt.Println("  Network partition          Low/medium    Split brain: two primaries")
	fmt.Println("  (split brain)             (cloud-dep)   accepting writes. Workflows")
	fmt.Println("                                          assigned to both; divergent")
	fmt.Println("                                          event histories.")
	fmt.Println()
	fmt.Println("  Corruption (bit rot,       Rare but      Silently wrong data. Replay")
	fmt.Println("  bad controller, PG bug)   happens)       returns wrong cached result.")
	fmt.Println("                                          Workflow makes wrong decision")
	fmt.Println("                                          based on corrupted state.")
	fmt.Println()
	fmt.Println("  AZ/region failure          Rare          Database unavailable. All")
	fmt.Println("                            (once/decade)  workflows stall. No workers")
	fmt.Println("                                          can claim or heartbeat.")
	fmt.Println()
	fmt.Println("  Key insight: operator error is MORE likely than disk failure.")
	fmt.Println("  Replication alone doesn't protect against 'oops, wrong WHERE clause'.")
	fmt.Println()
}

func minimumSetup() {
	fmt.Println("── 2. THE NON-NEGOTIABLE MINIMUM ──")
	fmt.Println()
	fmt.Println("  Before considering HA tooling, these are table stakes:")
	fmt.Println()
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  1. SYNCHRONOUS streaming replication to a hot standby      │")
	fmt.Println("  │     (not async — see below for why)                         │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  2. WAL archiving to S3/GCS (continuous, not periodic)      │")
	fmt.Println("  │     archive_command = 'wal-g wal-push %p'                  │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  3. Daily base backups with PITR capability                 │")
	fmt.Println("  │     (point-in-time recovery to any second)                  │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  4. statement_timeout set globally                          │")
	fmt.Println("  │     (prevents rogue queries from taking locks forever)      │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  5. MONITORING: replication lag, WAL archival lag,          │")
	fmt.Println("  │     disk space, connection count                            │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
}

func streamingReplication() {
	fmt.Println("── 3. SYNC vs ASYNC REPLICATION ──")
	fmt.Println()
	fmt.Println("  Async replication (the PostgreSQL default):")
	fmt.Println("    Primary commits → returns to client → sends WAL to replica.")
	fmt.Println("    If the primary crashes between steps 2 and 3, the committed")
	fmt.Println("    transaction is LOST. The replica never saw it. The client")
	fmt.Println("    was told 'success' but the data is gone.")
	fmt.Println()
	fmt.Println("    ┌──────────┐    ① COMMIT         ┌──────────┐")
	fmt.Println("    │  Worker  │ ──────────────────→ │  Primary │")
	fmt.Println("    │ (client) │ ←──── ② OK ─────── │          │")
	fmt.Println("    └──────────┘                     │          │")
	fmt.Println("                                     │ ③ WAL → │ ──→ Replica (maybe)")
	fmt.Println("                                     └──────────┘")
	fmt.Println("                               💥 CRASH HERE = LOST DATA")
	fmt.Println()
	fmt.Println("  For durable workflows, this is UNACCEPTABLE. A worker writes")
	fmt.Println("  payments.Charge result → gets OK → primary crashes → charge")
	fmt.Println("  result is lost → on resume, the workflow either double-charges")
	fmt.Println("  or hits a replay divergence.")
	fmt.Println()
	fmt.Println("  Synchronous replication fixes this:")
	fmt.Println()
	fmt.Println("    ┌──────────┐    ① COMMIT         ┌──────────┐    ② WAL      ┌──────────┐")
	fmt.Println("    │  Worker  │ ──────────────────→ │  Primary │ ────────────→ │  Standby │")
	fmt.Println("    │          │ ←──── ④ OK ─────── │          │ ←── ③ ACK ── │          │")
	fmt.Println("    └──────────┘                     └──────────┘               └──────────┘")
	fmt.Println()
	fmt.Println("  The commit doesn't return to the client until the standby has")
	fmt.Println("  written the WAL to disk. Primary crash → standby has all data.")
	fmt.Println()
	fmt.Println("  The tradeoff: synchronous = higher commit latency. For durable")
	fmt.Println("  workflows, each durable_call is an INSERT into event_history.")
	fmt.Println("  The sync replication latency adds ~1-5ms to each call (network")
	fmt.Println("  RTT to the standby). Since durable_calls are already ~10-100ms")
	fmt.Println("  (real HTTP calls), this overhead is negligible.")
	fmt.Println()
	fmt.Println("  Configuration:")
	fmt.Println()
	fmt.Println("    -- On primary:")
	fmt.Println("    synchronous_commit = remote_write   -- wait for standby disk write")
	fmt.Println("    synchronous_standby_names = 'standby1'")
	fmt.Println()
	fmt.Println("    -- On standby:")
	fmt.Println("    primary_conninfo = 'host=primary port=5432 ...'")
	fmt.Println()
}

func patroniAutoFailover() {
	fmt.Println("── 4. AUTOMATIC FAILOVER WITH PATRONI ──")
	fmt.Println()
	fmt.Println("  Manual failover (SSH in, run pg_ctl promote) means:")
	fmt.Println("    • Mean Time To Recovery (MTTR) = human response time = 5-30 min")
	fmt.Println("    • During those 30 minutes, ALL workflows are stuck")
	fmt.Println("    • Workers can't heartbeat → workflows get reassigned by timeout")
	fmt.Println("    • But... event_history writes fail → workers crash or hang")
	fmt.Println()
	fmt.Println("  Patroni automates this. It's the standard tool for PostgreSQL HA:")
	fmt.Println()
	fmt.Println("  ┌──────────────────────────────────────────────────────────────┐")
	fmt.Println("  │                      ETCD / CONSUL (3 nodes)                 │")
	fmt.Println("  │  Distributed consensus: which PG node is the primary?        │")
	fmt.Println("  └────┬─────────────────────┬─────────────────────┬────────────┘")
	fmt.Println("       │                     │                     │")
	fmt.Println("       ▼                     ▼                     ▼")
	fmt.Println("  ┌──────────┐         ┌──────────┐         ┌──────────┐")
	fmt.Println("  │ Patroni  │         │ Patroni  │         │ Patroni  │")
	fmt.Println("  │  + PG    │         │  + PG    │         │  + PG    │")
	fmt.Println("  │ PRIMARY  │ ──sync──│ STANDBY  │ ──async─│ STANDBY  │")
	fmt.Println("  │ (AZ-a)   │         │ (AZ-b)   │         │ (AZ-c)   │")
	fmt.Println("  └──────────┘         └──────────┘         └──────────┘")
	fmt.Println()
	fmt.Println("  What happens when the primary dies:")
	fmt.Println("    1. Patroni on primary stops sending leader-keepalive to etcd")
	fmt.Println("    2. After ttl (30s), etcd considers the leader slot vacant")
	fmt.Println("    3. Patroni on SYNC standby acquires the leader lock in etcd")
	fmt.Println("    4. Patroni promotes standby to primary (pg_ctl promote)")
	fmt.Println("    5. Patroni reconfigures the async standby to replicate from")
	fmt.Println("       the new primary")
	fmt.Println("    6. Client connections break → workers reconnect → continue")
	fmt.Println()
	fmt.Println("  MTTR: ~30-60 seconds. No human intervention.")
	fmt.Println()
	fmt.Println("  CRITICAL: etcd itself must be 3 nodes (separate VMs), or managed")
	fmt.Println("  etcd (AWS, GCP, or something like etcd-operator on Kubernetes).")
	fmt.Println("  Patroni without reliable etcd can't do safe failover.")
	fmt.Println()
}

func walArchivingPitr() {
	fmt.Println("── 5. WAL ARCHIVING & POINT-IN-TIME RECOVERY ──")
	fmt.Println()
	fmt.Println("  Replication protects against hardware failure. It does NOT")
	fmt.Println("  protect against:")
	fmt.Println("    • Operator runs DROP TABLE event_history; (replicates instantly!)")
	fmt.Println("    • Application bug corrupts data (wrong step numbers, bad JSON)")
	fmt.Println("    • Storage corruption (bit rot in the data files)")
	fmt.Println()
	fmt.Println("  For these, you need WAL archiving + PITR:")
	fmt.Println()
	fmt.Println("  ┌──────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  WAL Archiving to S3 (via wal-g or pgBackRest)               │")
	fmt.Println("  │                                                              │")
	fmt.Println("  │  Continuous: every WAL segment (16MB) pushed to S3           │")
	fmt.Println("  │  as soon as it's full.                                       │")
	fmt.Println("  │                                                              │")
	fmt.Println("  │  Combined with a weekly base backup, you can restore to      │")
	fmt.Println("  │  ANY point in time within the retention window.              │")
	fmt.Println("  └──────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Recovery procedure (after DROP TABLE disaster):")
	fmt.Println("    $ wal-g backup-fetch /restore/pg LATEST                    ")
	fmt.Println("    # Add recovery.conf:                                        ")
	fmt.Println("    restore_command = 'wal-g wal-fetch %f %p'                  ")
	fmt.Println("    recovery_target_time = '2026-05-04 14:31:52 UTC'           ")
	fmt.Println("    # (the timestamp JUST before the DROP TABLE)               ")
	fmt.Println("    $ pg_ctl start                                              ")
	fmt.Println()
	fmt.Println("  The WAL-G approach gives you:")
	fmt.Println("    • RPO: ~1 WAL segment (16MB, typically 1-5 minutes of data)")
	fmt.Println("    • RTO: ~time to download base backup + replay WAL")
	fmt.Println("      (for a 100GB database, ~15-30 minutes)")
	fmt.Println("    • Protection against operator error ✅")
	fmt.Println("    • Protection against corruption ✅")
	fmt.Println("    • Protection against region failure ✅")
	fmt.Println("      (S3 is cross-AZ, WAL is continuously archived)")
	fmt.Println()
}

func operatorSafety() {
	fmt.Println("── 6. OPERATOR SAFETY (defense in depth) ──")
	fmt.Println()
	fmt.Println("  Most data loss is caused by humans, not machines. Layers:")
	fmt.Println()
	fmt.Println("  Layer 1 — Application-level protection:")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  • Never issue DROP/TRUNCATE from application code          │")
	fmt.Println("  │  • event_history has no UPDATE/DELETE paths in application  │")
	fmt.Println("  │  • All writes are INSERT (append-only by design!)           │")
	fmt.Println("  │  • Use a restricted DB user for the worker pool:            │")
	fmt.Println("  │    GRANT INSERT ON event_history TO worker_app;             │")
	fmt.Println("  │    GRANT UPDATE (status, heartbeat_at) ON                   │")
	fmt.Println("  │      workflow_instances TO worker_app;                      │")
	fmt.Println("  │    -- worker_app has NO DROP, TRUNCATE, DELETE permissions  │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Layer 2 — Database-level guardrails:")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  • event_streaming_a_workflow:                              │")
	fmt.Println("  │    statement_timeout = '30s'  (global)                      │")
	fmt.Println("  │    idle_in_transaction_session_timeout = '60s'              │")
	fmt.Println("  │  • Disable autovacuum on event_history (append-only,        │")
	fmt.Println("  │    no updates/deletes, vacuum has nothing to clean)         │")
	fmt.Println("  │  • Consider: ALTER TABLE event_history SET (               │")
	fmt.Println("  │      autovacuum_enabled = false);                           │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Layer 3 — Human guardrails:")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  • Production DB access via jump host ONLY                   │")
	fmt.Println("  │  • psql session wraps BEGIN; ... COMMIT; (no auto-commit)   │")
	fmt.Println("  │  • .psqlrc sets: \\set ON_ERROR_STOP on                     │")
	fmt.Println("  │  • Prefer flyway/migrate for schema changes, not manual SQL │")
	fmt.Println("  │  • Read-only replicas for ad-hoc queries (never the primary)│")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
}

func verification() {
	fmt.Println("── 7. VERIFYING IT ACTUALLY WORKS ──")
	fmt.Println()
	fmt.Println("  Resilience that's never tested is not resilience. For this")
	fmt.Println("  system specifically, you should regularly run:")
	fmt.Println()
	fmt.Println("  Test 1 — Planned failover:")
	fmt.Println("    $ patronictl switchover  # weekly, during business hours")
	fmt.Println("    Verify: workers reconnect, in-flight workflows continue,")
	fmt.Println("    no replay divergences, no duplicate API calls.")
	fmt.Println()
	fmt.Println("  Test 2 — Unplanned failover (chaos engineering):")
	fmt.Println("    $ kill -9 $(pgrep -f 'postgres: primary')  # on the primary")
	fmt.Println("    Verify: Patroni promotes standby within 60s, workflows")
	fmt.Println("    resume from last checkpoint without error.")
	fmt.Println()
	fmt.Println("  Test 3 — PITR restore drill:")
	fmt.Println("    $ wal-g backup-fetch /tmp/restore LATEST")
	fmt.Println("    Verify: database comes up, event history is intact, a test")
	fmt.Println("    workflow replays correctly against the restored history.")
	fmt.Println()
	fmt.Println("  Test 4 — Network partition:")
	fmt.Println("    $ iptables -A OUTPUT -d <standby-ip> -j DROP  # on primary")
	fmt.Println("    Verify: sync replication blocks commits (correct!), primary")
	fmt.Println("    doesn't lose data, Patroni doesn't promote the standby")
	fmt.Println("    (split brain prevention).")
	fmt.Println()
}

func stagedRecommendation() {
	fmt.Println("── 8. STAGED RECOMMENDATION ──")
	fmt.Println()
	fmt.Println("  Week 1-2 (get running):")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  Single PostgreSQL instance (cloud managed: RDS, Cloud SQL) │")
	fmt.Println("  │  • Enable automated backups with 7-day retention            │")
	fmt.Println("  │  • Enable deletion protection (can't accidentally delete)   │")
	fmt.Println("  │  • statement_timeout = '30s'                                │")
	fmt.Println("  │  • Restricted DB user for application                       │")
	fmt.Println("  │  • For prototyping: this is fine                            │")
	fmt.Println("  │  • RPO for managed backups: 5 min (automated snapshots)     │")
	fmt.Println("  │  • RTO: ~30 min (restore from snapshot)                     │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Week 4-6 (production readiness):")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  Patroni + 2 replicas (one sync, one async) + etcd cluster  │")
	fmt.Println("  │  + WAL archiving to S3 via wal-g                            │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  • Self-managed or use cloud-native equivalent:             │")
	fmt.Println("  │    - AWS: RDS Multi-AZ with one sync standby                │")
	fmt.Println("  │    - GCP: Cloud SQL with HA + cross-region read replica      │")
	fmt.Println("  │    - Self-managed: Patroni on 3 VMs across 3 AZs            │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  • RPO: ~0 (synchronous replication)                        │")
	fmt.Println("  │  • RTO: ~60 seconds (automatic failover)                    │")
	fmt.Println("  │  • Add PITR: restore to any second within 30 days           │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Month 3+ (if this becomes critical infrastructure):")
	fmt.Println("  ┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("  │  Add cross-region disaster recovery:                        │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  Region A (primary):            Region B (DR):              │")
	fmt.Println("  │  ┌──────────┐                   ┌──────────┐               │")
	fmt.Println("  │  │ Patroni  │                   │ WAL-G    │               │")
	fmt.Println("  │  │ + PG     │ ── WAL archive ──→│ restore  │               │")
	fmt.Println("  │  │ Primary  │      to S3        │ (cold)   │               │")
	fmt.Println("  │  └──────────┘                   └──────────┘               │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  Cross-region WAL shipping via S3 replication.             │")
	fmt.Println("  │  Region B stays in continuous recovery mode, ready to      │")
	fmt.Println("  │  promote.                                                    │")
	fmt.Println("  │                                                             │")
	fmt.Println("  │  RPO: < 1 minute (WAL segments continuously archived)      │")
	fmt.Println("  │  RTO: ~15 minutes (promote DR instance, update DNS)        │")
	fmt.Println("  └─────────────────────────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  ── Bottom line ──")
	fmt.Println()
	fmt.Println("  The operational burden of making PostgreSQL rock-solid is")
	fmt.Println("  real but well-understood. This is NOT uncharted territory —")
	fmt.Println("  banks, hospitals, and payment processors run PostgreSQL with")
	fmt.Println("  exactly these patterns. The Patroni + synchronous replication")
	fmt.Println("  + WAL archiving setup is the industry standard for 'can't lose")
	fmt.Println("  a single committed transaction.'")
	fmt.Println()
	fmt.Println("  Compared to Temporal's operational complexity (4+ custom")
	fmt.Println("  services plus their persistence layer), this is simpler:")
	fmt.Println("  you're operating one well-understood database instead of a")
	fmt.Println("  distributed system of custom stateful services.")
	fmt.Println()
}
