package com.cleat.example;

/**
 * TeaVM entry point for the example workflow compilation.
 * <p>
 * This class provides the {@code main} method that TeaVM uses as the root
 * of its reachability (tree-shaking) analysis.  The actual workflow logic
 * lives in {@link PlaceOrder}.
 * <p>
 * <strong>Tree-shaking protection:</strong> TeaVM treats {@code @Export}
 * annotated methods as reachability roots, so the generated export wrapper
 * classes (produced by {@link cleat.CleatEntryProcessor}) are preserved
 * automatically — each carries a {@code @Export(name = "...")} annotation
 * that makes the method a WASM export.
 * <p>
 * As an additional safety measure, this main class references the
 * {@link PlaceOrder} class directly, ensuring that all code reachable
 * from <em>both</em> the main entry point and the generated exports is
 * retained.  The {@code CleatEntryAggregator} (also generated by the
 * annotation processor) provides a compile-time registry of all export
 * wrapper classes.
 */
public class WorkflowEntry {

    /**
     * Main entry point for TeaVM analysis.
     * <p>
     * This method does not perform any real work at runtime.  It exists
     * solely as a root for TeaVM's tree-shaking analysis.  The reference
     * to {@link PlaceOrder} ensures that the workflow logic is reachable
     * from the analysis root, while the generated {@code @Export} wrappers
     * are preserved by TeaVM's export handling.
     *
     * @param args command-line arguments (unused)
     */
    public static void main(String[] args) {
        // Reference PlaceOrder to ensure the workflow classes are reachable
        // from TeaVM's analysis root.  The @Export-annotated generated
        // wrappers (PlaceOrder_placeOrder_Export, PlaceOrder_cancelOrder_Export)
        // are preserved by TeaVM's export handling.
        System.out.println("Cleat workflow: " + PlaceOrder.class.getName());
    }
}
