// Code generated by durable-gen. DO NOT EDIT.

package orders

import "github.com/rcownie/durable/durable"

type GetStateRequest struct {
	OrderID string `json:"order_id"`
}

type GetStateResponse struct {
	Status     string `json:"status"`
	DriverName string `json:"driver_name"`
	ETAMinutes int    `json:"eta_minutes"`
	TotalCents int    `json:"total_cents"`
}

type Client struct {
	h durable.HostCalls
}

func NewClient(h durable.HostCalls) *Client {
	return &Client{h: h}
}

func (c *Client) GetState(req GetStateRequest) (*GetStateResponse, error) {
	var resp GetStateResponse
	if err := c.h.DurableCallTyped("orders", "GetState", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
