// FoodDash — typed client demonstration.
//
// This file shows the same workflow as order.go but uses typed client wrappers
// (generated by cleat-gen) instead of raw DurableCallJSON / DurableCall calls.
// Magic strings like "menu", "LookupItem" are eliminated entirely.
package fooddash

import (
	"fmt"
	"time"

	"github.com/rcownie/cleat/durable"
	"github.com/rcownie/cleat/examples/fooddash/clients/dispatch"
	"github.com/rcownie/cleat/examples/fooddash/clients/menu"
	"github.com/rcownie/cleat/examples/fooddash/clients/payments"
	"github.com/rcownie/cleat/examples/fooddash/clients/restaurant"
)

// PlaceOrderTyped demonstrates the PlaceOrder workflow using typed service clients.
func PlaceOrderTyped(h cleat.HostCalls, userID string, restaurantID string,
	items []OrderItem, address DeliveryAddress) (OrderResult, error) {

	if len(items) == 0 {
		return OrderResult{}, fmt.Errorf("order must contain at least one item")
	}

	// Create typed clients.
	menuClient := menu.NewClient(h)
	paymentsClient := payments.NewClient(h)
	dispatchClient := dispatch.NewClient(h)
	restaurantClient := restaurant.NewClient(h)

	// Step 1: Validate every item against the restaurant's menu.
	validated, err := validateMenuItemsTyped(menuClient, restaurantID, items)
	if err != nil {
		return OrderResult{}, fmt.Errorf("menu validation failed: %w", err)
	}

	// Step 2: Calculate the total.
	total := calculateOrderTotal(validated)
	h.LogKV("order total calculated",
		"total_cents", total,
		"item_count", len(validated),
	)

	// Steps 3-5: Execute with Saga-based compensation.
	var chargeResult struct {
		ChargeID string
		Amount   int
	}
	var driverInfo struct {
		DriverID   string
		DriverName string
		ETAMinutes int
	}

	s := cleat.NewSaga()

	// Step 3: Charge the customer. Compensate with refund.
	s.AddStep("charge_customer",
		func(h cleat.HostCalls) (string, error) {
			resp, err := paymentsClient.Charge(payments.ChargeRequest{
				UserID:      userID,
				AmountCents: total,
				Currency:    "usd",
			})
			if err != nil {
				return "", err
			}
			chargeResult = struct {
				ChargeID string
				Amount   int
			}{ChargeID: resp.ChargeID, Amount: total}
			return "", nil
		},
		func(h cleat.HostCalls) error {
			paymentsClient.Refund(payments.RefundRequest{
				ChargeID: chargeResult.ChargeID,
			})
			return nil
		},
	)

	// Step 4: Assign a driver. Compensate with release.
	s.AddStep("assign_driver",
		func(h cleat.HostCalls) (string, error) {
			resp, err := dispatchClient.FindDriver(dispatch.FindDriverRequest{
				Address: fmt.Sprintf("%s, %s %s", address.Street, address.City, address.ZipCode),
			})
			if err != nil {
				return "", err
			}

			// Wait for the driver to accept.
			sr := h.AwaitSignals(
				[]string{"driver_accepted", "driver_declined"},
				2*time.Minute,
			)
			if sr.Err != nil {
				return "", fmt.Errorf("signal error: %w", sr.Err)
			}
			if sr.TimedOut {
				return "", fmt.Errorf("no driver accepted within timeout")
			}
			if sr.Name == "driver_declined" {
				return "", fmt.Errorf("driver declined the delivery")
			}

			driverInfo = struct {
				DriverID   string
				DriverName string
				ETAMinutes int
			}{
				DriverID:   resp.DriverID,
				DriverName: resp.DriverName,
				ETAMinutes: resp.ETAMinutes,
			}
			return "", nil
		},
		func(h cleat.HostCalls) error {
			dispatchClient.ReleaseDriver(dispatch.ReleaseDriverRequest{
				DriverID: driverInfo.DriverID,
			})
			return nil
		},
	)

	// Step 5: Notify the restaurant. Compensate with cancel.
	s.AddStep("notify_restaurant",
		func(h cleat.HostCalls) (string, error) {
			var itemNames string
			for i, item := range validated {
				if i > 0 {
					itemNames += ", "
				}
				itemNames += fmt.Sprintf("%dx %s", item.Quantity, item.Name)
			}
			return "", restaurantClient.NotifyOrder(restaurant.NotifyOrderRequest{
				RestaurantID: restaurantID,
				Items:        itemNames,
				ETAMinutes:   driverInfo.ETAMinutes,
			})
		},
		func(h cleat.HostCalls) error {
			restaurantClient.CancelOrder(restaurant.CancelOrderRequest{
				OrderID: chargeResult.ChargeID,
			})
			return nil
		},
	)

	if err := s.Run(h); err != nil {
		return OrderResult{}, err
	}

	// Step 6: Wait for the driver to confirm pickup via polling.
	_, err = cleat.PollUntil(h, 30*time.Second, 30*time.Minute,
		func() (string, error) {
			resp, err := dispatchClient.CheckPickupStatus(dispatch.CheckPickupStatusRequest{
				DriverID: driverInfo.DriverID,
			})
			if err != nil {
				return "", err
			}
			return resp.Status, nil
		},
		func(status string) bool { return status == "picked_up" },
	)
	if err != nil {
		// Compensate everything if pickup fails.
		dispatchClient.ReleaseDriver(dispatch.ReleaseDriverRequest{DriverID: driverInfo.DriverID})
		paymentsClient.Refund(payments.RefundRequest{ChargeID: chargeResult.ChargeID})
		return OrderResult{}, fmt.Errorf("pickup failed: %w", err)
	}

	// Record queryable state.
	h.SetQueryState("order_status", "confirmed")
	h.SetQueryState("driver_name", driverInfo.DriverName)

	return OrderResult{
		OrderID:    chargeResult.ChargeID,
		TotalCents: total,
		DriverID:   driverInfo.DriverID,
		DriverName: driverInfo.DriverName,
		ETAMinutes: driverInfo.ETAMinutes,
		Status:     "confirmed",
	}, nil
}

// validateMenuItemsTyped validates each item against the menu using the typed client.
func validateMenuItemsTyped(client *menu.Client, restaurantID string, items []OrderItem) ([]validatedItem, error) {
	var result []validatedItem

	for _, item := range items {
		menuItem, err := client.LookupItem(menu.LookupItemRequest{
			RestaurantID: restaurantID,
			SKU:          item.SKU,
		})
		if err != nil {
			return nil, fmt.Errorf("item %s: %w", item.SKU, err)
		}
		if !menuItem.Available {
			return nil, fmt.Errorf("item %s (%s) is currently unavailable", item.SKU, menuItem.Name)
		}
		result = append(result, validatedItem{
			SKU:      item.SKU,
			Name:     menuItem.Name,
			Quantity: item.Quantity,
			Price:    menuItem.PriceCents,
		})
	}
	return result, nil
}
