//! Rust SDK for the cleat durable execution framework.
//!
//! Provides the [`HostCalls`] struct for making durable API calls from WASM
//! workflows, and memory helpers for the cleat ABI.

pub mod host_calls;
pub mod memory;
pub mod plugins;
pub mod test;

pub use host_calls::{FetchResult, HostCalls, RetryPolicy, SignalResult};
pub use plugins::{
    AwaitEventResult, AwaitWebhookResult, BlobGetResult, BlobPutResult,
    EvaluateFlagResult, LlmChatMessage, LlmChatResult, LlmTool, LlmToolCall,
    LlmUsageInfo, Plugins, ProduceResult, ResolveIncidentResult,
    SendMessageResult, SendWebhookResult, TriggerIncidentResult,
};

/// A sentinel error used to signal workflow suspension via
/// `std::panic::catch_unwind`.
///
/// When a host call (e.g. `durable_sleep`) determines that the workflow
/// should suspend, it panics with this value. The export wrapper generated by
/// `#[durable_entry]` wraps the inner function call in `catch_unwind` and, on
/// catching this sentinel, returns `SUSPEND_SENTINEL` to the host engine.
///
/// Analogous to Go's `durable.ErrSuspend`.
pub struct SuspendSentinel;

/// Convert a Result<T, E> into a Result<String, String> for serialized export.
///
/// On `Ok`, the value is serialized to JSON. On `Err`, the error is converted
/// to its display string representation.
pub fn format_durable_result<T: serde::Serialize, E: std::fmt::Display>(
    r: std::result::Result<T, E>,
) -> std::result::Result<String, String> {
    match r {
        Ok(val) => serde_json::to_string(&val).map_err(|e| format!("serialize: {}", e)),
        Err(e) => Err(e.to_string()),
    }
}
