//! Rust SDK for the cleat cleat execution framework.
//!
//! Provides the [`HostCalls`] struct for making cleat API calls from WASM
//! workflows, and memory helpers for the cleat ABI.

pub mod defer;
pub mod host_calls;
pub mod memory;
pub mod plugins;
pub mod saga;
pub mod test;
pub mod version;

// Native stubs for WASM host imports — provided so that crates depending on
// cleat-sdk can compile and link their tests on non-WASM targets. The generated
// #[cleat_entry] wrapper calls HostCalls::json_stringify (and json_parse) which
// in turn call these extern "C" imports. On WASM they're supplied by the host;
// here we provide no-op fallbacks.
#[cfg(not(target_family = "wasm"))]
mod native_stubs {
    #[no_mangle]
    pub extern "C" fn cleat_json_stringify(
        _ptr: *const u8, _len: u32,
        _out_ptr: *mut u8, _out_max_len: u32,
    ) -> i64 {
        0 // return zero bytes written / error
    }

    #[no_mangle]
    pub extern "C" fn cleat_json_parse(
        _json_ptr: *const u8, _json_len: u32,
        _out_ptr: *mut u8, _out_max_len: u32,
    ) -> i64 {
        0 // return zero bytes written / error
    }
}

pub use defer::{register_defer, run_deferred};
pub use cleat_macro::cleat_test;
pub use host_calls::{ChildWorkflowOptions, FetchResult, HostCalls, RetryPolicy, SignalResult};
pub use saga::{Saga, SagaStep};
pub use plugins::{
    AwaitEventResult, AwaitWebhookResult, BlobGetResult, BlobPutResult,
    EvaluateFlagResult, LlmChatMessage, LlmChatResult, LlmTool, LlmToolCall,
    LlmUsageInfo, Plugins, ProduceResult, ResolveIncidentResult,
    SendMessageResult, SendWebhookResult, TriggerIncidentResult,
};

/// A sentinel error used to signal workflow suspension via
/// `std::panic::catch_unwind`.
///
/// When a host call (e.g. `cleat_sleep`) determines that the workflow
/// should suspend, it panics with this value. The export wrapper generated by
/// `#[cleat_entry]` wraps the inner function call in `catch_unwind` and, on
/// catching this sentinel, returns `SUSPEND_SENTINEL` to the host engine.
///
/// Analogous to Go's `cleat.ErrSuspend`.
pub struct SuspendSentinel;

/// Convert a Result<T, E> into a Result<String, String> for serialized export.
///
/// On `Ok`, the value is serialized to JSON. On `Err`, the error is converted
/// to its display string representation.
pub fn format_cleat_result<T: serde::Serialize, E: std::fmt::Display>(
    r: std::result::Result<T, E>,
) -> std::result::Result<String, String> {
    match r {
        Ok(val) => serde_json::to_string(&val).map_err(|e| format!("serialize workflow result: {}", e)),
        Err(e) => Err(e.to_string()),
    }
}
