// Code generated by cleat-gen plugin-client. DO NOT EDIT.

package auditlog

import (
	"encoding/json"
	"github.com/cleat-team/cleat/cleat"
)

type RecordEventInput struct {
	EventType string          `json:"event_type"`
	Details   json.RawMessage `json:"details,omitempty"`
	EventID   string          `json:"event_id,omitempty"`
}

type RecordEventOutput struct {
	Recorded bool `json:"recorded"`
}

var RecordEvent = cleat.NewPluginFunc[RecordEventInput, RecordEventOutput]("audit-log", "record_event")
