package catalogdiff

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strings"

	"github.com/cleat-team/cleat/migration"
)

// autoGeneratedMSSQLName matches the names SQL Server invents for a
// constraint (and its backing index, which gets the same name) when the
// migration that created it left the name out -- e.g. "PK__schema_m__79B5C94C1DA7B4EB".
// The trailing segment is derived from the object_id and is not
// reproducible across two independently-built databases: measured on
// schema_migrations' bootstrap table, 2026-09-19, two builds of the
// identical migration chain produced "PK__schema_m__79B5C94C1DA7B4EB" and
// "PK__schema_m__79B5C94CC1648A3B" -- same prefix, different everything
// after it. A snapshot comparison that includes the raw name treats every
// unnamed constraint as a difference whether or not anything actually
// changed, which is exactly backwards for a schema-equality check: it is
// the SAME hazard schemaMigrationsTable's own exclusion exists for, but it
// is not limited to that one table -- any migration-defined or
// plugin-defined table with an unnamed inline constraint hits it too. See
// cleat#2306 phase 2, where the recoverable-vs-proven comparison snapshots
// plugin-created tables that may carry unnamed constraints of their own.
var autoGeneratedMSSQLName = regexp.MustCompile(`^[A-Za-z]{2,3}__.+__[0-9A-Fa-f]{8,}$`)

// normalizeMSSQLName replaces name with a stable placeholder when it looks
// SQL-Server-generated, so two constraints (or indexes) that are
// structurally identical but auto-named compare equal regardless of the
// random suffix. kind disambiguates the placeholder so an auto-named PK
// and an auto-named DEFAULT constraint on the same table are never
// conflated with each other -- only with another auto-named constraint of
// the SAME kind, which Definition (columns, or default expression + target
// column) still distinguishes.
func normalizeMSSQLName(name, kind string) string {
	if autoGeneratedMSSQLName.MatchString(name) {
		return "<auto:" + kind + ">"
	}
	return name
}

// snapshotMSSQL builds a Catalog for a SQL Server database.
//
// Every Table's RowSecurity and Policies, plus Catalog.Schemas and
// Catalog.Roles, are now populated here -- cleat#2432. Until that issue this
// comment described the opposite: RowSecurity was nil and Policies empty on
// every table, and before THAT, cleat#2434, the comment claimed the dialect
// had no row-level security at all, which was also false (a chain-built
// database carries 14 SECURITY POLICY objects holding 56 predicates). Both
// gaps were real for a while and neither was a fact about the dialect -- see
// cleat#2434's history, kept below the query that closes it, rather than
// repeating the measurement here a third time.
//
// The queries below are the same ones scripts/gen-mssql-baseline's
// -mode=supplementary check already runs and has validated independently
// (security policies/predicates, schemas, roles, and -- cleat#2882 -- column
// width/precision/scale/identity and index INCLUDE/filter/sort-order) --
// ported here rather than re-derived, because cleat#2434's own comment named
// this file as "the better repair" for exactly this gap.
//
// Still supplementary-only, and genuinely so rather than merely unclaimed:
// a column's is_computed flag, and triggers' own settings (QUOTED_IDENTIFIER,
// ANSI_NULLS, is_disabled) -- cleat#2882 scoped its port to the classes named
// in its own three-item list and did not take these on. Collation is NOT in
// that list: it was already read here (c.collation_name, below) before
// cleat#2882 -- this comment previously claimed otherwise, which was already
// false by the time it was written, not a fact that decayed.
func snapshotMSSQL(ctx context.Context, db *sql.DB) (*Catalog, error) {
	cat := &Catalog{
		Dialect:  migration.DialectMSSQL,
		Tables:   map[string]*Table{},
		Routines: map[string]string{},
	}

	type tableRow struct {
		objectID     int64
		schema, name string
	}
	rows, err := db.QueryContext(ctx, `
		SELECT t.object_id, s.name, t.name
		FROM sys.tables t
		JOIN sys.schemas s ON s.schema_id = t.schema_id
		ORDER BY s.name, t.name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing tables: %w", err)
	}
	var tables []tableRow
	for rows.Next() {
		var r tableRow
		if err := rows.Scan(&r.objectID, &r.schema, &r.name); err != nil {
			rows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning table row: %w", err)
		}
		if r.name == schemaMigrationsTable {
			continue
		}
		tables = append(tables, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing tables: %w", err)
	}
	rows.Close()

	for _, tr := range tables {
		qname := tr.schema + "." + tr.name
		t := &Table{Name: qname}

		// max_length, precision, scale and is_identity -- cleat#2882's
		// remaining MSSQL granularity gap. sys.types.name alone is a bare
		// type name with no length (unlike MySQL's COLUMN_TYPE, which
		// already spells "varchar(255)"), so a column silently narrowed
		// from varchar(255) to varchar(50) presented identical rows to
		// every query this function made before this change -- the exact
		// class scripts/gen-mssql-baseline/supplementary.go's "column
		// shape" check exists to catch, ported rather than re-derived.
		// Folded into DataType (not a new Column field) for the same
		// reason mysql.go folds auto_increment into DataType: canonicalize
		// already renders DataType, so there is nothing new to forget to
		// render -- the exact #2446 trap this file's header comment warns
		// about one line up.
		colRows, err := db.QueryContext(ctx, `
			SELECT c.name, ty.name, c.max_length, c.precision, c.scale, c.is_identity,
			       c.is_nullable,
			       COALESCE(OBJECT_DEFINITION(c.default_object_id), ''),
			       COALESCE(c.collation_name, '')
			FROM sys.columns c
			JOIN sys.types ty ON ty.user_type_id = c.user_type_id
			WHERE c.object_id = @p1
			ORDER BY c.column_id
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: columns for %s: %w", qname, err)
		}
		for colRows.Next() {
			var name, dtype string
			var maxLength int
			var precision, scale int
			var identity, nullable bool
			var def, collation string
			if err := colRows.Scan(&name, &dtype, &maxLength, &precision, &scale, &identity, &nullable, &def, &collation); err != nil {
				colRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning column for %s: %w", qname, err)
			}
			dtype = fmt.Sprintf("%s(len=%d,precision=%d,scale=%d)", dtype, maxLength, precision, scale)
			if identity {
				dtype += " IDENTITY"
			}
			t.Columns = append(t.Columns, Column{Name: name, DataType: dtype, Nullable: nullable, Default: def, Collation: collation})
		}
		if err := colRows.Err(); err != nil {
			return nil, fmt.Errorf("catalogdiff: columns for %s: %w", qname, err)
		}
		colRows.Close()

		// has_filter/filter_definition and, per column, is_included_column
		// and is_descending_key -- cleat#2882's remaining MSSQL granularity
		// gap. The PRIOR version of this query aggregated every
		// index_columns row (key AND included) into one STRING_AGG ordered
		// by key_ordinal alone -- included columns all carry key_ordinal=0,
		// so they sorted first, mixed in with key columns indistinguishably
		// and with no defined order among themselves. That is a second,
		// unrelated bug this same query carried: fixed here by querying
		// per-row (matching mysql.go's idxByName accumulator pattern) and
		// building the key-column and included-column lists separately in
		// Go, rather than trying to express "two differently-ordered lists
		// from one column" in a single STRING_AGG.
		idxRows, err := db.QueryContext(ctx, `
			SELECT i.name, i.is_unique, i.type_desc, i.has_filter, COALESCE(i.filter_definition, ''),
			       ic.is_included_column, ic.is_descending_key, ic.key_ordinal, c.name
			FROM sys.indexes i
			JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE i.object_id = @p1 AND i.name IS NOT NULL
			ORDER BY i.name, ic.is_included_column, ic.key_ordinal, c.name
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: indexes for %s: %w", qname, err)
		}
		type idxAcc struct {
			unique               bool
			typeDesc             string
			hasFilter            bool
			filterDef            string
			keyCols, includeCols []string
		}
		idxByName := map[string]*idxAcc{}
		var idxOrder []string
		for idxRows.Next() {
			var name, typeDesc, filterDef, colName string
			var unique, hasFilter, included, descending bool
			var keyOrdinal int
			if err := idxRows.Scan(&name, &unique, &typeDesc, &hasFilter, &filterDef,
				&included, &descending, &keyOrdinal, &colName); err != nil {
				idxRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning index for %s: %w", qname, err)
			}
			acc, ok := idxByName[name]
			if !ok {
				acc = &idxAcc{unique: unique, typeDesc: typeDesc, hasFilter: hasFilter, filterDef: filterDef}
				idxByName[name] = acc
				idxOrder = append(idxOrder, name)
			}
			// Folded into the column token, matching mysql.go's DESC fold
			// for the same attribute -- see that file's comment on why: it
			// reaches the line canonicalize already renders without a
			// separate field nothing would print.
			if descending {
				colName += " DESC"
			}
			if included {
				acc.includeCols = append(acc.includeCols, colName)
			} else {
				acc.keyCols = append(acc.keyCols, colName)
			}
		}
		if err := idxRows.Err(); err != nil {
			idxRows.Close()
			return nil, fmt.Errorf("catalogdiff: indexes for %s: %w", qname, err)
		}
		idxRows.Close()
		for _, name := range idxOrder {
			acc := idxByName[name]
			// columns is part of the Definition (not just the name) precisely
			// so that normalizeMSSQLName can collapse two auto-generated names
			// for DIFFERENT indexes without losing the ability to tell them
			// apart -- see the comment on that function. include and filter
			// are appended the same way, so a filtered or covering index
			// that loses either reaches this line too.
			t.Indexes = append(t.Indexes, Index{
				Name: normalizeMSSQLName(name, "IDX"),
				Definition: fmt.Sprintf("unique=%t type=%s columns=%s include=%s filter(%t)=%s",
					acc.unique, acc.typeDesc, strings.Join(acc.keyCols, ","),
					strings.Join(acc.includeCols, ","), acc.hasFilter, acc.filterDef),
			})
		}

		// Every branch's Definition carries the COLUMN(S) it applies to, not
		// just its kind -- required so that normalizeMSSQLName (applied
		// below) can strip an auto-generated name without two distinct
		// constraints of the same kind on the same table (two DEFAULTs, two
		// UNIQUEs, two FOREIGN KEYs) collapsing onto an identical line and
		// silently losing one from the comparison.
		//
		// is_not_trusted is part of the compared text, and that is the whole
		// reason the CASE below exists. It was not, until cleat#2438: the
		// pre-compaction chain adds seven JSON check constraints WITH NOCHECK on
		// purpose (036_plugin_deps_isjson.sql, 037_json_column_checks.sql) so an
		// existing deployment with a violating row upgrades instead of blocking,
		// and a baseline generated without it reproduces every one of those
		// definitions while silently marking all seven trusted. A fresh database
		// inserts identically either way, so only this column separates them --
		// and while it was outside the compared set this differential reported
		// zero differences about constraints it had not looked at. Appended, not
		// prepended: line 218 takes the definition's first token as the kind.
		conRows, err := db.QueryContext(ctx, `
			SELECT name, 'CHECK ' + COALESCE(OBJECT_DEFINITION(object_id), '')
				+ CASE WHEN is_not_trusted = 1 THEN ' WITH NOCHECK' ELSE '' END
			FROM sys.check_constraints WHERE parent_object_id = @p1
			UNION ALL
			SELECT dc.name, 'DEFAULT ' + COALESCE(OBJECT_DEFINITION(dc.object_id), '') + ' FOR ' + c.name
			FROM sys.default_constraints dc
			JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
			WHERE dc.parent_object_id = @p1
			UNION ALL
			SELECT kc.name, 'PRIMARY KEY (' + STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) + ')'
			FROM sys.key_constraints kc
			JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id AND ic.index_id = kc.unique_index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE kc.parent_object_id = @p1 AND kc.type = 'PK'
			GROUP BY kc.name
			UNION ALL
			SELECT kc.name, 'UNIQUE (' + STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) + ')'
			FROM sys.key_constraints kc
			JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id AND ic.index_id = kc.unique_index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE kc.parent_object_id = @p1 AND kc.type = 'UQ'
			GROUP BY kc.name
			UNION ALL
			-- cleat#2447. sys.foreign_keys carries the delete/update actions
			-- and its own is_not_trusted, none of which were compared -- the
			-- same shape as the CHECK constraint's is_not_trusted above, and
			-- for the same reason: two definitions that render identically
			-- here (ON DELETE CASCADE vs no action) are NOT the same
			-- constraint, and the emitter (scripts/gen-mssql-baseline/emit.go,
			-- refAction) already reads both actions -- only the comparator
			-- was missing them. The CASE mapping matches refAction exactly
			-- (CASCADE/SET_NULL/SET_DEFAULT, NO_ACTION omitted) so the same
			-- FK renders identically on both sides of -mode=verify.
			SELECT fk.name, 'FOREIGN KEY (' + STRING_AGG(pc.name, ',') WITHIN GROUP (ORDER BY fkc.constraint_column_id) + ') REFERENCES ' + OBJECT_NAME(fk.referenced_object_id)
				+ CASE fk.delete_referential_action_desc
					WHEN 'CASCADE' THEN ' ON DELETE CASCADE'
					WHEN 'SET_NULL' THEN ' ON DELETE SET NULL'
					WHEN 'SET_DEFAULT' THEN ' ON DELETE SET DEFAULT'
					ELSE ''
				  END
				+ CASE fk.update_referential_action_desc
					WHEN 'CASCADE' THEN ' ON UPDATE CASCADE'
					WHEN 'SET_NULL' THEN ' ON UPDATE SET NULL'
					WHEN 'SET_DEFAULT' THEN ' ON UPDATE SET DEFAULT'
					ELSE ''
				  END
				+ CASE WHEN fk.is_not_trusted = 1 THEN ' WITH NOCHECK' ELSE '' END
			FROM sys.foreign_keys fk
			JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
			JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
			WHERE fk.parent_object_id = @p1
			GROUP BY fk.name, fk.referenced_object_id, fk.delete_referential_action_desc,
				fk.update_referential_action_desc, fk.is_not_trusted
			ORDER BY 1
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: constraints for %s: %w", qname, err)
		}
		for conRows.Next() {
			var name, def string
			if err := conRows.Scan(&name, &def); err != nil {
				conRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning constraint for %s: %w", qname, err)
			}
			kind := strings.SplitN(def, " ", 2)[0]
			t.Constraints = append(t.Constraints, Constraint{Name: normalizeMSSQLName(name, kind), Definition: def})
		}
		if err := conRows.Err(); err != nil {
			return nil, fmt.Errorf("catalogdiff: constraints for %s: %w", qname, err)
		}
		conRows.Close()

		cat.Tables[qname] = t
	}

	// Security policies and predicates -- cleat#2432, the gap cleat#2434's own
	// comment on this function used to describe and leave unclosed.
	//
	// A policy's is_enabled is folded into EVERY predicate line it owns,
	// rather than carried as a separate RowSecurity-only fact: a policy that
	// targets a table gets exactly one RowSecurity{Enabled: ...} line for that
	// table (set once, below, from whichever predicate row is seen first --
	// every predicate of one policy reports the same is_enabled, so "first" and
	// "only" coincide), and that line's mere presence is itself the signal
	// "this table has an active policy" -- a dropped policy removes the line
	// entirely rather than changing a boolean, which is the stronger of the two
	// signals a known-positive can depend on.
	//
	// Unlike PostgreSQL, SQL Server has no owner-bypass knob on a security
	// policy -- RowSecurity.Forced has no SQL Server analogue and is left
	// unset (false) rather than hardcoded true, so it never fabricates a
	// comparable fact the platform does not have.
	polRows, err := db.QueryContext(ctx, `
		SELECT sp.name, sp.is_enabled, p.predicate_type_desc, COALESCE(p.operation_desc, ''),
		       p.predicate_definition,
		       OBJECT_SCHEMA_NAME(p.target_object_id), OBJECT_NAME(p.target_object_id)
		FROM sys.security_policies sp
		JOIN sys.security_predicates p ON p.object_id = sp.object_id
		ORDER BY sp.name, p.predicate_type_desc, COALESCE(p.operation_desc, '')
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: security policies: %w", err)
	}
	for polRows.Next() {
		var policyName, predType, opDesc, def, tschema, tname string
		var enabled bool
		if err := polRows.Scan(&policyName, &enabled, &predType, &opDesc, &def, &tschema, &tname); err != nil {
			polRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning security policy: %w", err)
		}
		qname := tschema + "." + tname
		t, ok := cat.Tables[qname]
		if !ok {
			// The predicate targets a table this snapshot excluded (only
			// schemaMigrationsTable today) or one sys.tables did not return --
			// skip rather than panic; nothing core-migration-owned does this.
			continue
		}
		if t.RowSecurity == nil {
			t.RowSecurity = &RowSecurity{Enabled: enabled}
		}
		command := predType
		if opDesc != "" {
			command += " " + opDesc
		}
		t.Policies = append(t.Policies, Policy{
			Name:    policyName + "/" + predType + "/" + opDesc,
			Command: command,
			Using:   def,
		})
	}
	if err := polRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: security policies: %w", err)
	}
	polRows.Close()

	// 'TR' (triggers) joined cleat#2432: a trigger object carries its own
	// schema_id and OBJECT_DEFINITION returns its body exactly as it does for
	// a procedure or function, so widening this one IN-list is the whole
	// change -- no separate sys.triggers query is needed for name/body/schema,
	// only for the settings (is_disabled, QUOTED_IDENTIFIER/ANSI_NULLS) that
	// remain supplementary-only per this file's header comment.
	rtRows, err := db.QueryContext(ctx, `
		SELECT s.name, o.name, o.type_desc, COALESCE(OBJECT_DEFINITION(o.object_id), '')
		FROM sys.objects o
		JOIN sys.schemas s ON s.schema_id = o.schema_id
		WHERE o.type IN ('P', 'FN', 'IF', 'TF', 'TR')
		ORDER BY s.name, o.name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing routines: %w", err)
	}
	for rtRows.Next() {
		var schema, name, typeDesc, def string
		if err := rtRows.Scan(&schema, &name, &typeDesc, &def); err != nil {
			rtRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning routine: %w", err)
		}
		cat.Routines[fmt.Sprintf("%s.%s (%s)", schema, name, typeDesc)] = def
	}
	if err := rtRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing routines: %w", err)
	}
	rtRows.Close()

	grantRows, err := db.QueryContext(ctx, `
		SELECT grantee_principal.name, s.name, o.name, dp.permission_name
		FROM sys.database_permissions dp
		JOIN sys.objects o ON o.object_id = dp.major_id
		JOIN sys.schemas s ON s.schema_id = o.schema_id
		JOIN sys.database_principals grantee_principal ON grantee_principal.principal_id = dp.grantee_principal_id
		WHERE dp.class = 1 AND dp.state = 'G'
		ORDER BY 1, 2, 3, 4
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing grants: %w", err)
	}
	for grantRows.Next() {
		var grantee, schema, obj, perm string
		if err := grantRows.Scan(&grantee, &schema, &obj, &perm); err != nil {
			grantRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning grant: %w", err)
		}
		cat.Grants = append(cat.Grants, fmt.Sprintf("%s ON %s.%s TO %s", perm, schema, obj, grantee))
	}
	if err := grantRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing grants: %w", err)
	}
	grantRows.Close()

	// Schemas -- cleat#2432. schema_id < 16384 excludes SQL Server's own
	// fixed/built-in schemas (dbo itself is 1, so it IS included -- dbo is a
	// migration-visible fact, not a server internal); this is the exact
	// predicate scripts/gen-mssql-baseline's supplementary "schemas" check
	// already uses and has validated.
	schemaRows, err := db.QueryContext(ctx, `
		SELECT name FROM sys.schemas WHERE schema_id < 16384 ORDER BY name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing schemas: %w", err)
	}
	for schemaRows.Next() {
		var name string
		if err := schemaRows.Scan(&name); err != nil {
			schemaRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning schema: %w", err)
		}
		cat.Schemas = append(cat.Schemas, name)
	}
	if err := schemaRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing schemas: %w", err)
	}
	schemaRows.Close()

	// Database roles -- EXISTENCE only, cleat#2432. is_fixed_role excludes
	// SQL Server's own built-in roles (db_owner, db_datareader, ...) and the
	// name exclusion drops 'public', which is type='R' but not is_fixed_role
	// and would otherwise appear identically on every database compared.
	// Membership is deliberately not captured here -- it is a deployment
	// fact, not a schema fact, matching the supplementary check's own stated
	// reasoning for the same exclusion.
	roleRows, err := db.QueryContext(ctx, `
		SELECT name FROM sys.database_principals
		WHERE type = 'R' AND is_fixed_role = 0 AND name <> 'public'
		ORDER BY name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing roles: %w", err)
	}
	for roleRows.Next() {
		var name string
		if err := roleRows.Scan(&name); err != nil {
			roleRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning role: %w", err)
		}
		cat.Roles = append(cat.Roles, name)
	}
	if err := roleRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing roles: %w", err)
	}
	roleRows.Close()

	return cat, nil
}
