package catalogdiff

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strings"

	"github.com/cleat-team/cleat/migration"
)

// autoGeneratedMSSQLName matches the names SQL Server invents for a
// constraint (and its backing index, which gets the same name) when the
// migration that created it left the name out -- e.g. "PK__schema_m__79B5C94C1DA7B4EB".
// The trailing segment is derived from the object_id and is not
// reproducible across two independently-built databases: measured on
// schema_migrations' bootstrap table, 2026-09-19, two builds of the
// identical migration chain produced "PK__schema_m__79B5C94C1DA7B4EB" and
// "PK__schema_m__79B5C94CC1648A3B" -- same prefix, different everything
// after it. A snapshot comparison that includes the raw name treats every
// unnamed constraint as a difference whether or not anything actually
// changed, which is exactly backwards for a schema-equality check: it is
// the SAME hazard schemaMigrationsTable's own exclusion exists for, but it
// is not limited to that one table -- any migration-defined or
// plugin-defined table with an unnamed inline constraint hits it too. See
// cleat#2306 phase 2, where the recoverable-vs-proven comparison snapshots
// plugin-created tables that may carry unnamed constraints of their own.
var autoGeneratedMSSQLName = regexp.MustCompile(`^[A-Za-z]{2,3}__.+__[0-9A-Fa-f]{8,}$`)

// normalizeMSSQLName replaces name with a stable placeholder when it looks
// SQL-Server-generated, so two constraints (or indexes) that are
// structurally identical but auto-named compare equal regardless of the
// random suffix. kind disambiguates the placeholder so an auto-named PK
// and an auto-named DEFAULT constraint on the same table are never
// conflated with each other -- only with another auto-named constraint of
// the SAME kind, which Definition (columns, or default expression + target
// column) still distinguishes.
func normalizeMSSQLName(name, kind string) string {
	if autoGeneratedMSSQLName.MatchString(name) {
		return "<auto:" + kind + ">"
	}
	return name
}

// snapshotMSSQL builds a Catalog for a SQL Server database. Core migrations
// create no SECURITY POLICY objects on this dialect -- tenant isolation on
// SQL Server is a contained-user/role mechanism, not row-level security, per
// docs/schema-partitioning-design.md's work plan -- so, as with MySQL, every
// Table's RowSecurity is nil and Policies is empty here.
func snapshotMSSQL(ctx context.Context, db *sql.DB) (*Catalog, error) {
	cat := &Catalog{
		Dialect:  migration.DialectMSSQL,
		Tables:   map[string]*Table{},
		Routines: map[string]string{},
	}

	type tableRow struct {
		objectID     int64
		schema, name string
	}
	rows, err := db.QueryContext(ctx, `
		SELECT t.object_id, s.name, t.name
		FROM sys.tables t
		JOIN sys.schemas s ON s.schema_id = t.schema_id
		ORDER BY s.name, t.name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing tables: %w", err)
	}
	var tables []tableRow
	for rows.Next() {
		var r tableRow
		if err := rows.Scan(&r.objectID, &r.schema, &r.name); err != nil {
			rows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning table row: %w", err)
		}
		if r.name == schemaMigrationsTable {
			continue
		}
		tables = append(tables, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing tables: %w", err)
	}
	rows.Close()

	for _, tr := range tables {
		qname := tr.schema + "." + tr.name
		t := &Table{Name: qname}

		colRows, err := db.QueryContext(ctx, `
			SELECT c.name, ty.name, c.is_nullable,
			       COALESCE(OBJECT_DEFINITION(c.default_object_id), '')
			FROM sys.columns c
			JOIN sys.types ty ON ty.user_type_id = c.user_type_id
			WHERE c.object_id = @p1
			ORDER BY c.column_id
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: columns for %s: %w", qname, err)
		}
		for colRows.Next() {
			var name, dtype string
			var nullable bool
			var def string
			if err := colRows.Scan(&name, &dtype, &nullable, &def); err != nil {
				colRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning column for %s: %w", qname, err)
			}
			t.Columns = append(t.Columns, Column{Name: name, DataType: dtype, Nullable: nullable, Default: def})
		}
		if err := colRows.Err(); err != nil {
			return nil, fmt.Errorf("catalogdiff: columns for %s: %w", qname, err)
		}
		colRows.Close()

		idxRows, err := db.QueryContext(ctx, `
			SELECT i.name, i.is_unique, i.type_desc,
			       STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal)
			FROM sys.indexes i
			JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE i.object_id = @p1 AND i.name IS NOT NULL
			GROUP BY i.name, i.is_unique, i.type_desc
			ORDER BY i.name
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: indexes for %s: %w", qname, err)
		}
		for idxRows.Next() {
			var name, typeDesc, cols string
			var unique bool
			if err := idxRows.Scan(&name, &unique, &typeDesc, &cols); err != nil {
				idxRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning index for %s: %w", qname, err)
			}
			// columns is part of the Definition (not just the name) precisely
			// so that normalizeMSSQLName can collapse two auto-generated names
			// for DIFFERENT indexes without losing the ability to tell them
			// apart -- see the comment on that function.
			t.Indexes = append(t.Indexes, Index{
				Name:       normalizeMSSQLName(name, "IDX"),
				Definition: fmt.Sprintf("unique=%t type=%s columns=%s", unique, typeDesc, cols),
			})
		}
		if err := idxRows.Err(); err != nil {
			return nil, fmt.Errorf("catalogdiff: indexes for %s: %w", qname, err)
		}
		idxRows.Close()

		// Every branch's Definition carries the COLUMN(S) it applies to, not
		// just its kind -- required so that normalizeMSSQLName (applied
		// below) can strip an auto-generated name without two distinct
		// constraints of the same kind on the same table (two DEFAULTs, two
		// UNIQUEs, two FOREIGN KEYs) collapsing onto an identical line and
		// silently losing one from the comparison.
		conRows, err := db.QueryContext(ctx, `
			SELECT name, 'CHECK ' + COALESCE(OBJECT_DEFINITION(object_id), '')
			FROM sys.check_constraints WHERE parent_object_id = @p1
			UNION ALL
			SELECT dc.name, 'DEFAULT ' + COALESCE(OBJECT_DEFINITION(dc.object_id), '') + ' FOR ' + c.name
			FROM sys.default_constraints dc
			JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
			WHERE dc.parent_object_id = @p1
			UNION ALL
			SELECT kc.name, 'PRIMARY KEY (' + STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) + ')'
			FROM sys.key_constraints kc
			JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id AND ic.index_id = kc.unique_index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE kc.parent_object_id = @p1 AND kc.type = 'PK'
			GROUP BY kc.name
			UNION ALL
			SELECT kc.name, 'UNIQUE (' + STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) + ')'
			FROM sys.key_constraints kc
			JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id AND ic.index_id = kc.unique_index_id
			JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
			WHERE kc.parent_object_id = @p1 AND kc.type = 'UQ'
			GROUP BY kc.name
			UNION ALL
			SELECT fk.name, 'FOREIGN KEY (' + STRING_AGG(pc.name, ',') WITHIN GROUP (ORDER BY fkc.constraint_column_id) + ') REFERENCES ' + OBJECT_NAME(fk.referenced_object_id)
			FROM sys.foreign_keys fk
			JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
			JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
			WHERE fk.parent_object_id = @p1
			GROUP BY fk.name, fk.referenced_object_id
			ORDER BY 1
		`, tr.objectID)
		if err != nil {
			return nil, fmt.Errorf("catalogdiff: constraints for %s: %w", qname, err)
		}
		for conRows.Next() {
			var name, def string
			if err := conRows.Scan(&name, &def); err != nil {
				conRows.Close()
				return nil, fmt.Errorf("catalogdiff: scanning constraint for %s: %w", qname, err)
			}
			kind := strings.SplitN(def, " ", 2)[0]
			t.Constraints = append(t.Constraints, Constraint{Name: normalizeMSSQLName(name, kind), Definition: def})
		}
		if err := conRows.Err(); err != nil {
			return nil, fmt.Errorf("catalogdiff: constraints for %s: %w", qname, err)
		}
		conRows.Close()

		cat.Tables[qname] = t
	}

	rtRows, err := db.QueryContext(ctx, `
		SELECT s.name, o.name, o.type_desc, COALESCE(OBJECT_DEFINITION(o.object_id), '')
		FROM sys.objects o
		JOIN sys.schemas s ON s.schema_id = o.schema_id
		WHERE o.type IN ('P', 'FN', 'IF', 'TF')
		ORDER BY s.name, o.name
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing routines: %w", err)
	}
	for rtRows.Next() {
		var schema, name, typeDesc, def string
		if err := rtRows.Scan(&schema, &name, &typeDesc, &def); err != nil {
			rtRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning routine: %w", err)
		}
		cat.Routines[fmt.Sprintf("%s.%s (%s)", schema, name, typeDesc)] = def
	}
	if err := rtRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing routines: %w", err)
	}
	rtRows.Close()

	grantRows, err := db.QueryContext(ctx, `
		SELECT grantee_principal.name, s.name, o.name, dp.permission_name
		FROM sys.database_permissions dp
		JOIN sys.objects o ON o.object_id = dp.major_id
		JOIN sys.schemas s ON s.schema_id = o.schema_id
		JOIN sys.database_principals grantee_principal ON grantee_principal.principal_id = dp.grantee_principal_id
		WHERE dp.class = 1 AND dp.state = 'G'
		ORDER BY 1, 2, 3, 4
	`)
	if err != nil {
		return nil, fmt.Errorf("catalogdiff: listing grants: %w", err)
	}
	for grantRows.Next() {
		var grantee, schema, obj, perm string
		if err := grantRows.Scan(&grantee, &schema, &obj, &perm); err != nil {
			grantRows.Close()
			return nil, fmt.Errorf("catalogdiff: scanning grant: %w", err)
		}
		cat.Grants = append(cat.Grants, fmt.Sprintf("%s ON %s.%s TO %s", perm, schema, obj, grantee))
	}
	if err := grantRows.Err(); err != nil {
		return nil, fmt.Errorf("catalogdiff: listing grants: %w", err)
	}
	grantRows.Close()

	return cat, nil
}
