// Code generated by durable-gen. DO NOT EDIT.

package menu

import "github.com/rcownie/durable/durable"

type LookupItemRequest struct {
	RestaurantID string `json:"restaurant_id"`
	SKU          string `json:"sku"`
}

type LookupItemResponse struct {
	SKU        string `json:"sku"`
	Name       string `json:"name"`
	PriceCents int    `json:"price_cents"`
	Available  bool   `json:"available"`
}

type Client struct {
	h durable.HostCalls
}

func NewClient(h durable.HostCalls) *Client {
	return &Client{h: h}
}

func (c *Client) LookupItem(req LookupItemRequest) (*LookupItemResponse, error) {
	var resp LookupItemResponse
	if err := c.h.DurableCallTyped("menu", "LookupItem", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
